.gitignore, src/IdentityServer/Configuration/DependencyInjection/Options/IdentityServerOptions.cs, src/IdentityServer/Configuration/IdentityServerApplicationBuilderExtensions.cs, src/IdentityServer/Hosting/IdentityServerMiddleware.cs, src/IdentityServer/Services/Default/DefaultDeviceFlowInteractionService.cs, src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs, src/IdentityServer/Validation/Default/LicenseValidator.cs, src/IdentityServer/Validation/Default/TokenRequestValidator.cs
This adds logic for reading and validating a license key and validating runtime usage against what a license allows.
=> License validation

src/IdentityServer/Services/Default/DefaultTokenService.cs, src/Storage/Models/Token.cs, test/IdentityServer.UnitTests/Common/MockTokenCreationService.cs, test/IdentityServer.UnitTests/Services/Default/DefaultTokenServiceTests.cs
Persisted/Cached access tokens stored in the refresh token persisted grant kept JTI as claim in DB, and new access tokens were not generating new JTI each renewal.
* add property to Token to indicate need for jti
* move jti creation to CreateSecurityTokenAsync and out of CreateAccessTokenAsync
* handle older tokens that do not have new property
=> Create JTI on each new access token

Directory.Build.targets, src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs, src/IdentityServer/Configuration/DependencyInjection/Options/IdentityServerOptions.cs, src/Storage/Duende.IdentityServer.Storage.csproj, src/Storage/Stores/Serialization/ClaimConverter.cs, src/Storage/Stores/Serialization/ClaimsPrincipalConverter.cs, src/Storage/Stores/Serialization/PersistentGrantSerializer.cs
This makes the "Data" column for the persisted grant store a generic container capable of having metadata without changing the entire table structure. The actual payload is now a value inside the container. 
The first real feature this allows is data protection of the payload itself.
=> Enable data protection on persisted grants

src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs, src/IdentityServer/Endpoints/DiscoveryEndpoint.cs, src/IdentityServer/Extensions/IdentityServerToolsExtensions.cs, src/IdentityServer/IdentityServerTools.cs, src/IdentityServer/Services/Default/DefaultIssuerNameService.cs, src/IdentityServer/Services/Default/DefaultTokenService.cs, src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs, src/IdentityServer/Services/Default/LogoutNotificationService.cs, src/IdentityServer/Services/IIssuerNameService.cs, src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs, src/IdentityServer/Validation/Default/JwtRequestValidator.cs, src/IdentityServer/Validation/Default/PrivateKeyJwtSecretValidator.cs, src/IdentityServer/Validation/Default/TokenRequestValidator.cs, src/IdentityServer/Validation/Default/TokenValidator.cs, src/IdentityServer/Validation/Models/ValidatedRequest.cs, test/IdentityServer.UnitTests/Services/Default/KeyManagement/KeyManagerTests.cs, test/IdentityServer.UnitTests/Validation/Secrets/PrivateKeyJwtSecretValidation.cs, test/IdentityServer.UnitTests/Validation/Setup/Factory.cs, test/IdentityServer.UnitTests/Validation/Setup/TestIssuerNameService.cs
* Adds the `IIssuerNameService`
* Sets the issuer name for the current request on the `ValidatedRequest` object
This will allow removing direct dependencies on `IHttpContextAccessor` in various places
=> Add abstraction for retrieving the issuer name for the current request

src/IdentityServer/Extensions/AuthorizeResponseExtensions.cs, src/IdentityServer/ResponseHandling/Default/AuthorizeResponseGenerator.cs, src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs, src/IdentityServer/ResponseHandling/Models/AuthorizeResponse.cs, test/IdentityServer.IntegrationTests/Endpoints/Authorize/AuthorizeTests.cs
Adds support for the `iss` response parameter for authorization code flows. This helps clients mitigate the "AS Mix-up Attack".
https://www.ietf.org/archive/id/draft-meyerzuselhausen-oauth-iss-auth-resp-02.html
=> iss Response Parameter

src/Storage/Stores/Serialization/ClaimConverter.cs, src/Storage/Stores/Serialization/ClaimsPrincipalConverter.cs, src/Storage/Stores/Serialization/PersistentGrantSerializer.cs
Do not emit claim value type if it's a string.
=> Optimize claims serialization for persisted grants

src/IdentityServer/Configuration/DependencyInjection/Options/IdentityServerOptions.cs, src/IdentityServer/ResponseHandling/Default/AuthorizeResponseGenerator.cs, test/IdentityServer.IntegrationTests/Common/IdentityServerPipeline.cs, test/IdentityServer.IntegrationTests/Conformance/Basic/CodeFlowTests.cs
=> Add option to specify whether s_hash should be emitted.

src/IdentityServer/Extensions/KeyManagementExtensions.cs, src/IdentityServer/Services/Default/DefaultRefreshTokenService.cs, src/IdentityServer/Services/Default/KeyManagement/InMemoryKeyStoreCache.cs, src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs, test/IdentityServer.UnitTests/Services/Default/KeyManagement/InMemoryKeyStoreCacheTests.cs, test/IdentityServer.UnitTests/Services/Default/KeyManagement/KeyManagerTests.cs
During key management initialization there is an edge case that could cause an unhanded exception with the message "Failed to create and then load new keys.". This could be seen during requests to the discovery and keys endpoint. 
The conditions that would trigger this edge case were when no keys had yet been created, a low rotation interval configured (common when testing), and if the local time zone was after UTC. With typical production settings for the rotation interval, this initialization error would not occur and the normal key management processing would execute properly.
The bug was caused due to an incorrect use of non-UTC DateTimeOffset API, and the fix is to use the correct UTC version of the API.
=> Fix misuse DateTimeOffset and UTC in KeyManagement

src/IdentityServer/Validation/Default/LicenseValidator.cs, test/IdentityServer.UnitTests/Validation/LicenseValidatorTests.cs
#81 
- always emit license key details
- hide internal License flags
- add edition to summary
=> Improve license logging at startup

src/IdentityServer/Endpoints/Results/CustomRedirectResult.cs
If a custom redirect is returned from the `IAuthorizeInteractionResponseGenerator`'s `ProcessInteractionAsync`, the intent is to allow a custom UI to process the login and possibly the consent workflow. The returnUrl passed to this custom redirect would then allow IdentityServer to complete the workflow, but the wrong returnURl was being used. It would work correctly if the custom redirect simply logged the user in, but if it was also trying to issue any sort of consent response (grant or access denied) then the use of the incorrect callback endpoint was not "looking for" the consent result. This fix changes the return URL to be the same one that the normal login and consent workflows use, thus allowing a custom redirect to work the same.
Fixes #103
=> Bug fix for custom redirects from IAuthorizeInteractionResponseGenerator

src/IdentityServer/Extensions/AuthenticationPropertiesExtensions.cs, src/IdentityServer/Services/Default/DefaultUserSession.cs, test/IdentityServer.UnitTests/Services/Default/DefaultUserSessionTests.cs
Currently, if a user re-authenticates on the login page then the current `sid` and list of tracked clients (for logout purposes) is overwritten and lost. This change preserves those values.
If there has been any custom code written around setting the `sid` value on the `AuthenticationProperties` when signing in a user in any of your custom login workflows, then it should be tested thoroughly given this change.
Original issue: #45.
=> Preserve user session when same user re-authenticating

hosts/EntityFramework/Startup.cs, migrations/IdentityServerDb/Migrations/ConfigurationDb.sql, migrations/IdentityServerDb/Migrations/ConfigurationDb/20210118185536_Configuration.Designer.cs, migrations/IdentityServerDb/Migrations/ConfigurationDb/20210118185536_Configuration.cs, migrations/IdentityServerDb/Migrations/ConfigurationDb/ConfigurationDbContextModelSnapshot.cs, migrations/IdentityServerDb/Migrations/PersistedGrantDb.sql, migrations/IdentityServerDb/Migrations/PersistedGrantDb/20210118185528_Grants.Designer.cs, migrations/IdentityServerDb/Migrations/PersistedGrantDb/20210118185528_Grants.cs, migrations/IdentityServerDb/Migrations/PersistedGrantDb/PersistedGrantDbContextModelSnapshot.cs, src/EntityFramework.Storage/Extensions/ModelBuilderExtensions.cs, src/EntityFramework.Storage/Options/OperationalStoreOptions.cs, src/EntityFramework.Storage/TokenCleanup/TokenCleanupService.cs
[Operational Data](https://docs.duendesoftware.com/identityserver/v5/data/operational/) in IdentityServer produces state that is essential to supporting the OIDC and OAuth protocols. Under normal protocol workflows, this state will eventually be marked as [consumed](https://docs.duendesoftware.com/identityserver/v5/data/operational/grants/#grant-expiration-and-consumption), but the record in the store will remain. These records, without intervention, will remain in the store.
When using our [EF integration](https://docs.duendesoftware.com/identityserver/v5/data/ef/) for operational data, an automatic mechanism is provided to cleanup expired records via a [configuration flag](https://docs.duendesoftware.com/identityserver/v5/data/ef/#operationalstoreoptions). This existing feature only …
=> add feature to cleanup consumed tokens

src/IdentityServer/Endpoints/Results/ConsentPageResult.cs, src/IdentityServer/Endpoints/Results/CustomRedirectResult.cs, src/IdentityServer/Endpoints/Results/LoginPageResult.cs, src/IdentityServer/Extensions/ValidatedAuthorizeRequestExtensions.cs, test/IdentityServer.IntegrationTests/Endpoints/Authorize/JwtRequestAuthorizeTests.cs
When a JWT request or request URI is used to pass authorize request parameters, internally (after validation of the JWT) we merge those values into the data structure that holds the original query params. When we redirect to any UI page (e.g. the login page) we then create the `returnUrl` to return back to the authorize endpoint from that internal data structure. This ends up with the `request` parameter (which is a sizable JWT) and then all the contents of the JWT as redundant parameters in the `returnUrl`.
This fix optimizes this process by omitting those redundant JWT request object query values in the `returnUrl`.
Original issue: #128
=> optimize URLs for JWT request/request URI scenarios

src/IdentityServer/Endpoints/Results/CustomRedirectResult.cs, test/IdentityServer.IntegrationTests/Common/IdentityServerPipeline.cs, test/IdentityServer.IntegrationTests/Endpoints/Authorize/AuthorizeTests.cs
If a custom redirect is triggered from the authorize endpoint interaction response generator, and if a custom authorize parameter message store is registered, it will not be used. This fix changes it so that a custom redirect will use the store if registered in the same way the login and consent workflows do.
Original issue: #137
=> Fix CustomRedirectResult to use IAuthorizationParametersMessageStore if registered

src/IdentityServer/Extensions/IReadableStringCollectionExtensions.cs, test/IdentityServer.IntegrationTests/Endpoints/Authorize/AuthorizeTests.cs
Currently `GetAuthorizationContextAsync` does not return multiple query values from returnUrl. For example, if the returnUrl (which is the original authorize request URL) contains multiple `resource` parameters and is passed to `GetAuthorizationContextAsync`, then the resultant `Parameters` will only contain one `resource` value.
This change fixes it so that all query values are returned. The `GetValues` API on the `NameValueCollection` should be used to access the query params when multiple values are possible.
Fixes: #141
=> Fix GetAuthorizationContextAsync to return multiple query values from returnUrl

test/IdentityServer.IntegrationTests/Clients/ExtensionGrantClient.cs
Several tests seems to fail frequently on slower test machines when we check expected expiration values. This is a temp workaround to widen those windows of time to accommodate the server load.
=> Adjust time window for tests that check expirations

src/IdentityServer/Validation/Default/EndSessionRequestValidator.cs
`SetClient` copies over additional properties, so this is better so as to be consistent.
Fixes: #185
=> use SetClient rather than setting Client property directly in end session validator

src/IdentityServer/Validation/Default/LicenseValidator.cs, test/IdentityServer.UnitTests/Validation/LicenseValidatorTests.cs
For business and enterprise ISV editions, we were not setting the default client limit correctly. This PR fixes that.
=> Set license defaults for business and enterprise ISV editions

src/IdentityServer/Configuration/DependencyInjection/Options/IdentityServerOptions.cs, src/IdentityServer/Extensions/PrincipalExtensions.cs, src/IdentityServer/IdentityServerConstants.cs, src/IdentityServer/IdentityServerUser.cs, src/IdentityServer/ResponseHandling/Default/AuthorizeInteractionResponseGenerator.cs, test/IdentityServer.IntegrationTests/Endpoints/Authorize/AuthorizeTests.cs, test/IdentityServer.IntegrationTests/Endpoints/Authorize/ConsentTests.cs, test/IdentityServer.UnitTests/ResponseHandling/AuthorizeInteractionResponseGenerator/AuthorizeInteractionResponseGeneratorTests.cs, test/IdentityServer.UnitTests/ResponseHandling/AuthorizeInteractionResponseGenerator/AuthorizeInteractionResponseGeneratorTests_Consent.cs, test/IdentityServer.UnitTests/ResponseHandling/AuthorizeInteractionResponseGenerator/AuthorizeInteractionResponseGeneratorTests_Custom.cs, test/IdentityServer.UnitTests/ResponseHandling/AuthorizeInteractionResponseGenerator/AuthorizeInteractionResponseGeneratorTests_Login.cs
In the authorize interaction response generator we have special handling for the `idp` claim in the user's session and comparing that against our special `idp:tenant` processing in the acr_values request param, and if it does not match we require the user to login.
This PR adds a similar check (and thus more first class support) for our acr_values `tenant:tenantid` processing. In short, it checks for a `tenant` claim and compares to the acr value and if they don't match it forces the user to re-authenticate.
=> add support for user tenant check in authorize interaction response generator against acr tenant value

src/IdentityServer/Services/Default/DefaultCache.cs
This enhancement makes the `DefaultCache` class easier to use from a derived implementation. 
Fixes: #164
=> Open up DefaultCache for derived implementations 

src/IdentityServer/Configuration/DependencyInjection/Options/UserInteractionOptions.cs, src/IdentityServer/Services/Default/OidcReturnUrlParser.cs, test/IdentityServer.UnitTests/Services/Default/OidcReturnUrlParserTests.cs
When validating return URLs we only allowed local paths to be accepted. But there is desire to allow the UI for login to outside the IdentityServer host, thus when they receive the returnUrl on the login page the full URL will be passed (including the host). 
This PR now allows the exact IdentityServer host to be included in the returnUrl for validation.
Fixes: #173
=> Allow full host name to be included in OidcReturnUrlParser's IsValidReturnUrl

src/IdentityServer/ResponseHandling/Default/AuthorizeInteractionResponseGenerator.cs
If during the UI workflow a user is logged in, and an explicit authorize error response is expressed via the `IIdentityServerInteractionService` then the IdentityServer internal plumbing would only honor that error if the client is configured for consent. This PR removes that limitation and so now during any UI workflow if an error response is indicated then it will be returned to the client.
=> Always allow explicit error responses from authorize request

src/IdentityServer/Services/Default/KeyManagement/FileSystemKeyStore.cs
The automatic key management code was accessing the file system earlier than it needed to (most importantly when it was disabled), and on read-only file systems this was throwing an exception. This PR delays file system access until needed.
Fixes: #232
=> delay filesystem access until needed for automatic key management

src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicAuthenticationScheme.cs, src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicAuthenticationSchemeCache.cs
This PR changes the dynamic authentication scheme cache to public. This is needed if a custom dynamic provider needs to have more control in the configure named options code and can't use the built-in ConfigureAuthenticationOptions.
=> change the accessibility to public for the dynamic provider cache

src/IdentityServer/Configuration/DependencyInjection/Options/DynamicProviderOptions.cs
The dynamic providers feature expects the authentication handler to derive from RemoteAuthenticationHandler, but it's possible to implement an external handler with out this base class. This PR relaxes this restriction on this incorrect assumption.
=> relax constraint on handler type when configuring the external provider

src/IdentityServer/Validation/Default/License.cs
adds a ToString for the License for better debugging (when not using Serilog)
=> add a ToString to the License

src/EntityFramework.Storage/Extensions/ModelBuilderExtensions.cs, src/EntityFramework.Storage/Options/OperationalStoreOptions.cs
The "Keys" table in the operational EF database was missing a *TableConfiguration*  to allow changing the table name. This PR adds that option. 
Fixes: https://github.com/DuendeSoftware/IdentityServer/issues/109
=> Add TableConfiguration for "Keys" table in operational EF database

src/IdentityServer/Endpoints/Results/AuthorizeResult.cs, src/IdentityServer/Models/Messages/ConsentResponse.cs, src/IdentityServer/ResponseHandling/Default/AuthorizeInteractionResponseGenerator.cs, test/IdentityServer.IntegrationTests/Endpoints/Authorize/ConsentTests.cs
In a custom login or consent page, there's not way to trigger a general error to be returned back to the client other than errors related to the user choosing to fail the request (for example, access denied). This PR add a *TemporarilyUnavailable* to the *AuthorizationError* enum to allow a custom UI to return a general error/failure message when using the *ConsentRequest* due to some condition happening in the custom UI workflow. This will return the "temporarily_unavailable" error directly back to the client.
For more context: https://github.com/DuendeSoftware/IdentityServer/discussions/203
Fixes: #205
=> Add temporarily_unavailable error support for ConsentResponse

src/IdentityServer/Endpoints/Results/CustomRedirectResult.cs
*CustomRedirectResult* was using a different API to construct the *returnUrl* which did not work quite right in some hosting scenarios. This changes it to use the same approach the *LoginPageResult* and *ConsentPageResult* use.
This might cause a breaking change for some uses of *CustomRedirectResult* depending on how your IdentityServer is hosted.
=> Fix inconsistency in CustomRedirectResult vs Login and ConsentPageResult

src/EntityFramework.Storage/Stores/ClientStore.cs, test/EntityFramework.Storage.IntegrationTests/IntegrationTest.cs
In a prior version of EF we were forced to break up the queries when loading a *Client* to make an individual round trip for each child table. EF6 seems improved to allow the code to go back to a more natural form using `.Include` for the child tables/entities, which results in a single round trip (albeit using joins to fetch the child table table: #298).
=> [EF] Optimize client query to use a single DB round trip

src/IdentityServer/Extensions/ResourceExtensions.cs, src/IdentityServer/Services/Default/OidcReturnUrlParser.cs, src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs, src/IdentityServer/Validation/Default/DefaultClientConfigurationValidator.cs, test/IdentityServer.UnitTests/Validation/AuthorizeRequest Validation/Authorize_ProtocolValidation_Invalid.cs
Uri.TryCreate has unexpected behavior on non-Windows machines. It does accept relative URI as absolute ones (and turns them into `file://` URIs..
=> Replace Uri.TryCreate with Uri.IsWellformedUriString

hosts/EntityFramework/Startup.cs
Now with split queries as a feature in EF, if your query is not explicit on the behavior then EF emits a warning. This suppresses the warning in the EF host.
This [issue](https://github.com/DuendeSoftware/IdentityServer/issues/298) is relevant.
=> Ignore EF warning about split vs non-split queries

hosts/EntityFramework/Startup.cs, src/EntityFramework.Storage/DbContexts/ConfigurationDbContext.cs
Now with split queries as a feature in EF, if your query is not explicit on the behavior then EF emits a warning. This suppresses the warning in the DbContext itself.
This [issue](https://github.com/DuendeSoftware/IdentityServer/issues/298) is relevant.
=> Suppress EF warning about split query behavior

src/IdentityServer/Endpoints/Results/EndSessionCallbackResult.cs, test/IdentityServer.UnitTests/Endpoints/Results/EndSessionCallbackResultTests.cs
Added `allow` and `loading` attributes to the `iframe`s used for front channel logout. 
Fixes: https://github.com/DuendeSoftware/IdentityServer/issues/154
=> Enhancements to front channel logout iframes

src/IdentityServer/Services/Default/DefaultRefreshTokenService.cs, src/Storage/Models/RefreshToken.cs, test/IdentityServer.UnitTests/Services/Default/DefaultPersistedGrantServiceTests.cs, test/IdentityServer.UnitTests/Stores/Default/DefaultPersistedGrantStoreTests.cs
When a refresh token was being created in the grant store, the session id value was being sourced from the wrong place. This most commonly meant that the SessionId column in the persisted grants table was null for refresh tokens.
=> Fix bug when storing session id in refresh token

src/IdentityServer/Stores/Default/DistributedCacheAuthorizationParametersMessageStore.cs, test/IdentityServer.UnitTests/Common/MockDistributedCache.cs, test/IdentityServer.UnitTests/Stores/Default/DistributedCacheAuthorizationParametersMessageStoreTests.cs
=> Fix bug in cache removal for DistributedCacheAuthorizationParametersMessageStore

src/IdentityServer/Infrastructure/DistributedCacheStateDataFormatter.cs
.NET 5 broke JSON serialization for the AuthenticationProperties class (when used in AddOidcStateDataFormatterCache), so we had custom handling for it. .NET 6 fixed the JSON serialization, so this PR removes our workaround for that prior .NET bug.
Fixes: #168
=> Remove custom serialization handling for AuthenticationProperties

hosts/main/Startup.cs, src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Additional.cs, src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs, src/IdentityServer/Events/Infrastructure/EventIds.cs, src/IdentityServer/Events/InvalidClientConfiguration.cs, src/IdentityServer/Events/InvalidIdentityProviderConfiguration.cs, src/IdentityServer/Hosting/DynamicProviders/Oidc/IdentityServerBuilderOidcExtensions.cs, src/IdentityServer/Hosting/DynamicProviders/Store/ValidatingIdentityProviderStore.cs, src/IdentityServer/Validation/Contexts/IdentityProviderConfigurationValidationContext.cs, src/IdentityServer/Validation/Default/DefaultIdentityProviderConfigurationValidator.cs, src/IdentityServer/Validation/IIdentityProviderConfigurationValidator.cs, test/IdentityServer.UnitTests/Validation/IdentityProviderConfigurationValidation.cs
This PR adds infrastructure to validate OidcProvider models that are being loaded from the database when using the [dynamic providers](https://docs.duendesoftware.com/identityserver/v5/ui/login/dynamicproviders/) feature. This ensures that the configuration necessary to support the identity provider has been set properly and provides errors for the missing or invalid configuration.
Fixes: #275
=> Add IdentityProvider validator

src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs, src/IdentityServer/Configuration/DependencyInjection/IdentityServerServiceCollectionExtensions.cs, src/IdentityServer/Hosting/IdentityServerAuthenticationService.cs
When registering IdentityServer in the DI system, we have a `AddCookieAuthentication` API to add the default services needed by IdentityServer. If you want more fine grained control over the cookie authentication handler, a custom one can be registered, but with the above `AddCookieAuthentication` our default is still added but unused. 
This PR introduces new APIs to allow finer grained control over how much of our default cookie authentication services are added to the host. A `AddDefaultCookieHandlers` API will register our default cookie handlers and `AddCookieAuthenticationExtensions` API will add our mandatory decorators (and other services) that IdentityServer needs for session management.
The existing `AddCookieAuthentication` remains the same and now internally just invokes the …
=> Add finer grained IdentityServerBuilderExtensions for registering cookie authentication services

src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs
Some child properties on the IdentityServerOptions are put into DI (for various reasons). They are put into DI as singleton, but that means there's more to be done when multi-tenancy is desired and options need to be scoped. This PR changes the default for thise child properties to be transient to make it easier for developers wanting to support multi-tenancy.
=> Change lifetime of nested options in DI to be more multi-tenant friendly

src/IdentityServer/Hosting/DynamicProviders/Store/CachingIdentityProviderStore.cs, src/IdentityServer/Stores/Caching/CachingResourceStore.cs, test/IdentityServer.UnitTests/Common/MockCache.cs, test/IdentityServer.UnitTests/Stores/Default/CachingResourceStoreTests.cs
The resource store cache caches items based on the collection of requested items (e.g. scopes), rather then caching individual items. It was done that way given the expectation that client apps will make all of their requests with the same set of scopes, so instead of breaking down the cache into individual items, we used the entire set of scopes requested as the key and the entire set of matching resources is what's cached.
This PR changes that and stores items individually by name in the appropriate cache. This now requires items to be looked up first in the cache one by one, and then any remaining items requested not found in the cache to be looked up in the store, and then those results cached one by one.
=> Change cache design for resource store cache

build/build.csproj
The versions in the csproj are not used. They are controlled by the top level `Directory.Build.targets`.
This totally threw me when I was trying to run the build for https://github.com/DuendeSoftware/IdentityServer/pull/501
=> fix Bullseye and SimpleExec refs

src/IdentityServer/Hosting/DynamicProviders/Oidc/OidcConfigureOptions.cs, src/Storage/Models/OidcProvider.cs
This PR adds two new properties to the `OidcProvider` class to control the OIDC configuration:
* UsePkce (bool)
* GetClaimsFromUserInfoEndpoint (bool)
Both default to `true`. These two values were previously hard coded, so they can now be disabled (if needed).
Also, the calculated `Scopes` collection (based on the `Scope` property) no longer automatically adds `openid` to the returned collection. This is technically a breaking change, but would only manifest if the `Scope` is set and `openid` was omitted from the list of values.
Fixes: https://github.com/DuendeSoftware/IdentityServer/issues/484
Fixes: https://github.com/DuendeSoftware/IdentityServer/issues/493
=> Improvement to OidcProvider

src/IdentityServer/ResponseHandling/Default/BackchannelAuthenticationResponseGenerator.cs
Bug: Was using local date for creation time. Fix is to now use UTC date for creation for `BackChannelAuthenticationRequest`.
=> fix creation time to be utc (not local time)

clients/src/ConsoleCibaClient/Program.cs, hosts/AspNetIdentity/Pages/Ciba/Consent.cshtml.cs, hosts/AspNetIdentity/Pages/Ciba/Index.cshtml.cs, hosts/EntityFramework/Pages/Ciba/Consent.cshtml.cs, hosts/EntityFramework/Pages/Ciba/Index.cshtml.cs, hosts/main/Pages/Ciba/Consent.cshtml.cs, hosts/main/Pages/Ciba/Index.cshtml.cs, src/IdentityServer/Services/Default/DefaultBackchannelAuthenticationInteractionService.cs, src/IdentityServer/Services/IBackchannelAuthenticationInteractionService.cs, src/IdentityServer/Stores/Default/DefaultBackChannelAuthenticationRequestStore.cs, src/IdentityServer/Validation/Default/BackchannelAuthenticationRequestIdValidator.cs, src/Storage/Models/BackChannelAuthenticationRequest.cs, src/Storage/Stores/IBackChannelAuthenticationRequestStore.cs, test/EntityFramework.Tests/EntityFramework.Tests.csproj, test/IdentityServer.IntegrationTests/Endpoints/Token/CibaTokenEndpointTests.cs, test/IdentityServer.UnitTests/Common/MockBackChannelAuthenticationRequestStore.cs, test/IdentityServer.UnitTests/Common/MockSystemClock.cs, test/IdentityServer.UnitTests/Services/Default/DefaultBackchannelAuthenticationInteractionServiceTests.cs
This will allow scenarios where use can consent to login request via non-browser mechanisms (e.g. native app on phone).
=> Add support to set subject for ciba login request outside of browser session

src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicAuthenticationSchemeProvider.cs
If the `IAuthenticationSchemeProvider` is used outside an HTTP request, then our `DynamicAuthenticationSchemeProvider` decorator would fail when resolving services from the `IHttpContextAccessor`. This change fails gracefully in that situation and logs a debug warning message.
=> Add warning when using dynamic provider outside http request

hosts/AspNetIdentity/Pages/ExternalLogin/Callback.cshtml.cs
In the ASP.NET Identity host, we were failing to capture the "idp" claim when the user used an external IdP. This PR adds it to the user's session.
=> Add idp claim to uer's claims when using external idp

src/IdentityServer/Validation/Default/StrictRedirectUriValidatorAppAuth.cs
The AppAuth redirect validator checked the redirect URI collection for logout. This is has been updated to use the post logout redirect URIs instead.
=> Fix PostLogout check in AppAuth redirect validator

src/AspNetIdentity/IdentityServerBuilderExtensions.cs, src/AspNetIdentity/UserClaimsFactory.cs
ASP.NET Identity will [now] issue an email claim in its `UserClaimsFactory`. This means we no longer have to in our decorator.
=> Adjust ASP.NET Identity integration to use EmailClaimType option

src/EntityFramework.Storage/DbContexts/ConfigurationDbContext.cs
When EF DbContext pooling is enabled for our ConfigurationDbContext, the EF options builder can't be modified more than one in OnConfiguring. This PR prevents us from trying to modify the options more than once.
Fixes:  #645
=> Fix OnConfiguring exception from EF when DbContext pooling is enabled

src/IdentityServer/Validation/Default/DefaultIdentityProviderConfigurationValidator.cs, test/IdentityServer.UnitTests/Validation/IdentityProviderConfigurationValidation.cs
In 6.0 the concept of `IIdentityProviderConfigurationValidator` was introduced. This allows some minimal validation of the `OidcProvider` data stored when using the [dynamic provider feature](https://docs.duendesoftware.com/identityserver/v6/ui/login/dynamicproviders/). As part of this validation the client secret is checked, but given that the secret is a special value that might need to be stored elsewhere and configured after loading the IdP data from the database, it makes sense to not require in our store.
This PR removes the validation logic to require the client secret in the identity provider store.
Fixes: #647
=> Allow empty secret when validating OIDC IDP config

src/IdentityServer/Logging/ILoggerExtensions.cs
Provides logging extensions that
* check the log level first
* do not allocate arrays if not needed
* avoid boxing if not needed
=> Optimize trace/debug logging

src/IdentityServer/Services/Default/NumericUserCodeGenerator.cs
.NET Core 3.0+ have this capability built-in, so use that instead of rolling it.
=> Use the built-in CSPRNG GetInt32

src/EntityFramework.Storage/Extensions/StringsExtensions.cs, src/IdentityServer/Extensions/StringsExtensions.cs, test/IdentityServer.UnitTests/Extensions/StringExtensionsTests.cs
Replaces our home grown logic with the built-in String.Join implementation which is more efficient
=> Replace home grown logic of ToSpaceSeparatedString with String.Join

clients/src/ConsoleDeviceFlow/Program.cs, src/EntityFramework.Storage/Stores/DeviceFlowStore.cs
In the device flow, when the user does their interaction and updates the grant we were not capturing the session id or the description from the user's interaction. This PR fixes that.
Related: https://github.com/DuendeSoftware/IdentityServer/issues/735
=> update session id and description for user interaction in device flow

hosts/AspNetIdentity/Pages/Account/Login/Index.cshtml.cs, hosts/EntityFramework/Pages/Account/Login/Index.cshtml.cs, hosts/main/Pages/Account/Login/Index.cshtml.cs
It was unnecessary to load the *Client* on the login page, as it's already available via the *AuthorizationContext*
Fixes: #715
=> remove client store use from login page

migrations/IdentityServerDb/SeedData.cs, src/Storage/Models/IdentityProvider.cs
It's possible to overwrite the `Properties` dictionary, thus un-setting other properties on the `IdentityProvider` class:
```
new OidcProvider
{
Scheme = "google",
DisplayName = "Google",
Authority = "https://accounts.google.com",
ClientId = "...",
Scope = "openid profile email",
Properties = new Dictionary<string, string>
{
{ "foo", "bar" }
}
}
```
This PR removes the setter to prevent this problem. The updated code from above would now look like this:
```
new OidcProvider
{
Scheme = "google",
DisplayName = "Google",
Authority = "https://accounts.google.com",
ClientId = "...",
Scope = "openid profile email",
Properties = 
{
{ "foo", "bar" }
}
}
```
=> Remove setter from Properties on IdentityProvider

src/EntityFramework.Storage/Stores/ServerSideSessionStore.cs, src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/SessionManagement.cs, src/IdentityServer/Configuration/DependencyInjection/PostConfigureApplicationCookieTicketStore.cs, src/IdentityServer/Hosting/IdentityServerMiddleware.cs, src/IdentityServer/Hosting/ServerSideSessionCleanupHost.cs, src/IdentityServer/Models/UserSession.cs, src/IdentityServer/Services/Default/DefaultSessionManagementService.cs, src/IdentityServer/Services/Default/ServerSideSessionRefreshTokenService.cs, src/IdentityServer/Services/ISessionManagementService.cs, src/IdentityServer/Stores/Default/ServerSideTicketStore.cs, src/IdentityServer/Stores/IServerSideTicketStore.cs, src/IdentityServer/Stores/InMemory/InMemoryServerSideSessionStore.cs, test/IdentityServer.IntegrationTests/Hosting/ServerSideSessionTests.cs, test/IdentityServer.UnitTests/Common/StubSessionCoordinationService.cs
=> minor reorg of session mgmt service/store/model names, add OTel support

src/EntityFramework.Storage/Configuration/ServiceCollectionExtensions.cs, src/EntityFramework.Storage/DbContexts/ConfigurationDbContext.cs, src/EntityFramework.Storage/DbContexts/PersistedGrantDbContext.cs
Given that we have an interface abstraction on our EF DbContexts, it doesn't seem the normal creation was taking place in DI for the `ConfigurationDbContext` or `PersistedGrantDbContext` classes to allow EF's pooling. This PR fixes that, but has the side effect that we can't provide convenience ctors to accept the `OperationalStoreOptions` or `ConfigurationStoreOptions`, so those were also removed.
=> Fix DI registration to actually allow EF DbContext pooling

hosts/EntityFramework/IdentityServerExtensions.cs, hosts/EntityFramework/Pages/ServerSideSessions/Index.cshtml, hosts/EntityFramework/Pages/ServerSideSessions/Index.cshtml.cs, hosts/main/IdentityServerExtensions.cs, hosts/main/Pages/ServerSideSessions/Index.cshtml, hosts/main/Pages/ServerSideSessions/Index.cshtml.cs
UI and sample host updates only.
=> Show info on how to enable server side sessions when disabled

src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/SessionManagement.cs
When using our EF package, the [optional by design] server side session store is always added to DI, even though `AddServerSideSessions` is not called. As long as none of the server-side session coordination features are enabled, then this has no effect. But it's possible that this is added, server-side sessions are not being used, but one of the session coordination features is accidentally enabled, then it could cause unintended side effects for the processing of the client's request.
This PR adds a more defensive check to not allow any of the server side session store logic to be used if `AddServerSideSessions` is not called.
=> add more defensive check for server side session store in DI

src/IdentityServer/Configuration/DependencyInjection/Options/IdentityServerOptions.cs, src/IdentityServer/Endpoints/Results/AuthorizeResult.cs, src/IdentityServer/Extensions/AuthorizeResponseExtensions.cs
Some client libraries cannot process the iss response parameter.
This option allows suppressing the parameter.
=> Introduce option to emit/suppress iss parameter

src/IdentityServer/Endpoints/BackchannelAuthenticationEndpoint.cs, src/IdentityServer/Endpoints/DeviceAuthorizationEndpoint.cs, src/IdentityServer/Endpoints/EndSessionEndpoint.cs, src/IdentityServer/Endpoints/IntrospectionEndpoint.cs, src/IdentityServer/Endpoints/TokenEndpoint.cs, src/IdentityServer/Endpoints/TokenRevocationEndpoint.cs, test/IdentityServer.IntegrationTests/Endpoints/Token/TokenEndpointTests.cs
When an invalid form-url-encoded payload is submitted, IdentityServer throws and returns a 500 status code. It's more appropriate to return a 400 status code.
Fixes: https://github.com/DuendeSoftware/Support/issues/110
=> handle bad form data on token (and other) endpoints

src/IdentityServer/Services/Default/DefaultEventService.cs
The Microsoft provided ISystemClock doesn't capture milliseconds. This PR will use DateTime directly to ensure events have milliseconds in the created/timestamp field.
Context: https://github.com/DuendeSoftware/Support/issues/101#issuecomment-1167779325
A larger effort to rework is considered for the next major release: https://github.com/DuendeSoftware/IdentityServer/issues/949
=> ensure we capture milliseconds of the current DateTime when creating events

src/EntityFramework.Storage/Stores/ServerSideSessionStore.cs, src/IdentityServer/Stores/InMemory/InMemoryServerSideSessionStore.cs, test/IdentityServer.IntegrationTests/Hosting/ServerSideSessionTests.cs
Fixes: https://github.com/DuendeSoftware/Support/issues/94
=> fix incorrect filtering logic in QuerySessionsAsync

src/EntityFramework.Storage/Stores/PersistedGrantStore.cs
At some point the PersistedGrantStore had some refactoring done and some of the methods inadvertently had the virtual modifier removed/omitted. This PR adds them back.
=> add back missing virtuals to PersistedGrantStore

src/IdentityServer/Models/Messages/AuthorizationRequest.cs
Make `AuthorizationRequest` ctor as public to override implementation `IReturnUrlParser`
AuthorizationRequest class contains public constructor without parameters and internal constructor with initialization from validated request parameters. I want to override `OidcReturnUrlParser` to process request URI's without validation for local URL because IS is hosted in AWS kubernetes.
=> Make AuthorizationRequest ctor as public to override implementation IReturnUrlParser

src/IdentityServer/Endpoints/BackchannelAuthenticationEndpoint.cs, src/IdentityServer/Endpoints/DeviceAuthorizationEndpoint.cs, src/IdentityServer/Endpoints/TokenEndpoint.cs, src/IdentityServer/Endpoints/TokenRevocationEndpoint.cs, src/IdentityServer/Validation/Default/ClientSecretValidator.cs, test/IdentityServer.IntegrationTests/Endpoints/DeviceAuthorization/DeviceAuthorizationTests.cs
Fixes: https://github.com/DuendeSoftware/Support/issues/44
=> support invalid_request when client_id is missing in client secret validator

src/IdentityServer/Extensions/ResourceExtensions.cs, src/IdentityServer/Extensions/StringsExtensions.cs, src/IdentityServer/Services/Default/OidcReturnUrlParser.cs, src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs, src/IdentityServer/Validation/Default/DefaultClientConfigurationValidator.cs, test/IdentityServer.UnitTests/Extensions/StringExtensionsTests.cs
Fixes: https://github.com/DuendeSoftware/Support/issues/148
=> fix URI validation to allow query params with encoded values

src/IdentityServer/Configuration/DependencyInjection/Options/LoggingOptions.cs
This PR is adding comments to the properties in `LoggingOptions.cs`, making it clear what they're doing as well as adding a remark to call out the risk of initializing the properties directly as opposed to using `Add(...)` for example
=> Add comments to the LoggingOptions properties

src/EntityFramework.Storage/Stores/ServerSideSessionStore.cs, src/IdentityServer/Stores/Default/ServerSideTicketStore.cs, test/IdentityServer.IntegrationTests/Hosting/ServerSideSessionTests.cs
This PR adds logic to create a new server-side session entry if trying to renew an entry but the DB record has been removed. Done as per guidance from: https://github.com/dotnet/aspnetcore/issues/41516#issuecomment-1178076544
Fixes: https://github.com/DuendeSoftware/Support/issues/161
=> when renewing server-side session, create new entry if current session not found

src/IdentityServer/Validation/Default/License.cs
Mainly just used to show in logging/debugging.
=> Add support for "extras" in license key

src/IdentityServer/Stores/Default/DefaultRefreshTokenStore.cs, src/Storage/Stores/Serialization/PersistentGrantSerializer.cs
Refresh tokens had a format change in v5, and the code to migrate and fixup old records was in the DefaultRefreshTokenStore. But some code, namely the DefaultPersistedGrantService, skips the store and deserializes the payload directly. This was skipping the fixup logic, so this PR moves this fixup logic down into the PersistentGrantSerializer so that both code paths will get the correct behavior.
Fix for: https://github.com/DuendeSoftware/Support/issues/214
=> Fix refresh token data fixup upgrade when using DefaultPersistedGrantService 

src/EntityFramework.Storage/Stores/ServerSideSessionStore.cs
The *ServerSideSessionStore.DeleteSessionAsync* API was using the EF helper *AsNoTracking* on the entity it needed to delete. This prevents the record from being deleted in the database. This is a bug, so the call has been removed.
=> remove unnecessary call to AsNoTracking

.github/workflows/codeql-analysis.yml, build/Program.cs
CodeQL init has a bug - this switches to the latest tooling. Will revert to stable once the fix has landed.
=> Switch to latest CodeQL due to bug

src/IdentityServer/Services/Default/DefaultPersistedGrantService.cs
When refresh tokens are renewed, the old entry in the grants store is marked with a consumed time. This value is used in the refresh token service to decide if an old refresh token is being re-used and if a grace period is allowed. The persisted grant service does not load refresh tokens thru the refresh token service, and instead directly consumes the persisted grant store. This means refresh tokens marked as consumed can still appear as if they are outstanding when a user uses the self-service "Grants" UI page. 
This PR filters the consumed grants from the persisted grant service and thus the self-service "Grants" UI page.
Fixes: #1061
=> filter consumed grants in the persisted grant service

test/IdentityServer.UnitTests/Validation/Secrets/BasicAuthenticationCredentialParsing.cs
Add unit tests for parsing client credentials when client ids include colons. This would happen if your client id was a urn, as is required when using resource indicators.
=> Add unit tests for parsing client credentials when client ids include colons

test/IdentityServer.UnitTests/Services/Default/DefaultRefreshTokenServiceTests.cs
Update the unit tests for refresh token to ensure that CreationTime and Lifetime properties do not change when renewed (TokenUsage.OneTimeOnly).
=> Verify refresh token creation and lifetime in test

src/IdentityServer/Configuration/DependencyInjection/Options/LoggingOptions.cs, src/IdentityServer/Hosting/IdentityServerMiddleware.cs
Allows customers to decide if our catch block around any IdentityServer endpoints will emit a log entry when there is an unhandled exception. The default, and primary use case is to suppress logs when the HTTP connection is cancelled early (e.g. a user navigates away or cancelled the browser request) and EF internally is detecting this and throwing the TaskCancelledException.
Fixes: https://github.com/DuendeSoftware/IdentityServer/issues/1040
=> Introduce filter to allow suppression of unhandled exception logs in IdentityServer middleware

src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/IdentityServerBuilderDynamicSchemesExtensions.cs, src/IdentityServer/Hosting/DynamicProviders/Oidc/IdentityServerBuilderOidcExtensions.cs, src/IdentityServer/Hosting/DynamicProviders/Store/InMemoryIdentityProviderStore.cs, test/IdentityServer.IntegrationTests/Hosting/DynamicProvidersTests.cs
There is really nothing OIDC specific with the InMemoryOidcProviderStore. By changing it to use the IdentityProviders base class, it can be reused for SAML2 providers as well.
=> Make in memory identity providers not OIDC specific

src/IdentityServer/Hosting/DynamicProviders/Configuration/ConfigureAuthenticationContext.cs, src/IdentityServer/Hosting/DynamicProviders/Configuration/ConfigureAuthenticationOptions.cs
Set the base class AuthenticationSchemeOptions as the restriction instead of RemoteAuthenticationOptions for ConfigureAuthenticationOptions.
The code doesn't require any of the functionality of RemoteAuthenticationOptions and it is not a correct assumption that every remote or special scheme would derive from RemoteAuthenticationOptions. It is an opinionated base class that assumes remote authentication is done in specific ways. Using the base AuthenticationSchemeOptions gives more flexibility.
=> Set the base class AuthenticationSchemeOptions as the restriction

src/IdentityServer/Hosting/ServerSideSessionCleanupHost.cs
Log the entire exception, including stack trace, when errors occur in server side session cleanup.
=> Improve error logging in serversidesession cleanup

src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs
In the discovery document, set `authorization_response_iss_parameter_supported` to match the value of `EmitIssuerIdentificationResponseParameter`.
=> EmitIssuerIdentificationResponseParameter is reflected in discovery

clients/src/APIs/ResourceBasedApi/Program.cs, clients/src/APIs/SimpleApi/Program.cs, clients/src/MvcAutomaticTokenManagement/MvcAutomaticTokenManagement.csproj, clients/src/MvcAutomaticTokenManagement/Program.cs, clients/src/MvcAutomaticTokenManagement/Startup.cs, clients/src/MvcCode/Controllers/HomeController.cs, clients/src/MvcCode/Views/Shared/_Layout.cshtml, clients/src/MvcJarJwt/Program.cs, clients/src/MvcJarUriJwt/Program.cs
- Use Duende.AccessTokenManagement in the MvcAutomaticTokenManagement client
- Move the call to UseSerilog in several other clients as well (the extension method on IWebHost is deprecated in favor of one on IHost)
- Fix the logout button in the MvcCode client
=> Samples use duende access token management

src/IdentityServer/Events/UnhandledExceptionEvent.cs
When implementing a custom `EventSink` currently there is no access to the exception that was thrown when the event is of the type `UnhandledExceptionEvent`. The only way to get any information about the exception is to look at the string representation of the exception stored in the `Details` property of `UnhandledExceptionEvent`.
Access to the `Exception` type might be important, especially if the sink forwards the events to a framework / tool that supports exceptions. This is for example the case in certain logging frameworks. At the moment the default sink logs all the events with `_logger.LogInformation("{@event}", evt);`. In case of the `UnhandledExceptionEvent` it would be preferable to log it by providing the exception as separate parameter …
=> add exception to UnhandledExceptionEvent

.editorconfig, clients/src/ConsoleResourceIndicators/Program.cs, src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs, src/IdentityServer/Validation/Default/BackchannelAuthenticationRequestValidator.cs, src/IdentityServer/Validation/Default/DefaultResourceValidator.cs, src/IdentityServer/Validation/Default/TokenRequestValidator.cs, src/IdentityServer/Validation/Models/ResourceValidationRequest.cs, test/IdentityServer.IntegrationTests/Endpoints/Authorize/ResourceTests.cs, test/IdentityServer.IntegrationTests/Endpoints/Token/ResourceTests.cs, test/IdentityServer.UnitTests/Validation/ResourceValidation.cs
When resource indicators were used without offline_access, we had some logic on the authorize endpoint request that was trying to limit or filter the resources in the request. That produced odd "aud" claim results in the access token depending on if the resource requested was isolated or not, and did not allow the request on the token endpoint from actually indicating the resource to use when the code was being exchanged. This PR removes that special casing and allows the resource param on token endpoint to actually control this behavior. 
Related: https://github.com/DuendeSoftware/Support/issues/414
Related: https://github.com/DuendeSoftware/Support/issues/415
=> fix bug with resource indicators and not passing offline_access

src/IdentityServer/Extensions/ValidatedAuthorizeRequestExtensions.cs, test/IdentityServer.UnitTests/Extensions/ValidatedAuthorizeRequestExtensionsTests.cs
This is a redo of the the merge in PR https://github.com/DuendeSoftware/IdentityServer/pull/1118, which accidentally included too many commits into the release branch (and is now reverted).
=> Fixes ToOptimizedRawValues to handle multiple resource values when combined with resource indicators

src/IdentityServer/Services/Default/DefaultSessionCoordinationService.cs, src/IdentityServer/Stores/Default/ServerSideTicketStore.cs
When using server side sessions, if a user's session is re-created (via another call to SignInAsync) and there is an existing session, a new AuthenticationTicket was passed in without the issuer property that we require. This PR detects that condition and now captures the issuer property. This issuer property is needed when performing back channel logout notifications. 
Closes https://github.com/DuendeSoftware/IdentityServer/issues/1138
Related https://github.com/DuendeSoftware/Support/issues/420
=> When cookie is re-issued ensure the issuer is captured in the ticket

src/EntityFramework.Storage/Options/OperationalStoreOptions.cs, src/EntityFramework.Storage/TokenCleanup/TokenCleanupService.cs, src/IdentityServer/Services/Default/DefaultRefreshTokenService.cs, src/Storage/Stores/Serialization/PersistentGrantSerializer.cs, test/EntityFramework.Storage.IntegrationTests/TokenCleanup/TokenCleanupTests.cs, test/IdentityServer.UnitTests/Services/Default/DefaultRefreshTokenServiceTests.cs, test/IdentityServer.UnitTests/Validation/Setup/Factory.cs
This PR adds two new configuration options related to the handling of refresh tokens. The intent of both settings is to alleviate some of the database pressure associated with marking refresh tokens as consumed.
First, `DeleteOneTimeOnlyRefreshTokensOnUse` controls what happens to OneTimeUse tokens when they are used. They can now be either marked as consumed or deleted immediately. The idea here is that, if you aren't making use of the consumed tokens, you can safely delete them immediately. _The default is to immediately delete._
Second, `ConsumedTokenCleanupDelay` delays deletion of consumed tokens in the token cleanup job. The intent of the delay is to allow users to keep tokens for some period of time (perhaps a short delay to allow "lenient" one-time use refresh tokens that can be …
=> Refresh Token Consumption Rework

src/IdentityServer/Validation/Default/PrivateKeyJwtSecretValidator.cs, test/IdentityServer.UnitTests/Validation/Secrets/PrivateKeyJwtSecretValidation.cs
This PR updates the `aud` claim check for private key JWT client authentication based on the CIBA and PAR specs. PAR is not yet implemented, so once it is this will need to be augmented for the new PAR endpoint as well.
Related: https://github.com/DuendeSoftware/IdentityServer/issues/983
=> Update audience logic for private key JWT client authN

hosts/main/DiscoveryHealthCheck.cs, hosts/main/HostingExtensions.cs, src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs, src/IdentityServer/IdentityServerConstants.cs
This PR contains two things:
* bug fix: the JWKS Endpoint in the endpoint collection was using the same name as the discovery endpoint, so the lookup by name results in an ambiguous/non-unique result
* sample to show how to use our public APIs to create a health check for the discovery endpoint
Closes: https://github.com/DuendeSoftware/IdentityServer/issues/584
=> fix non-unique names in endpoint list and add health check sample

src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs
In the past, we only needed the sid claim in the check session endpoint, and only included the sid claim when that endpoint was enabled check session. Now we have more cases where the sid claim is useful, so we are no longer going to make the sid claim conditional on the EnableCheckSessionEndpoint option
=> Always emit the sid claim in id tokens

clients/src/MvcCode/Startup.cs, hosts/main/IdentityServerExtensions.cs, hosts/main/Pages/Account/Create/Index.cshtml, hosts/main/Pages/Account/Create/Index.cshtml.cs, hosts/main/Pages/Account/Create/InputModel.cs, src/IdentityServer/Configuration/DependencyInjection/Options/UserInteractionOptions.cs, src/IdentityServer/Configuration/IdentityServerApplicationBuilderExtensions.cs, src/IdentityServer/Constants.cs, src/IdentityServer/Endpoints/AuthorizeEndpointBase.cs, src/IdentityServer/Endpoints/Results/AuthorizeInteractionPageResult.cs, src/IdentityServer/Endpoints/Results/ConsentPageResult.cs, src/IdentityServer/Endpoints/Results/CreateAccountPageResult.cs, src/IdentityServer/Endpoints/Results/CustomRedirectResult.cs, src/IdentityServer/Endpoints/Results/InteractivePageResult.cs, src/IdentityServer/Endpoints/Results/LoginPageResult.cs, src/IdentityServer/Extensions/ValidatedAuthorizeRequestExtensions.cs, src/IdentityServer/ResponseHandling/Default/AuthorizeInteractionResponseGenerator.cs, src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs, src/IdentityServer/ResponseHandling/Models/InteractionResponse.cs, src/IdentityServer/Test/TestUserStore.cs, src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs, test/IdentityServer.IntegrationTests/Common/IdentityServerPipeline.cs, test/IdentityServer.IntegrationTests/Endpoints/Authorize/AuthorizeTests.cs, test/IdentityServer.IntegrationTests/Endpoints/Discovery/DiscoveryEndpointTests.cs, test/IdentityServer.UnitTests/Endpoints/Authorize/AuthorizeEndpointBaseTests.cs
This PR adds support for the OIDC prompt=create extension:
https://openid.net/specs/openid-connect-prompt-create-1_0.html
Closes: https://github.com/DuendeSoftware/IdentityServer/issues/432
Docs needed: New CreateAccountUrl property on the UserInteractionOptions, and how this affects the values in discovery and request processing.
=> Add support for OIDC prompt=create

src/IdentityServer/Configuration/DependencyInjection/Options/IdentityServerOptions.cs, src/IdentityServer/IdentityServerConstants.cs, src/IdentityServer/IdentityServerTools.cs, src/IdentityServer/Services/Default/DefaultBackChannelLogoutService.cs, src/IdentityServer/Services/Default/DefaultTokenCreationService.cs, test/IdentityServer.IntegrationTests/Endpoints/EndSession/EndSessionTests.cs
This adds a new `LogoutTokenJwtType` option for explicitly configuring back channel logout tokens `typ` header. It defaults to `logout+jwt` to be in compliance with the recently updated and released OIDC back channel logout spec.
https://openid.net/specs/openid-connect-backchannel-1_0.html#LogoutToken
While this might be a breaking change, the current versions of the .NET JWT handler ignore the `typ` so it is a low chance of affecting customers. And if they are validating the `typ` then they should be using the value as per spec. If this does cause issues, then they can set the new `LogoutTokenJwtType` option value introduced in this PR.
Closes: https://github.com/DuendeSoftware/IdentityServer/issues/1169
=> add LogoutTokenJwtType property for back channel logout tokens

src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs, test/IdentityServer.IntegrationTests/Hosting/DynamicProvidersTests.cs
Fixes: https://github.com/DuendeSoftware/IdentityServer/issues/1171
=> requests to ~/federation with no additional segments should return not found

src/IdentityServer/Validation/Default/BasicAuthenticationSecretParser.cs, test/IdentityServer.UnitTests/Validation/Secrets/BasicAuthenticationCredentialParsing.cs
This PR enhances the InputLengthRestrictions checking on the HTTP Basic authorization header and properly validates the client id and secret length checks after URL decoding. 
Closes: https://github.com/DuendeSoftware/IdentityServer/issues/1173
=> enhance InputLengthRestrictions checking on the BasicAuthenticationSecretParser

src/IdentityServer/Validation/Default/TokenRequestValidator.cs
Improves the formatting of some log messages in the validator that previously would look like this:
```
No allowed scopes configured for client{"clientId":
^^^
```
Resolves #1207
=> Add whitespace to logs from TokenRequestValidator

src/IdentityServer/ResponseHandling/Default/TokenResponseGenerator.cs, src/IdentityServer/Validation/Default/TokenRequestValidator.cs
Some follow up work for the DPoP feature:
* more defensive code around validating prior proofs for public clients
* do not force a DB update for legacy refresh tokens that don't have the proof type property
=> small DPoP proof cleanup

src/EntityFramework.Storage/Configuration/ServiceCollectionExtensions.cs, src/EntityFramework.Storage/TokenCleanup/ITokenCleanupService.cs, src/EntityFramework.Storage/TokenCleanup/TokenCleanupService.cs, src/EntityFramework/TokenCleanupHost.cs, test/EntityFramework.Storage.IntegrationTests/TokenCleanup/TokenCleanupTests.cs
- Add ITokenCleanupService interface
- Remove unused IServerSideSessionsMarker from TokenCleanupService
- Rename RemoveExpiredGrantsAsync to CleanupGrantsAsync. This is more accurate, because we are performing all grant cleanup tasks within this method, which might include removing consumed grants and expired device codes in addition to expired grants.
Resolves #981 
The rename is strictly speaking a breaking change, but it a safe one to make because even though this method is public, it is not virtual. The assumption is that the only users of this class are 
- IdentityServer itself, which we change during the rename
- Classes that derive from TokenCleanupService, which can't override this non-virtual method
Removing the IServerSideSessionsMarker is also technically a breaking change, but …
=> Add ITokenCleanupService Interface

src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs
dpop_signing_alg_values_supported should be an [] and not  an [[]]
=> Fix dpop_signing_alg_values_supported

src/IdentityServer/Configuration/DependencyInjection/Options/LoggingOptions.cs
This changes the default TokenRequestSensitiveValuesFilter to include the code parameter. This is for consistency with the parsed value, which is already being obfuscated. Previous logs that included codes are not really a concern, since codes are one time use only - by the time they are logged, they are not likely to be useful anymore.
Closes: #1240
=> Filter authorization codes from token request logs

src/IdentityServer/Configuration/DependencyInjection/PostConfigureApplicationCookieTicketStore.cs, src/IdentityServer/Hosting/DynamicProviders/Configuration/ConfigureAuthenticationOptions.cs, src/IdentityServer/Hosting/DynamicProviders/Oidc/OidcConfigureOptions.cs, src/IdentityServer/Hosting/DynamicProviders/Store/CachingIdentityProviderStore.cs, src/IdentityServer/Hosting/DynamicProviders/Store/NonCachingIdentityProviderStore.cs
When the HttpContext is not available and we would attempt to use it, instead log a debug message explaining what is happening.
Resolves #874
=> Noop instead of trying to use missing HttpContext

src/IdentityServer/Configuration/DependencyInjection/Options/InputLengthRestrictions.cs, src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs, src/IdentityServer/Validation/Default/TokenRequestValidator.cs, test/IdentityServer.IntegrationTests/Endpoints/Token/DPoPTokenEndpointTests.cs
These were overlooked in the first cut implementation.
=> add input length restrictions for dpop

clients/src/APIs/DPoPApi/DPoP/DPoPJwtBearerEvents.cs, clients/src/APIs/DPoPApi/DPoP/DPoPProofValidatonContext.cs, clients/src/APIs/DPoPApi/DPoP/DPoPProofValidatonResult.cs, clients/src/APIs/DPoPApi/DPoP/DPoPProofValidator.cs
This was missing when we copied over the proof token validation logic from what was in IdentityServer itself.
=> Add ath validation in the API for DPoP

clients/src/ConsoleMTLSClient/Program.cs
Minor change to the mtls client to use `ClientCredentialStyle.PostBody`.
=> Fix client credential style in mtls client

src/EntityFramework/Services/CorsPolicyService.cs, test/EntityFramework.Tests/Services/CorsPolicyServiceTests.cs
The CorsPolicyService originally took a dependency on the IServiceProvider because the CorsMiddleware didn't resolve dependencies dynamically. As of .NET 3.0, that is now fixed, so we can remove this dependency.
See https://github.com/dotnet/aspnetcore/issues/2377 for more detail.
Marking this for 7.0 to avoid a breaking change in 6.3.
=> Remove IServiceProvider from CorsPolicyService

src/IdentityServer/Services/Default/DefaultUserSession.cs, test/IdentityServer.UnitTests/Services/Default/DefaultUserSessionTests.cs
Closes: https://github.com/DuendeSoftware/IdentityServer/issues/1352
=> check for IsAuthenticated in addition to Succeeded when calling AuthenticateAsync

src/IdentityServer/Validation/Default/BackchannelAuthenticationRequestValidator.cs
This fixes #1345, which happened because the passed in log message contained a placeholder, and LogWithRequestDetails also added a placeholder for the values, resulting in too many placeholders.
The fix is to remove the extra placeholder from LogWithRequestDetails and review all calls to it to ensure the passed log message always contains placeholders for the values.
=> Fix log messages in backchannel user validator

src/IdentityServer/Endpoints/IntrospectionEndpoint.cs, src/IdentityServer/Events/TokenIntrospectionSuccessEvent.cs, src/IdentityServer/Extensions/DateTimeExtensions.cs, src/IdentityServer/ResponseHandling/Default/IntrospectionResponseGenerator.cs, src/IdentityServer/Validation/Contexts/IntrospectionRequestValidationContext.cs, src/IdentityServer/Validation/Default/IntrospectionRequestValidator.cs, src/IdentityServer/Validation/IIntrospectionRequestValidator.cs, src/IdentityServer/Validation/Models/IntrospectionRequestValidationResult.cs, test/IdentityServer.IntegrationTests/Endpoints/Introspection/IntrospectionTests.cs, test/IdentityServer.IntegrationTests/Endpoints/Introspection/Setup/Clients.cs, test/IdentityServer.UnitTests/Validation/IntrospectionRequestValidatorTests.cs, test/IdentityServer.UnitTests/Validation/Setup/Factory.cs
Closes: https://github.com/DuendeSoftware/IdentityServer/issues/1101
=> add support for introspection for refresh tokens

src/IdentityServer/ResponseHandling/Default/TokenRevocationResponseGenerator.cs, src/IdentityServer/Stores/Default/DefaultGrantStore.cs, src/IdentityServer/Stores/Default/DefaultReferenceTokenStore.cs, src/Storage/Stores/IReferenceTokenStore.cs, test/IdentityServer.IntegrationTests/Endpoints/Revocation/RevocationTests.cs, test/IdentityServer.UnitTests/Common/MockReferenceTokenStore.cs
Fixes: https://github.com/DuendeSoftware/IdentityServer/issues/906
Does add a new param to RemoveReferenceTokensAsync on IReferenceTokenStore, and to the RemoveAllAsync helper on DefaultGrantStore\<T>. I don't expect many customers are overriding these classes/methods, but it's possible.
=> use session id when revoking reference tokens for refresh token

src/IdentityServer/Events/UnhandledExceptionEvent.cs, test/IdentityServer.UnitTests/Events/EventTests.cs
This would fix #1362. Seems a bit heavy-handed to just completely remove the exception, but it can't be serialized anyway so I don't think we're losing much.
=> Remove raw exception from unhandled exception event

src/Configuration/Models/DynamicClientRegistration/DynamicClientRegistrationResponse.cs
Some properties are not included in the request object, but are included in the response. Customizations might want to allow the request to specify those properties, and they can do so in the extensions dictionary. We want to echo back to the user any extension values that they set, but also avoid duplicating values between the elements of the Extensions dictionary and properties on the response model itself.
If a value is added to the extensions that also is a property of the response object, then both values will be serialized. This at best is redundant, and at worst results in conflicting values.
For example, if a customization used
Request.Extensions["client_secret"] to set the Response.ClientSecret, we don't want to copy Request.Extensions["client_secret"] to …
=> DCR - Remove duplicate values from the extensions

clients/src/APIs/DPoPApi/DPoP/DPoPProofValidator.cs, src/IdentityServer/Hosting/LocalApiAuthentication/LocalApiAuthenticationHandler.cs, src/IdentityServer/Hosting/LocalApiAuthentication/LocalApiAuthenticationOptions.cs, src/IdentityServer/Hosting/LocalApiAuthentication/LocalApiTokenMode.cs, src/IdentityServer/Validation/Contexts/DPoPProofValidatonContext.cs, src/IdentityServer/Validation/Default/DefaultDPoPProofValidator.cs, src/IdentityServer/Validation/Default/TokenRequestValidator.cs, src/IdentityServer/Validation/Models/DPoPProofValidatonResult.cs, test/IdentityServer.IntegrationTests/Endpoints/Token/DPoPTokenEndpointTests.cs, test/IdentityServer.IntegrationTests/Hosting/LocalApiAuthentication/LocalApiAuthenticationTests.cs, test/IdentityServer.UnitTests/Validation/DPoPProofValidatorTests.cs, test/IdentityServer.UnitTests/Validation/Setup/Factory.cs
This PR attempts to preserve the existing handler and options and simply layers on the option to use DPoP.
Closes: https://github.com/DuendeSoftware/IdentityServer/issues/1261
=> Add DPoP support to our AddLocalApi access token validation

src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs, src/IdentityServer/Endpoints/Results/AuthorizeInteractionPageResult.cs, src/IdentityServer/Endpoints/Results/AuthorizeResult.cs, src/IdentityServer/Endpoints/Results/BackchannelAuthenticationResult.cs, src/IdentityServer/Endpoints/Results/BadRequestResult.cs, src/IdentityServer/Endpoints/Results/CheckSessionResult.cs, src/IdentityServer/Endpoints/Results/DeviceAuthorizationResult.cs, src/IdentityServer/Endpoints/Results/DiscoveryDocumentResult.cs, src/IdentityServer/Endpoints/Results/EndPointResult.cs, src/IdentityServer/Endpoints/Results/EndSessionCallbackResult.cs, src/IdentityServer/Endpoints/Results/EndSessionResult.cs, src/IdentityServer/Endpoints/Results/IntrospectionResult.cs, src/IdentityServer/Endpoints/Results/JsonWebKeysResult.cs, src/IdentityServer/Endpoints/Results/ProtectedResourceErrorResult.cs, src/IdentityServer/Endpoints/Results/StatusCodeResult.cs, src/IdentityServer/Endpoints/Results/TokenErrorResult.cs, src/IdentityServer/Endpoints/Results/TokenResult.cs, src/IdentityServer/Endpoints/Results/TokenRevocationErrorResult.cs, src/IdentityServer/Endpoints/Results/UserInfoResult.cs, src/IdentityServer/Hosting/IEndpointResult.cs, src/IdentityServer/Hosting/IEndpointResultGenerator.cs, test/IdentityServer.UnitTests/Endpoints/EndSession/EndSessionCallbackResultTests.cs, test/IdentityServer.UnitTests/Endpoints/Results/AuthorizeResultTests.cs, test/IdentityServer.UnitTests/Endpoints/Results/CheckSessionResultTests.cs, test/IdentityServer.UnitTests/Endpoints/Results/EndSessionCallbackResultTests.cs, test/IdentityServer.UnitTests/Endpoints/Results/EndSessionResultTests.cs
This PR introduces the `IEndpointResultGenerator<T>` type which is designed to render the `IEndpointResult` objects that are returned from the `IEndpointHandler` in our endpoint routing architecture.
Previously the `IEndpointResult` would render themselves, but was difficult for customers to override or change how they did this. Now our built in `IEndpointResult` classes use a new base class `EndpointResult` which will resolve a `IEndpointResultGenerator<T>` from DI to do the rendering. This allows customers to register their own `IEndpointResultGenerator<T>` and can change how they are rendered to the HTTP response.
This PR is also designed to be backwards compatible with the prior approach, such that any custom `IEndpointResult` or `IEndpointHandler` should still work the way they used …
=> Support response generators for the endpoint results

src/IdentityServer/Hosting/CorsPolicyProvider.cs
The previous wording looks like thee is an error. If this shows up in the log when troubleshooting, people starts looking at Cors even though it's probably something else
=> Improve Cors logging message.

src/AspNetIdentity/IdentityServerBuilderExtensions.cs, src/AspNetIdentity/PostConfigureIdentityServerOptions.cs, src/IdentityServer/Configuration/DependencyInjection/Options/DynamicProviderOptions.cs
**Redirecting back to client application after logging out from the external identity provider**
User is not redirected back to the client application from external identity provider, when identity server is configured for asp.net identity.
[Link to the Issue](https://github.com/DuendeSoftware/IdentityServer/issues/1404)
After some debugging of the duende and Microsoft sources, I've discovered that the reason for the redirection problem is the absence of id token. SignOutScheme which is used to retrieve id token from the user is set to default value, but default authentication scheme after configuring identity server for asp.net identity is changed to Application.Identity.
=> Add post configuration of identity server options

Directory.Build.targets, test/EntityFramework.Storage.IntegrationTests/Stores/DeviceFlowStoreTests.cs, test/IdentityServer.IntegrationTests/Endpoints/Authorize/AuthorizeTests.cs, test/IdentityServer.IntegrationTests/TestFramework/GenericHost.cs, test/IdentityServer.IntegrationTests/TestFramework/TestBrowserClient.cs, test/IdentityServer.UnitTests/Extensions/IResourceStoreExtensionsTests.cs, test/IdentityServer.UnitTests/ResponseHandling/AuthorizeInteractionResponseGenerator/AuthorizeInteractionResponseGeneratorTests_Consent.cs, test/IdentityServer.UnitTests/ResponseHandling/DeviceAuthorizationResponseGeneratorTests.cs, test/IdentityServer.UnitTests/ResponseHandling/UserInfoResponseGeneratorTests.cs, test/IdentityServer.UnitTests/Services/Default/DefaultBackchannelAuthenticationInteractionServiceTests.cs, test/IdentityServer.UnitTests/Services/Default/DefaultIdentityServerInteractionServiceTests.cs, test/IdentityServer.UnitTests/Services/Default/DistributedDeviceFlowThrottlingServiceTests.cs, test/IdentityServer.UnitTests/Validation/AuthorizeRequest Validation/Authorize_ProtocolValidation_Invalid.cs, test/IdentityServer.UnitTests/Validation/DeviceAuthorizationRequestValidation.cs, test/IdentityServer.UnitTests/Validation/Secrets/MutualTlsSecretValidation.cs, test/IdentityServer.UnitTests/Validation/TokenRequest Validation/TokenRequestValidation_General_Invalid.cs
Upgrading FluentAssertions is needed to add FluentAssertions.Web, which I'd like to start using.
Breaking changes that impacted us:
- Async code that throws must now await ThrowAsync
- Enums must now be used in a type safe manner
- Dates are compared with a mandatory precision
=> Upgrade FluentAssertions from 5.10.1 to 6.5.1

src/IdentityServer/Events/UnhandledExceptionEvent.cs, test/IdentityServer.UnitTests/Events/EventTests.cs
This backports #1363 into the 6.3 release.
The issue is that thrown exceptions can't be serialized by System.Text.Json, because they contain pointers that it won't allow. 
This fix (suppressing serialization) is specific to the 6.3 release, to avoid a breaking change to the event type.
In 7.0, we will remove the property entirely.
=> Joe/6.3 bugfix/error event serialization

Directory.Build.targets
This reverts commit 18d53869141a650e91b76beefa6232959aca75a9.
Keeps dependencies as permissive as possible to avoid dependency issues.
=> Revert "Bump WilsonVersion from 7.0.0 to 7.0.1"

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, Directory.Build.targets, global.json, src/IdentityServer/Endpoints/PushedAuthorizationEndpoint.cs, src/IdentityServer/Services/Default/PushedAuthorizationService.cs, src/IdentityServer/Services/DeserializedPushedAuthorizationRequest.cs, src/IdentityServer/Validation/Default/RequestObjectValidator.cs, src/IdentityServer/Validation/Models/JwtRequestValidationResult.cs, test/EntityFramework.Storage.IntegrationTests/Stores/ClientStoreTests.cs, test/EntityFramework.Tests/Services/CorsPolicyServiceTests.cs, test/IdentityServer.UnitTests/Extensions/IdentityServerBuilderExtensionsCryptoTests.cs, test/IdentityServer.UnitTests/Services/Default/DefaultCorsPolicyServiceTests.cs, test/IdentityServer.UnitTests/Services/InMemory/InMemoryCorsPolicyService.cs, test/IdentityServer.UnitTests/Validation/AuthorizeRequest Validation/Authorize_ProtocolValidation_PAR.cs
..new warnings and new failed tests around JWTs... could you please have a look @josephdecock
=> Update to .NET RC.2

clients/src/MvcCode/Startup.cs, hosts/Config/ClientsWeb.cs, hosts/Configuration/Pages/TestUsers.cs, hosts/EntityFramework/Pages/TestUsers.cs, hosts/main/Pages/TestUsers.cs, test/IdentityServer.UnitTests/ResponseHandling/UserInfoResponseGeneratorTests.cs
=> Use strings for postal codes in test users

src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Additional.cs, src/IdentityServer/Endpoints/Results/AuthorizeInteractionPageResult.cs, src/IdentityServer/Extensions/ValidatedAuthorizeRequestExtensions.cs, test/IdentityServer.UnitTests/Extensions/ValidatedAuthorizeRequestExtensionsTests.cs
PAR is a more robust/standardized approach to get similar benefits
This PR obsoletes the extension method that registers the default `IAuthorizationParametersMessageStore` as well as the `ToOptimizedFullDictionary` method, which is only used when that store is used. There are more types that could in theory be obsoleted - notably the `IAuthorizationParametersMessageStore` itself, but that gets used in many places, and would add quite a bit of clutter.
This closes #1444
=> Discourage IAuthorizationParametersMessageStore

src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs, test/IdentityServer.IntegrationTests/Conformance/Basic/ResponseTypeResponseModeTests.cs, test/IdentityServer.UnitTests/Validation/AuthorizeRequest Validation/Authorize_ProtocolValidation_Invalid.cs
If you agree on https://github.com/DuendeSoftware/Support/issues/907.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate and …
=> Return invalid_request when no response_type is provided

src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs, src/IdentityServer/Extensions/IdentityServerToolsExtensions.cs, src/IdentityServer/IdentityServerTools.cs, src/IdentityServer/Services/Default/DefaultBackChannelLogoutService.cs, test/IdentityServer.IntegrationTests/Endpoints/Ciba/CibaTests.cs
`IdentityServerTools` is useful and I expect used in a lot of places. However as it's a concrete class it is difficult to test services that depend on it. This PR creates an abstraction `IIdentityServerTools` which can be injected instead, and can therefore be mocked easily for tests. This is important for testing services that depend upon `IdentityServerTools` but don't explicitly need it for testing purposes.
**Note:** This would be a breaking change. Personally I think that's ok, but if you wanted to maintain backward compatibility, we could keep both registrations:
```csharp
builder.Services.AddTransient<IIdentityServerTools, IdentityServerTools>();
builder.Services.AddTransient<IdentityServerTools>();
```
**Important: Any code or remarks in your …
=> Provide abstraction for IdentityServerTools

src/IdentityServer/IdentityServerTools.cs, src/IdentityServer/Services/Default/DefaultBackChannelLogoutService.cs, test/IdentityServer.UnitTests/Services/Default/DefaultBackChannelLogoutServiceTests.cs
=> Fix logout token iss when issuer is missing

src/IdentityServer/Stores/Default/DefaultGrantStore.cs, src/IdentityServer/Stores/Default/DefaultUserConsentStore.cs, test/IdentityServer.IntegrationTests/Endpoints/Authorize/ConsentTests.cs
=> Hex encode consent keys

src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs, src/IdentityServer/IdentityServerTools.cs, test/IdentityServer.UnitTests/Services/Default/DefaultBackChannelLogoutServiceTests.cs
`[Obsolete]` was added to the `IdentityServerTools` class when we introduced the `IIdentityServerTools` interface. This was added to try to alert users that they may need to change their DI registrations.
Users can customize `IdentityServerTools` today by deriving from the class, and then registering the custom version like this:
```cs
builder.Services.AddTransient<IdentityServerTools, CustomIdentityServerTools>
```
Pre-v7, this works because our code depends on an `IdentityServerTools`, which resolves to `CustomIdentityServerTools`. In v7, this fails because our code depends on an `IIdentityerServerTools`, which resolves to `IdentityServerTools`.
Users need to change to 
```cs
builder.Services.AddTransient<IIdentityerServerTools, CustomIdentityServerTools>
```
Marking …
=> Remove [Obsolete] from IdentityServerTools

src/EntityFramework.Storage/Options/OperationalStoreOptions.cs, src/IdentityServer/Services/Default/DefaultIssuerNameService.cs, src/Storage/Models/Client.cs
- Enable refresh token reuse by default
- ~Enable the token cleanup job by default~
- ~Remove consumed tokens in the cleanup job by default~
Closes #1128
=> Change some token option defaults

src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Additional.cs, src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs, src/IdentityServer/Endpoints/Results/BackchannelAuthenticationResult.cs, src/IdentityServer/Models/BackchannelUserLoginRequest.cs, src/IdentityServer/ResponseHandling/Default/BackchannelAuthenticationResponseGenerator.cs, src/IdentityServer/ResponseHandling/Models/BackchannelAuthenticationResponse.cs, src/IdentityServer/Services/Default/DefaultBackchannelAuthenticationInteractionService.cs, src/IdentityServer/Validation/Contexts/CustomBackchannelAuthenticationRequestValidationContext.cs, src/IdentityServer/Validation/Default/BackchannelAuthenticationRequestValidator.cs, src/IdentityServer/Validation/Default/DefaultCustomBackchannelAuthenticationValidator.cs, src/IdentityServer/Validation/ICustomBackchannelAuthenticationValidator.cs, src/IdentityServer/Validation/Models/ValidatedBackchannelAuthenticationRequest.cs, src/Storage/Models/BackChannelAuthenticationRequest.cs, test/IdentityServer.IntegrationTests/Common/MockCustomBackchannelAuthenticationValidator.cs, test/IdentityServer.IntegrationTests/Endpoints/Ciba/CibaTests.cs
This adds extensibility points to CIBA to allow for custom request and response parameters.
- Adds a new custom backchannel authentication request validator hook, similar to `AddCustomAuthorizeRequestValidator` and `AddCustomTokenRequestValidator`
- Adds a context dictionary to the ciba validation result, which then feeds into similar context dictionaries in the response to the client, notification to the user, and record in the database
=> CIBA Customization Extensibility Points

src/IdentityServer/Configuration/DependencyInjection/Options/LoggingOptions.cs
Treat the Subject Token as sensitive because it could be an access token or an identity token that contains PII.
See https://github.com/DuendeSoftware/IdentityServer/issues/1522
=> Filter subject token from TokenRequest log

clients/src/ConsolePrivateKeyJwtClient/Program.cs, hosts/Config/ClientsConsole.cs
A small addition to the Private Key JWT test client that adds an EC DSA jwk.
=> Expand private key jwt test client with an ECDSA key

src/IdentityServer/Licensing/IdentityServerLicenseValidator.cs, src/IdentityServer/Licensing/LicenseValidator.cs, test/IdentityServer.UnitTests/Licensing/IdentityServerLicenseValidatorTests.cs
- ConcurrentDictionary has excellent concurrency performance for reading/writing invidivual key/values. But the locking pattern for reading the count and getting all keys is quite bad.
- Add tests
- Fixes #1526
=> Rework license validator to not use ConcurrentDictionary

src/IdentityServer/Services/Default/KeyManagement/X509KeyContainer.cs
=> Exception type is updated from .NET 7 and up

Directory.Build.targets
Most of the packages are listed with a security vulernability that is only fixed in 1.8.1, so all them are bumped to that version. Except those packages that do not have a 1.8.1 released
=> Bump OpenTelemetry dependencies

src/IdentityServer/Services/Default/DefaultEventService.cs, test/IdentityServer.UnitTests/Common/MockEventSink.cs, test/IdentityServer.UnitTests/Common/NullHttpContextAccessor.cs, test/IdentityServer.UnitTests/Services/Default/DefaultEventServiceTests.cs
Fixes https://github.com/DuendeSoftware/Support/issues/614, which seems to have reappeared for events.
=> Fix null reference exception in event service when httpcontext missing

Directory.Build.targets
Update Otel dependencies for 7.0. These are only used by the hosts so simply bumping to latest version.
=> Update OTel dependencies for 7.0

src/IdentityServer/Constants.cs, src/IdentityServer/Extensions/ValidatedAuthorizeRequestExtensions.cs, src/IdentityServer/ResponseHandling/Default/AuthorizeInteractionResponseGenerator.cs, src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs, test/IdentityServer.IntegrationTests/Endpoints/Authorize/AuthorizeTests.cs
This replaces https://github.com/DuendeSoftware/IdentityServer/pull/1544, but now with automated tests and in the 7.0 release branch.
Closes #1545
=> Prevent infinite loop when max_age=0

src/IdentityServer/Endpoints/Results/AuthorizeInteractionPageResult.cs, src/IdentityServer/Validation/Default/RequestObjectValidator.cs, test/IdentityServer.IntegrationTests/Common/IdentityServerPipeline.cs, test/IdentityServer.IntegrationTests/Endpoints/Authorize/PushedAuthorizationTests.cs
Fixes #1562, which is a bug where the prompt (or max_age=0) parameter could not be used with PAR because we weren't respecting the processed flag.
=> PAR - support processed params in authorize endpoint

Directory.Build.targets
Update framework dependencies to avoid taking a transitive dependency on a vulnerable version of System.IdentityModel.Tokens.Jwt. Even though we specify wilson version, we aren't explicitly using the wilson version in most of the nuget packages we produce.
=> Update ASP.NET core depedencies

Directory.Build.targets, hosts/AspNetIdentity/Host.AspNetIdentity.csproj, hosts/Configuration/Host.Configuration.csproj, hosts/EntityFramework/Host.EntityFramework.csproj, hosts/EntityFramework/Pages/Admin/Clients/ClientRepository.cs, hosts/EntityFramework/Pages/Admin/Clients/Edit.cshtml.cs, migrations/IdentityServerDb/IdentityServerDb.csproj, test/Configuration.IntegrationTests/Configuration.IntegrationTests.csproj, test/EntityFramework.IntegrationTests/EntityFramework.IntegrationTests.csproj, test/EntityFramework.Storage.IntegrationTests/EntityFramework.Storage.IntegrationTests.csproj, test/EntityFramework.Storage.UnitTests/EntityFramework.Storage.UnitTests.csproj, test/IdentityServer.IntegrationTests/IdentityServer.IntegrationTests.csproj, test/IdentityServer.IntegrationTests/TestFramework/TestBrowserClient.cs, test/IdentityServer.UnitTests/Validation/IsLocalUrlTests.cs, test/IdentityServer.UnitTests/Validation/Secrets/BasicAuthenticationCredentialParsing.cs, test/IdentityServer.UnitTests/Validation/Secrets/ClientAssertionSecretParsing.cs, test/IdentityServer.UnitTests/Validation/Secrets/FormPostCredentialParsing.cs
This PR prepares the repo for .net 9.
_Note that this only affects our development hosts and test projects, not any published package's dependency. All our current packages have no transitive security vulnerabilities as of now._
- Update Serilog to 8.0.2. This pulls in the right version of System.Text.Json in most cases.
- Pin versions of Azure.Identity (1.11.4), System.Formats.Asn1 (8.0.1), Microsoft.Data.SqlClient (5.1.6) and System.Text.Json. These are depended on by EF and Sql client packages, and there's no update to those packages available that wouldn't give us a vulnerable version. Hopefully someday those packages will update such that this is no longer needed.
- Rename ClientModel. The new System.ClientModel library is a new dependency that we get from updating Azure.Identity, …
=> Build updates in preparation for .net 9

src/IdentityServer/Configuration/DependencyInjection/Options/UserInteractionOptions.cs, test/IdentityServer.IntegrationTests/Endpoints/Authorize/AuthorizeTests.cs
=> Allow SupportedPromptModes customization

hosts/Configuration/Pages/TestUsers.cs, hosts/EntityFramework/Pages/TestUsers.cs, hosts/main/Pages/TestUsers.cs, migrations/AspNetIdentityDb/SeedData.cs, test/IdentityServer.IntegrationTests/Clients/Setup/Users.cs, test/IdentityServer.IntegrationTests/Clients/UserInfoClient.cs
Replace alice.com with alice.example.com, bob.com with bob.example.com, and email.com with example.com
Fixes #1419 (https://github.com/DuendeSoftware/Support/issues/1419)
=> Replace alice/bob/email.com domains with example domains

src/IdentityServer/Services/Default/DefaultUserSession.cs, test/IdentityServer.UnitTests/Services/Default/DefaultUserSessionTests.cs
Reuse already existing check in the [AuthenticationPropertiesExtensions.AddClientId](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Extensions/AuthenticationPropertiesExtensions.cs#L101) method.
=> Avoid multiple check adding clientid

src/IdentityServer/Validation/Default/IntrospectionRequestValidator.cs, test/IdentityServer.IntegrationTests/Endpoints/Introspection/IntrospectionTests.cs
When the token type hint parameter is incorrect, we now fall back and try the other type of token (either refresh or access). But, we only do this for clients - apis cannot use refresh tokens, so they still get a response of { "isActive": false } if they attempt to introspect a refresh token. In either case, bogus token_type_hints are not an error anymore, either.
For reference, RFC 7662 Section 2.1:
> If the server is unable to locate the token using the given hint, it MUST extend its search across all of its supported token types.
Resolves #1578
=> Fall back to other token types when given incorrect hint

src/IdentityServer/Configuration/CryptoHelper.cs, src/IdentityServer/Extensions/HashExtensions.cs, src/IdentityServer/Extensions/ValidatedAuthorizeRequestExtensions.cs, src/IdentityServer/Models/Messages/ConsentRequest.cs, src/IdentityServer/Stores/Default/DefaultGrantStore.cs, src/IdentityServer/Validation/Default/DefaultDPoPProofValidator.cs
I rebased @martincostello's PR (#1573) onto main because we need the latest package updates to build. 
The original PR replaces the SHA256.Create() (and other SHA HashAlgorithm) calls with SHA*.HashData, which uses less memory by not allocating a SHA* object. It had left in place one public function that would actually return the SHA* object. We weren't using that anymore but it was public.
I deprecated that function, and added a new function that returns the appropriate SHA*.HashData function instead.
=> Recreating martincostello's PR (#1573), rebased onto main

src/Configuration.EntityFramework/ClientConfigurationStore.cs, src/EntityFramework.Storage/Interfaces/IConfigurationDbContext.cs, test/Configuration.IntegrationTests/TestHosts/ConfigurationHost.cs
Fixes #1616
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate and use your Feedback for any purpose, including to make and …
=> ClientConfigurationStore now uses IConfigurationDbContext

hosts/AspNetIdentity/Pages/Extensions.cs, hosts/Configuration/Extensions/SameSiteHandlingExtensions.cs, hosts/Configuration/Pages/Extensions.cs, hosts/EntityFramework/Pages/Extensions.cs, hosts/main/Extensions/SameSiteHandlingExtensions.cs, hosts/main/Pages/Extensions.cs, src/IdentityServer/Extensions/HttpRequestExtensions.cs, src/IdentityServer/Extensions/HttpResponseExtensions.cs, src/IdentityServer/Hosting/LocalApiAuthentication/LocalApiAuthenticationHandler.cs, src/IdentityServer/Validation/Default/BasicAuthenticationSecretParser.cs, src/IdentityServer/Validation/Default/BearerTokenUsageValidator.cs, test/IdentityServer.UnitTests/Endpoints/EndSession/EndSessionCallbackResultTests.cs, test/IdentityServer.UnitTests/Endpoints/Results/AuthorizeResultTests.cs, test/IdentityServer.UnitTests/Endpoints/Results/CheckSessionResultTests.cs, test/IdentityServer.UnitTests/Endpoints/Results/EndSessionCallbackResultTests.cs, test/IdentityServer.UnitTests/Endpoints/Results/EndSessionResultTests.cs
=> use named headers

src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs
- use [MaxBy](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.maxby) method instead of [OrderByDescending ](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.orderbydescending) and [First](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.first) methods.
- use [MinBy](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.minby) method instead of [OrderBy](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.orderby) and [First](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.first) methods.
```
record KeyContainer(DateTime Created);
[SimpleJob(RuntimeMoniker.Net80)]
[MemoryDiagnoser]
public class Benchmark
{
private IEnumerable<KeyContainer> keys =
[
new KeyContainer(DateTime.Now),
new …
```
=> improve youngest key search

src/IdentityServer/Extensions/HttpContextExtensions.cs, src/IdentityServer/Services/Default/DefaultPersistedGrantService.cs
[Enumerable.Union](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.union?view=net-8.0#system-linq-enumerable-union-1(system-collections-generic-ienumerable((-0))-system-collections-generic-ienumerable((-0)))) method already excludes duplicates.
> Returns
An [IEnumerable<T>](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.ienumerable-1?view=net-8.0) that contains the elements from both input sequences, excluding duplicates.
---
```
IEnumerable<string> first = ["a", "b"];
IEnumerable<string> second = ["a", "c"];
var union = first.Union(second); // => [a, b, c]
var unionDistinct = first.Union(second).Distinct(); // => [a, b, c]
Debug.Assert(union.SequenceEqual(unionDistinct));
```
---
Some performance improvement:
``` …
```
=> remove unnecessary distinct method

src/IdentityServer/Test/TestUserStore.cs
`user.Password` could be null.
=> use static equals method to avoid exception

src/IdentityServer/Extensions/AuthenticationPropertiesExtensions.cs
Use [Append](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.append) method instead of [ToList](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.tolist) and [Add](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.add) methods.
```
[SimpleJob(RuntimeMoniker.Net80)]
[MemoryDiagnoser]
public class Benchmark
{
private string clientId = "1";
[Benchmark]
public void ToList_Add()
{
IEnumerable<string> clients = [];
var update = clients.ToList();
update.Add(clientId);
}
[Benchmark]
public void Append()
{
IEnumerable<string> clients = [];
clients.Append(clientId);
}
}
void Main() => BenchmarkRunner.Run<Benchmark>();
```
```
// * Summary *
BenchmarkDotNet v0.14.0, Windows 10 (10.0.19045.4780/22H2/2022Update)
Intel Core i7-10700 CPU …
```
=> Refactoring AuthenticationPropertiesExtensions

src/IdentityServer/Validation/Default/TokenValidator.cs, test/IdentityServer.UnitTests/Validation/IntrospectionRequestValidatorTests.cs
=> Filter protocol claims from reference tokens

src/IdentityServer/Endpoints/Results/ProtectedResourceErrorResult.cs
This is a double alloc. since the previous code was converting a StringValues to a string. then internal to Headers.Append it will then wrap that string in a StringValues
=> remove redundant allocation in ProtectedResourceErrorResult

src/EntityFramework.Storage/Stores/SigningKeyStore.cs
Since StoreKeyAsync was elided. the cost of SaveChangesAsync would occur after the dispose of `activity` resulting in an inaccurate timing
=> more accurate timing to SigningKeyStore.StoreKey activity in StoreKeyAsync

hosts/EntityFramework/Pages/Account/Login/Index.cshtml.cs, src/Storage/Extensions/ClaimsPrincipalLiteExtensions.cs, src/Storage/Stores/Serialization/ClaimLite.cs, test/IdentityServer.IntegrationTests/Hosting/ServerSideSessionTests.cs
Resolves #1546
@AndersAbel this came up in context of a support issue you worked where someone couldn't logout using saml and sustainsys, so I've added you as a reviewer if you have time - is this what you were hoping for?
=> Persist claim issuers in server side sessions

src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs, test/IdentityServer.UnitTests/Services/Default/KeyManagement/KeyManagerTests.cs, test/IdentityServer.UnitTests/Services/Default/KeyManagement/MockSigningKeyProtector.cs
Retired signing keys will now be deleted by the key manager even if they are data protected and cannot be unprotected.
Resolves #1572
=> Delete retired keys even if they are un-unprotectable 

src/IdentityServer/Configuration/DependencyInjection/Options/LoggingOptions.cs, test/IdentityServer.IntegrationTests/Hosting/IdentityServerMiddlewareTests..cs
When an http request is canceled, we'll get some sort of cancellation related exception. There are reports that this sometimes is raised as OperationCanceled instead of TaskCanceled, and since OperationCanceled is the base class, it is simpler to filter that instead.
Closes #1587 
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to …
=> Filter OperationCanceled instead of TaskCanceled logs

src/IdentityServer/Licensing/V2/ProtocolRequestCounter.cs, test/IdentityServer.IntegrationTests/Hosting/LicenseTests.cs, test/IdentityServer.UnitTests/Licensing/v2/ProtocolRequestCounterTests.cs
=> Update trial mode warning language

.github/workflows/ci.yml
I'm about to bulk rename tags, and don't want that to kick off dozens of builds.
=> Disable tag builds (temporary)

src/IdentityServer/Configuration/DependencyInjection/PostConfigureApplicationCookieTicketStore.cs, test/IdentityServer.UnitTests/Common/MockHttpContextAccessor.cs, test/IdentityServer.UnitTests/Configuration/DependencyInjection/PostConfigureApplicationCookieTicketStoreTests.cs
Fix service resolution in PostConfigureApplicationCookieTicketStore so that it can be constructed without an http context available.
Fixes #1689
=> fix(is): service resolution from HttpContext

bff/test/Duende.Bff.EntityFramework.Tests/Duende.Bff.EntityFramework.Tests.csproj, bff/test/Duende.Bff.EntityFramework.Tests/UserSessionStoreTests.cs, bff/test/Duende.Bff.Tests/Duende.Bff.Tests.csproj, bff/test/Duende.Bff.Tests/Endpoints/LocalEndpointTests.cs, bff/test/Duende.Bff.Tests/Endpoints/Management/BackchannelLogoutEndpointTests.cs, bff/test/Duende.Bff.Tests/Endpoints/Management/LoginEndpointTests.cs, bff/test/Duende.Bff.Tests/Endpoints/Management/LogoutEndpointTests.cs, bff/test/Duende.Bff.Tests/Endpoints/Management/ManagementBasePathTests.cs, bff/test/Duende.Bff.Tests/Endpoints/Management/UserEndpointTests.cs, bff/test/Duende.Bff.Tests/Endpoints/RemoteEndpointTests.cs, bff/test/Duende.Bff.Tests/Endpoints/YarpRemoteEndpointTests.cs, bff/test/Duende.Bff.Tests/GenericHostTests.cs, bff/test/Duende.Bff.Tests/Headers/ApiAndBffUseForwardedHeaders.cs, bff/test/Duende.Bff.Tests/Headers/ApiUseForwardedHeaders.cs, bff/test/Duende.Bff.Tests/Headers/General.cs, bff/test/Duende.Bff.Tests/SessionManagement/CookieSlidingTests.cs, bff/test/Duende.Bff.Tests/SessionManagement/RevokeRefreshTokenTests.cs, bff/test/Duende.Bff.Tests/SessionManagement/ServerSideTicketStoreTests.cs, bff/test/Duende.Bff.Tests/TestFramework/GenericHost.cs, bff/test/Duende.Bff.Tests/TestHosts/BffHost.cs, bff/test/Duende.Bff.Tests/TestHosts/BffHostUsingResourceNamedTokens.cs, bff/test/Duende.Bff.Tests/TestHosts/YarpBffHost.cs
This PR removes FluentAssertions from the BFF security framework in favor of using Shouldly. This makes the unit testing experience consistent with our other products.
=> phase out fluent assertions in favor of shouldly

hosts/main/Program.cs
Fixed usage in the main host of the LicenseUsageSummary so that it is resolved at shutdown properly.
=> fix(is): LicenseUsageSummary resolution

.github/workflows/ci.yml
Config to facilitate IdentityServer releases pre-move to mono-repo.
=> ci(is): add 7.1 workflow dispatch

.github/workflows/identity-server-ci.yml
Add workflow dispatch to allow for manually triggering builds (needed for IdSrv 7.1, etc).
=> ci(is): Add workflow dispatch to build config

identity-server/src/IdentityServer/Configuration/DependencyInjection/PostConfigureApplicationCookieTicketStore.cs, identity-server/src/IdentityServer/Hosting/DynamicProviders/Store/CachingIdentityProviderStore.cs
Fixes two potential NullReferenceExceptions by being a bit more defensive
=> Fix two potential NREs

identity-server/src/IdentityServer/Endpoints/Results/AuthorizeResult.cs
This PR adjusts the fragment that is added to error redirect responses, which is supposed to prevent browsers from reattaching existing ones.
The previous fragment `#_=_` is an invalid query selector and can not be used as is on the receiving end, hence it has been adjusted to the recommended `#_`.
Additionally, I adjusted the link to the respective latest active internet draft.
This looks like a minor thing, but one can run into issues caused by the browsers behavior of carrying along fragments.
=> fix(error-redirect): use query-safe fragment as recommended in the latest OAuth 2 security best practices

identity-server/src/EntityFramework/TokenCleanupHost.cs, identity-server/src/IdentityServer/Hosting/ServerSideSessionCleanupHost.cs
Changes background services from to use `AsyncServiceScope` to support services which implement `IAsyncDisposable`.
It is worth noting we do have one other spot we create a scope. However, the other instance of creating a scope is in code called during startup and is not currently asynchronous. Updating that feels like a breaking change and has been kept out of scope for these changes.
=> Use AsyncServiceScope in Background Services

identity-server/src/Storage/Models/IdentityProvider.cs
I assume empty and whitespace is invalid for type?
=> ThrowIfNullOrWhiteSpace for type in IdentityProvider

bff/test/Duende.Bff.Tests/Endpoints/LocalEndpointTests.cs, bff/test/Duende.Bff.Tests/Endpoints/Management/BackchannelLogoutEndpointTests.cs, bff/test/Duende.Bff.Tests/Endpoints/Management/LoginEndpointTests.cs, bff/test/Duende.Bff.Tests/Endpoints/Management/LogoutEndpointTests.cs, bff/test/Duende.Bff.Tests/Endpoints/Management/ManagementBasePathTests.cs, bff/test/Duende.Bff.Tests/Endpoints/Management/UserEndpointTests.cs, bff/test/Duende.Bff.Tests/Endpoints/RemoteEndpointTests.cs, bff/test/Duende.Bff.Tests/Endpoints/YarpRemoteEndpointTests.cs, bff/test/Duende.Bff.Tests/GenericHostTests.cs, bff/test/Duende.Bff.Tests/Headers/ApiAndBffUseForwardedHeaders.cs, bff/test/Duende.Bff.Tests/Headers/ApiUseForwardedHeaders.cs, bff/test/Duende.Bff.Tests/Headers/General.cs, bff/test/Duende.Bff.Tests/SessionManagement/CookieSlidingTests.cs, bff/test/Duende.Bff.Tests/SessionManagement/RevokeRefreshTokenTests.cs, bff/test/Duende.Bff.Tests/SessionManagement/ServerSideTicketStoreTests.cs, bff/test/Duende.Bff.Tests/TestFramework/GenericHost.cs, bff/test/Duende.Bff.Tests/TestFramework/TestLoggerProvider.cs, bff/test/Duende.Bff.Tests/TestHosts/ApiHost.cs, bff/test/Duende.Bff.Tests/TestHosts/BffHost.cs, bff/test/Duende.Bff.Tests/TestHosts/BffHostUsingResourceNamedTokens.cs, bff/test/Duende.Bff.Tests/TestHosts/BffIntegrationTestBase.cs, bff/test/Duende.Bff.Tests/TestHosts/IdentityServerHost.cs, bff/test/Duende.Bff.Tests/TestHosts/YarpBffHost.cs, bff/test/Duende.Bff.Tests/TestHosts/YarpBffIntegrationTestBase.cs
This PR ensures that all tests now write the HTTP logs to the output.
=> tests write output via ITestOutputHelper

bff/src/Duende.Bff/EndpointProcessing/IBffUIApiEndpoint.cs
Cleaned up the license header by removing unnecessary comment delimiters. This improves readability and maintains consistency with standard file header formatting conventions.
=> Remove redundant comment delimiters in license header

identity-server/hosts/Configuration/Pages/Account/Login/Index.cshtml.cs, identity-server/hosts/EntityFramework/Pages/Account/Login/Index.cshtml.cs, identity-server/hosts/main/Pages/Account/Login/Index.cshtml.cs, identity-server/src/Configuration/Licensing/LicenseValidator.cs, identity-server/src/IdentityServer/Extensions/ValidatedAuthorizeRequestExtensions.cs, identity-server/src/IdentityServer/Hosting/DynamicProviders/Store/CachingIdentityProviderStore.cs, identity-server/src/IdentityServer/Hosting/DynamicProviders/Store/NonCachingIdentityProviderStore.cs, identity-server/src/IdentityServer/IdentityServerTools.cs, identity-server/src/IdentityServer/Licensing/LicenseValidator.cs, identity-server/src/IdentityServer/Services/Default/DefaultPersistedGrantService.cs, identity-server/src/IdentityServer/Stores/InMemory/InMemoryServerSideSessionStore.cs, identity-server/src/IdentityServer/Validation/Default/DefaultScopeParser.cs, identity-server/src/IdentityServer/Validation/Models/ParsedScopeValidationError.cs, identity-server/src/IdentityServer/Validation/Models/ParsedScopeValue.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Authorize/ResourceTests.cs, identity-server/test/IdentityServer.UnitTests/Services/Default/DefaultUserSessionTests.cs
Replaced `ArgumentNullException` with `ArgumentException` where appropriate to handle invalid arguments more effectively. Standardized syntax and fixed minor inconsistencies in method calls.
This knocked down some warnings I found throughout the codebase—no functionality changes.
=> Refactor exception handling and minor code improvements.

bff/src/Duende.Bff/SessionManagement/Revocation/SessionRevocationService.cs
Updated the `GetUserTicketsAsync` method to include a cancellation token parameter. This ensures proper cancellation handling during user ticket retrieval.
=> Add cancellation token support for ticket retrieval

.github/workflow-gen/Program.cs, .github/workflows/bff-ci.yml, .github/workflows/bff-release.yml, .github/workflows/identity-server-ci.yml, .github/workflows/identity-server-release.yml
This PR changes the build so that a build runs only once, and in the right security context, depending on their origins. 
_Previously, the build used pull_request_target. Effectively, this means that the entire context (including which code to build) was pointing to the target of the PR (likely main). This means it wasn't building anything in the PR, but actually building main (not very useful in a PR workflow)_ 
1. Builds / pr's from contributors are run trusted and can access security tokens needed for signing. If you create a branch in the DuendeSoftware repo, then you'll automatically get a CI build for this. You can (must) create a PR for this to get it merged. When you create a PR, the build script will detect that there is still a branch for it …
=> build - build with the correct security context

identity-server/migrations/AspNetIdentityDb/AspNetIdentityDb.csproj, identity-server/migrations/IdentityServerDb/IdentityServerDb.csproj
Updated project files to use `<TargetFrameworks>` instead of `<TargetFramework>` in both `IdentityServerDb.csproj` and `AspNetIdentityDb.csproj`.
=> Switch to TargetFrameworks for multi-framework support

identity-server/src/IdentityServer/Extensions/ClaimsExtensions.cs, identity-server/src/IdentityServer/Extensions/TokenExtensions.cs, identity-server/test/IdentityServer.UnitTests/Extensions/ApiResourceSigningAlgorithmSelectionTests.cs, identity-server/test/IdentityServer.UnitTests/Extensions/ClaimsExtensionsTests.cs, identity-server/test/IdentityServer.UnitTests/Extensions/TokenExtensionsTests.cs
This updates our serialization behavior so that we treat claims with either our json value type constant or the System.IdentityModel json value type constant the same. Prior to this change, we would serialize json with the System.IdentityModel as an escaped string instead of json, while our json value type constant would become json in the claims. 
After this change, either constant will work to put JSON into your claims. For example, code like this in a profile service will now serialize the claims as JSON, instead of a string containing escaped quotes:
```
var payload = 
"""
{
"nested": {
"sample": "value"
}
}
""";
context.IssuedClaims.Add(new Claim("json", payload, System.IdentityModel.Tokens.Jwt.JsonClaimValueTypes.Json))
```
=> Handle case-insensitive JSON claim value types.

.github/workflows/bff-ci.yml, .github/workflows/identity-server-ci.yml, bff/docs/upgrade-guide.md, bff/src/Bff.EntityFramework/Configuration/BffBuilderExtensions.cs
Fixes #1695
The method BffBuilderExtensions.AddAddEntityFrameworkServerSideSessionsServices() now is called AddEntityFrameworkServerSideSessionsServices(), without the duplicate 'add'. 
The name AddAddEntityFrameworkServerSideSessionsServices() has been renamed to AddEntityFrameworkServerSideSessionsServices.
If you used this method in your code, please rename it to .AddEntityFrameworkServerSideSessionsServices();
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in …
=> Remove duplicate 'add' in AddEntityFrameworkServerSideSessionsServices

identity-server/src/IdentityServer/Extensions/ValidatedAuthorizeRequestExtensions.cs, identity-server/test/IdentityServer.UnitTests/Extensions/ValidatedAuthorizeRequestExtensionsTests.cs
Filter client authentication because it's possible for a PAR request to include client auth, and we don't want that to cause client auth parameters to get passed into the authorization parameters message store, where they might get logged or otherwise stored insecurely.
=> Filter client credentials in ToOptimizedFullDictionary method

bff/hosts/Blazor/WebAssembly/Hosts.Bff.Blazor.WebAssembly.Client/Pages/Weather.razor, bff/hosts/Blazor/WebAssembly/Hosts.Bff.Blazor.WebAssembly.Client/Program.cs, bff/hosts/Blazor/WebAssembly/Hosts.Bff.Blazor.WebAssembly.Client/WeatherForecast.cs, bff/hosts/Blazor/WebAssembly/Hosts.Bff.Blazor.WebAssembly.Client/WeatherHttpClient.cs, bff/src/Bff.Blazor.Client/ServiceCollectionExtensions.cs, bff/test/Bff.Blazor.Client.UnitTests/AntiforgeryHandlerTests.cs, bff/test/Bff.Blazor.Client.UnitTests/ServiceCollectionExtensionsTests.cs, products.v3.ncrunchsolution
A AddLocalApiHttpClient extension method is added, similar to AddRemoteApiHttpClient. 
fixes #1698
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights …
=> bff - Add local client

identity-server/src/IdentityServer/Constants.cs, identity-server/src/IdentityServer/Extensions/HttpContextExtensions.cs, identity-server/src/IdentityServer/Hosting/IdentityServerMiddleware.cs, identity-server/src/IdentityServer/Stores/Default/ServerSideTicketStore.cs, identity-server/test/IdentityServer.IntegrationTests/Hosting/ServerSideSessionTests.cs
Scenarios can exist where session lifetime coordination is enabled but a session is expired and removed prior to the cleanup job running and processing that expiration. These changes account for that scenario and implement a workaround to detect when the dotnet cookie handler removes a session and triggers the session coordination service's processing of an expired session to ensure things such as backchannel logout and removal of grants.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the …
=> Ensure session lifetime coordination is invoked when a session expires

Directory.Packages.props, identity-server/clients/src/WindowsConsoleSystemBrowser/Program.cs, identity-server/clients/src/WindowsConsoleSystemBrowser/RegistryConfig.cs, identity-server/clients/src/WindowsConsoleSystemBrowser/WindowsConsoleSystemBrowser.csproj, identity-server/perf/IdentityServer.PerfTests/IdentityServer.PerfTests.csproj, identity-server/test/IdentityServer.IntegrationTests/Hosting/ServerSideSessionTests.cs
- `WindowsConsoleSystemBrowser` targets net8.0 (instead of net472) and some adjustments to get compiling
- `IdentityServer.PerfTests` targets net8.0 (instead of net6.0) and update package refs to get compiling again
This PR is stacked on #1768 and will be rebased when that is merged.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited …
=> Some fixes to get the products mono solution compiling. 

bff/hosts/Hosts.IdentityServer/Pages/Account/Login/Index.cshtml.cs, bff/src/Bff/EndpointServices/SilentLogin/PostConfigureOidcOptionsForSilentLogin.cs, bff/src/Bff/SessionManagement/Configuration/PostConfigureApplicationCookieRevokeRefreshToken.cs, bff/src/Bff/SessionManagement/Configuration/PostConfigureApplicationValidatePrincipal.cs, bff/src/Bff/SessionManagement/Configuration/PostConfigureSlidingExpirationCheck.cs, templates/src/IdentityServerEntityFramework/Pages/Account/Login/Index.cshtml.cs, templates/src/IdentityServerInMem/Pages/Account/Login/Index.cshtml.cs
This PR corrects improper semicolon usage in lambda expressions across multiple files by replacing them with closing braces. Ensures proper syntax adherence without introducing functional changes.
=> Fix misplaced semicolons in lambda expressions

identity-server/src/IdentityServer/Validation/Default/DefaultClientConfigurationValidator.cs, identity-server/test/IdentityServer.IntegrationTests/Clients/ClientCredentialsClient.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Token/DPoPTokenEndpointTests.cs, identity-server/test/IdentityServer.UnitTests/Validation/ClientConfigurationValidation.cs
Currently it's possible to configure a client to allow the `ClientCredentials` grant type and set `RequireClientSecret` on the client to `false` which creates a bad scenario. These changes update the `DefaultClientConfigurationValidator` to consider that scenario invalid.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the …
=> Ensure Client Secret is Required for Clients with ClientCredentials Grant

.github/workflow-gen/Program.cs, .github/workflows/bff-codeql-analysis.yml, .github/workflows/identity-server-codeql-analysis.yml
Using the CodeQL action's `autobuild` mode was resulting in both products being built in every workflow. These changes specify a product specific build in each CodeQL pipeline so each scan is only running on the appropriate product code.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes …
=> Manual CodeQL Build Commands

bff/hosts/Hosts.Bff.InMemory/ImpersonationAccessTokenRetriever.cs, bff/hosts/Hosts.IdentityServer/ServiceDiscoveringClientStore.cs, bff/src/Bff.Yarp/AccessTokenRequestTransform.cs, bff/src/Bff.Yarp/AccessTokenTransformProvider.cs, bff/src/Bff.Yarp/YarpTransformExtensions.cs, bff/src/Bff/Configuration/BffOptions.cs, bff/src/Bff/Extensions/HttpContextExtensions.cs, bff/src/Bff/General/AccessTokenRetrievalError.cs, bff/src/Bff/General/Log.cs, bff/test/Bff.Tests/Endpoints/RemoteEndpointTests.cs, bff/test/Bff.Tests/TestHosts/ApiHost.cs, bff/test/Bff.Tests/TestHosts/BffHost.cs, bff/test/Bff.Tests/TestHosts/FailureAccessTokenRetriever.cs, bff/test/Hosts.Tests/BffBlazorWebAssemblyTests.cs, bff/test/Hosts.Tests/BffTests.cs, bff/test/Hosts.Tests/BlazorPerComponentTests.cs
The BFF now detects, when it tries to request an access token to access **external services** that there was a failure to request an access token. Should this happen, then by default, the session will be terminated. This behavior can be disabled with a setting. 
The BCP for Browser Based Applications states:
> 6.1.2.2. [Refresh Tokens](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps#name-refresh-tokens)
> When the refresh token expires, there is no way to obtain a valid access token without running an entirely new Authorization Code flow. Therefore, it makes sense to configure the lifetime of the cookie-based session managed by the BFF to be equal to the maximum lifetime of the refresh token. **Additionally, when the BFF …
=> Signout on refresh token expire

.github/workflow-gen/Program.cs, .github/workflows/bff-release.yml, .github/workflows/identity-server-release.yml, .github/workflows/templates-release.yml
Due to a copy paste error, there's a double quote in the git-tag logic of the release branch. This removes it. 
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under …
=> fix double quotes in release build

bff/hosts/Blazor/PerComponent/Hosts.Bff.Blazor.PerComponent.Client/Components/CallApi.razor, bff/hosts/Hosts.IdentityServer/ServiceDiscoveringClientStore.cs, bff/src/Bff.Blazor/ServerSideTokenStore.cs, bff/src/Bff/EndpointServices/Logout/DefaultLogoutService.cs, bff/test/Bff.Tests/Endpoints/Management/LogoutEndpointTests.cs
When the refresh token is no longer valid, api calls returns a 401 status code. 
In the hosts, the front-end then detects this and attempts to completely terminate the session. However, now then it turned out that signing out twice didn't work. 
Signing out twice should now just work.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited …
=> Fixing issue when refresh token times out

src/IdentityServer/Services/Default/DefaultUserSession.cs
Removing the check for if we needed to update the session cookie was leading to scenarios where cookies with sliding sessions were being re-issued with the wrong expiration. This is reported in our GitHub discussions [here](https://github.com/orgs/DuendeSoftware/discussions/78). This PR reverts this change to restore the prior behavior.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such …
=> Revert Change Causing Unnecessary Cookie Re-Issue

.github/workflow-gen/Program.cs, .github/workflows/identity-server-release.yml
The back ported workflow from main contained an extra tag step which was causing the release workflow to fail. These changes remove the extra tag step.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, …
=> Removing redundant tag step in release workflow

identity-server/src/IdentityServer/Configuration/DependencyInjection/Options/DPoPOptions.cs, identity-server/src/IdentityServer/Configuration/DependencyInjection/Options/IdentityServerOptions.cs, identity-server/src/IdentityServer/Validation/Default/JwtRequestValidator.cs, identity-server/src/IdentityServer/Validation/Default/PrivateKeyJwtSecretValidator.cs, identity-server/src/IdentityServer/Validation/Default/TokenValidator.cs, identity-server/test/IdentityServer.UnitTests/Validation/AccessTokenValidation.cs, identity-server/test/IdentityServer.UnitTests/Validation/Secrets/PrivateKeyJwtSecretValidation.cs, identity-server/test/IdentityServer.UnitTests/Validation/Setup/Factory.cs
Added a new option for clock skew when validating JWTs. Currently, we use the default value of 5 minutes which is much higher than it needs to be and outside of the allowed range for the FAPI 2.0 Security Profile. The default value is within the range of the FAPI 2.0 Security Profile and allows for customizing as needed.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its …
=> JWT Validation Clock Skew Option

identity-server/src/IdentityServer/Configuration/DependencyInjection/Options/IdentityServerOptions.cs, identity-server/src/IdentityServer/Configuration/DependencyInjection/Options/PreviewFeaturesOptions.cs, identity-server/src/IdentityServer/Endpoints/DiscoveryEndpoint.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Discovery/DiscoveryEndpointTests.cs
This PR goes on top of #1830 and adds the [ExperimentalAttribute] to feature preview toggles.
When a preview feature toggle is used in consuming code, a diagnostic is reported and has to be suppressed to explicitly acknowledge using the toggle:
To disable, the developer can:
* Add `<PropertyGroup><NoWarn>DUENDEPREVIEW001</NoWarn></PropertyGroup>` to the project file
* Add `#pragma warning disable DUENDEPREVIEW001` at the call site
The diagnostic will also log a link to `https://duende.link/previewfeatures?id={0}` (with the format string replaced by the diagnostic) so we can explain what the feature preview is, how to opt-in, etc.
Background in https://blog.maartenballiauw.be/post/2023/11/08/opt-in-to-experimental-apis-using-csharp-12-experimentalattribute.html.
=> Add [ExperimentalAttribute] on preview feature toggles

global.json
This file sets the .NET SDK version to 9.0.103 and ensures using the latest patch updates. It also disables the use of prerelease versions for improved environment consistency.
This is an issue with `dotnet format` in the latest .NET SDK 9.0.200. This will likely be fixed in a future release.
=> Add global.json to specify .NET SDK version

.github/workflow-gen/Program.cs, .github/workflows/bff-ci.yml, .github/workflows/bff-codeql-analysis.yml, .github/workflows/bff-release.yml, .github/workflows/identity-server-ci.yml, .github/workflows/identity-server-codeql-analysis.yml, .github/workflows/identity-server-release.yml, .github/workflows/templates-release.yml
This pull request replaces the generic "9.0.x" with the explicit version "9.0.103" across multiple GitHub Actions workflows. The change ensures consistency, improves build reliability, and eliminates ambiguity regarding the .NET version used.
=> Update .NET version to 9.0.103 in workflows

identity-server/src/IdentityServer/Configuration/DependencyInjection/Options/IdentityServerOptions.cs, identity-server/src/IdentityServer/Configuration/DependencyInjection/Options/PreviewFeatureOptions.cs, identity-server/src/IdentityServer/Endpoints/DiscoveryEndpoint.cs, identity-server/src/IdentityServer/Endpoints/Results/DiscoveryDocumentResult.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Discovery/DiscoveryEndpointTests.cs, identity-server/test/IdentityServer.UnitTests/Infrastructure/ObjectSerializerTests.cs
Introduced a caching mechanism for the discovery document, configurable through the new `PreviewFeatureOptions`. This feature includes settings for enabling the cache and defining its duration. Updated related tests and classes to support and validate the caching implementation.
I ended up going with `IDistributedCache` to avoid any extra steps folks have to take.
=> Add caching support for discovery documents with preview options

bff/src/Bff.Blazor.Client/BffBlazorOptions.cs, identity-server/aspire/aspire.orchestrator/aspire.orchestrator.AppHost/aspire.orchestrator.AppHost.v3.ncrunchproject
The server polling interval is no longer needed. 
fixes: https://github.com/DuendeSoftware/products/issues/1864
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under …
=> Remove server polling interval

identity-server/src/IdentityServer/Configuration/DependencyInjection/Options/IdentityServerOptions.cs, identity-server/src/IdentityServer/Configuration/DependencyInjection/Options/PreviewFeatureOptions.cs, identity-server/src/IdentityServer/IdentityServerConstants.cs, identity-server/src/IdentityServer/Validation/Default/PrivateKeyJwtSecretValidator.cs, identity-server/test/IdentityServer.UnitTests/Validation/Secrets/PrivateKeyJwtSecretValidation.cs
This PR introduces the new `StrictClientAssertionAudienceValidation` preview flag.
The preview will enable users to optionally enforce a `typ` header requirement for client authentication jwts while also allowing clients to voluntarily opt into strict validation by setting the `typ` header value to `client-authentication+jwt`.
**Setting the flag within the IdentityServer host configuration**
In a typical IdentityServer host, users may set the preview flag through `options.Preview` feature flags, for example;
```csharp
builder.Services.AddIdentityServer(options =>
{
options.Preview.StrictClientAssertionAudienceValidation = true;
})
```
Setting this flag will mean that when clients authenticate with private_key_jwt assertions, IdentityServer will …
=> Introduce the `StrictClientAssertionAudienceValidation` preview feature

.editorconfig
We should really set this as the root, otherwise:
> EditorConfig plugins look for a file named .editorconfig (all lowercase) in the directory of the opened file and in every parent directory
_— <https://editorconfig.org/#file-location>_
=> set root editorconfig

identity-server/hosts/AspNetIdentity/Pages/Account/Login/Index.cshtml.cs, identity-server/templates/src/IdentityServerAspNetIdentity/Pages/Account/Login/Index.cshtml.cs
Uses the correct option (`LoginOptions.AllowRememberLogin`) to validate whether Remember Me should be allowed and used, instead of relying on the `View` model as it could be `null`, breaking the login.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant …
=> Use correct option to validate "Remember Me"

bff/src/Bff.Blazor/BffBlazorServerOptions.cs, bff/src/Bff.Blazor/BffBuilderExtensions.cs, bff/src/Bff.Blazor/BffServerAuthenticationStateProvider.cs
Moved BffServerOptions from the 'client' project to the Bff.Blazor project.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate …
=> move serveroptions to server project

.editorconfig, bff/src/Bff/EndpointProcessing/BffUserAccessTokenParameters.cs, bff/test/Bff.Tests/TestFramework/GenericHost.cs, bff/test/Hosts.Tests/TestInfra/AppHostFixture.cs
Enforce that 'this.' should not be used when it's redundant.
This PR is stacked on #1869 and will be rebased when that is merged.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, …
=> EditorConfig: Enforce that 'this.' should not be used when it's redundant

identity-server/src/IdentityServer/Configuration/DependencyInjection/Options/PreviewFeatureOptions.cs, identity-server/src/IdentityServer/Endpoints/DiscoveryEndpoint.cs, identity-server/src/IdentityServer/Validation/Default/PrivateKeyJwtSecretValidator.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Discovery/DiscoveryEndpointTests.cs, identity-server/test/IdentityServer.UnitTests/Validation/Secrets/PrivateKeyJwtSecretValidation.cs
Based on internal discussions, we are removing the build warnings brought on by using the `Experimental` flags.
The thought process around this is that because the options are explicitly under a "Preview" navigation property, users accessing these options implicitly acknowledge the preview nature of the feature.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, …
=> Remove the Experimental flags from the Preview options

identity-server/hosts/AspNetIdentity/Pages/Account/Login/Index.cshtml.cs, identity-server/hosts/Configuration/Pages/Account/Login/Index.cshtml.cs, identity-server/hosts/EntityFramework/Pages/Account/Login/Index.cshtml.cs, identity-server/hosts/main/Pages/Account/Login/Index.cshtml.cs, identity-server/templates/src/IdentityServerAspNetIdentity/Pages/Account/Login/Index.cshtml.cs, identity-server/templates/src/IdentityServerEntityFramework/Pages/Account/Login/Index.cshtml.cs, identity-server/templates/src/IdentityServerInMem/Pages/Account/Login/Index.cshtml.cs, identity-server/templates/src/UI/Pages/Account/Login/Index.cshtml.cs
There's an edge case where we don't set the displayname in the ui template for the login page. Normally that doesn't matter because our template would immediately challenge instead of needing to display the external provider. However, some users have run into situations where it caused errors for them. 
My speculation is that there was some additional customization performed, but we'll still apply this change because it doesn't add overhead and makes the template code more robust.
This is a recreation of a community PR to fix that issue. I've rebased onto the latest in main, and applied the fix to all hosts and templates.
Thanks to @stefannikolei for the original contribution!
=> Always include displayname in external providers

identity-server/src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs, identity-server/src/IdentityServer/Infrastructure/ConcurrencyLock/DefaultConcurrencyLock.cs
Changed the DI registration of `IConcurrencyLock<>` to Singleton to ensure consistent state for `SemaphoreSlim` locks. Also removed the static modifier from `SemaphoreSlim` to align its lifecycle with the class instance.
=> Use `DefaultConcurrencyLock` as a Singleton instead of Transient.

identity-server/hosts/AspNetIdentity/Pages/Diagnostics/Index.cshtml.cs, identity-server/hosts/AspNetIdentity/Pages/Extensions.cs, identity-server/hosts/AspNetIdentity/Pages/ServerSideSessions/Index.cshtml.cs, identity-server/hosts/Configuration/Pages/Diagnostics/Index.cshtml.cs, identity-server/hosts/Configuration/Pages/Extensions.cs, identity-server/hosts/Configuration/Pages/ServerSideSessions/Index.cshtml.cs, identity-server/hosts/EntityFramework/Pages/Diagnostics/Index.cshtml.cs, identity-server/hosts/EntityFramework/Pages/Extensions.cs, identity-server/hosts/EntityFramework/Pages/ServerSideSessions/Index.cshtml.cs, identity-server/hosts/main/Pages/Diagnostics/Index.cshtml.cs, identity-server/hosts/main/Pages/Extensions.cs, identity-server/hosts/main/Pages/ServerSideSessions/Index.cshtml.cs, identity-server/templates/src/IdentityServerAspNetIdentity/Pages/Diagnostics/Index.cshtml.cs, identity-server/templates/src/IdentityServerAspNetIdentity/Pages/Extensions.cs, identity-server/templates/src/IdentityServerAspNetIdentity/Pages/ServerSideSessions/Index.cshtml.cs, identity-server/templates/src/IdentityServerEntityFramework/Pages/Diagnostics/Index.cshtml.cs, identity-server/templates/src/IdentityServerEntityFramework/Pages/Extensions.cs, identity-server/templates/src/IdentityServerEntityFramework/Pages/ServerSideSessions/Index.cshtml.cs, identity-server/templates/src/IdentityServerInMem/Pages/Diagnostics/Index.cshtml.cs, identity-server/templates/src/IdentityServerInMem/Pages/Extensions.cs, identity-server/templates/src/IdentityServerInMem/Pages/ServerSideSessions/Index.cshtml.cs, identity-server/templates/src/UI/Pages/Diagnostics/Index.cshtml.cs, identity-server/templates/src/UI/Pages/Extensions.cs, identity-server/templates/src/UI/Pages/ServerSideSessions/Index.cshtml.cs
Takes extension method used in UI template for checking if connection is local and uses it across all templates and hosts. Also ensure that method is being applied appropriately in the server side session pages.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You …
=> Align Approach on Check If Request is Remote Amongst Hosts and Templates

identity-server/templates/src/IdentityServerAspNetIdentity/HostingExtensions.cs, identity-server/templates/src/IdentityServerEmpty/HostingExtensions.cs, identity-server/templates/src/IdentityServerEntityFramework/HostingExtensions.cs, identity-server/templates/src/IdentityServerInMem/HostingExtensions.cs
The templates were missing the registration of the license usage summary and throwing an exception on shut down rather than printing out the summary.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, …
=> Added registration of LicenseSummary to all templates

identity-server/src/IdentityServer/Extensions/AuthorizeResponseExtensions.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Authorize/AuthorizeTests.cs
This addresses a customer reported bug which was transferred to the internal backlog. The customer reported:
"We’ve noticed that the scope parameter is included in the callback URL after authentication in the authorization code flow, also when using PAR. This behavior seems unexpected, as scope is already handled during the authorization process and doesn’t appear to be required in the callback URL. In particular with PAR, where one of the benefits should be shorter URLs.
Wondering if this is an intentional design choice? If so, what purpose does it serve?"
Per RFC 6749, the only time the authorize endpoint needs to return the scope parameter is during the implicit flow as defined in [section 4.2.2](https://datatracker.ietf.org/doc/html/rfc6749#section- …
=> Don't unnecessarily return scope parameter from authorize endpoint

identity-server/aspire/aspire.orchestrator/aspire.orchestrator.ServiceDefaults/Extensions.cs, identity-server/aspire/aspire.orchestrator/aspire.orchestrator.ServiceDefaults/aspire.orchestrator.ServiceDefaults.csproj, identity-server/hosts/EntityFramework-dotnet9/IdentityServerExtensions.cs
Updated tracing to include IdentityServer-specific sources for improved observability. Added a project reference to Duende.IdentityServer and integrated `AddServiceDefaults` to enhance service configuration.
cc @StuFrankish
=> Add OpenTelemetry tracing and integrate IdentityServer

identity-server/src/IdentityServer/Endpoints/Results/AuthorizeResult.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Authorize/AuthorizeTests.cs, identity-server/test/IdentityServer.UnitTests/Endpoints/Results/AuthorizeResultTests.cs
Stop setting redirect URI and response mode on unsafe errors. The errors have been deemed unsafe to redirect so we should not enable them being presented to users. …
=> Don't return redirect URI or response mode on unsafe errors

identity-server/src/IdentityServer/Models/RefreshTokenCreationRequest.cs, identity-server/src/IdentityServer/Validation/Default/DefaultScopeParser.cs, identity-server/test/IdentityServer.UnitTests/Services/Default/DefaultRefreshTokenServiceTests.cs, identity-server/test/IdentityServer.UnitTests/Validation/TokenRequest Validation/TokenRequestValidation_Invalid.cs
This PR addresses an unhandled exception that gets raised whenever an expected collection of scopes is `null`.
- Includes nullability changes from [community PR](https://github.com/DuendeSoftware/products/pull/1929). (`default!` to `required`, and amended unit tests).
- Updates the `DefaultScopeParser` to return gracefully rather than throwing an exception (which was ultimately unhandled).
- Introduces a new unit test to cover `AuthorizedScopes` being null. A similar unit test to cover an empty collection for scopes is already present.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the …
=> Addresses an unhandled exception path & nullability concerns

bff/src/Bff/Configuration/BffEndpointRouteBuilderExtensions.cs, bff/src/Bff/Configuration/BffOptions.cs, bff/src/Bff/Configuration/BffServiceCollectionExtensions.cs, bff/src/Bff/Constants.cs, bff/src/Bff/EndpointServices/Login/DefaultLoginService.cs, bff/src/Bff/EndpointServices/SilentLogin/BffOpenIdConnectEvents.cs, bff/src/Bff/EndpointServices/SilentLogin/DefaultSilentLoginService.cs, bff/src/Bff/EndpointServices/SilentLogin/PostConfigureOidcOptionsForSilentLogin.cs, bff/src/Bff/Extensions/AuthenticationPropertiesExtensions.cs, bff/src/Bff/Extensions/HttpContextExtensions.cs, bff/test/Bff.Tests/Bff.Tests.net8.0.v3.ncrunchproject, bff/test/Bff.Tests/Endpoints/Management/LoginEndpointTests.cs, bff/test/Bff.Tests/Endpoints/Management/ManagementBasePathTests.cs, bff/test/Bff.Tests/TestHosts/IdentityServerHost.cs
The login endpoint now supports prompt=create (for silent login) and other prompts such as select. 
The existing silent-login endpoint now redirects to the login endpoint with prompt=none. 
This is a breaking change because some of the public constructors have changed.
fixes #https://github.com/DuendeSoftware/products/issues/1701
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback …
=> Implement prompt support for login

bff/src/Bff.Yarp/AntiforgeryMiddleware.cs, bff/src/Bff/Configuration/AnonymousSessionResponse.cs, bff/src/Bff/Configuration/BffOptions.cs, bff/src/Bff/Configuration/DisableAntiForgeryCheck.cs, bff/src/Bff/EndpointProcessing/BffMiddleware.cs, bff/src/Bff/EndpointServices/User/DefaultUserService.cs, bff/test/Bff.Tests/Endpoints/Management/UserEndpointTests.cs, bff/test/Bff.Tests/Endpoints/RemoteEndpointTests.cs, bff/test/Bff.Tests/Endpoints/YarpRemoteEndpointTests.cs, bff/test/Bff.Tests/PublicApiVerificationTests.VerifyPublicApi_Bff.verified.txt, bff/test/Bff.Tests/TestHosts/YarpBffHost.cs
The anti-forgery check can be disabled by changing the **BffOptions.DisableAntiForgeryRequest** method. 
fixes: https://github.com/DuendeSoftware/products/issues/1732 …
=> allow anti-forgery check to be disabled

identity-server/src/Telemetry/Tracing.cs
Currently `Tracing` class is marked as `internal` which stops us from extending `ActivitySource` declared in that class. Why would we want to extend it?
Duende Server currently adds few predefined values to traces produced by it and does it at different stages e.g. top level span for `connect/authorize` doesn't include `clientId` label. We would like to enrich all calls by `clientId` (wherever applicable of course) and with other labels depending on scenario.
How would that work? Example below
```csharp
Tracing.DuendeActivitySource.AddActivityListener(new ActivityListener
{
ShouldListenTo = _ => true,
ActivityStarted = activity =>
{
if (activity.Parent.TryGetCorrelationId(out var correlationId))
{
activity.SetTag(CorrelationIdKey, correlationId);
}
}, …
```
=> Made tracing class public to allow activity source extensions

Directory.Packages.props, identity-server/clients/src/ConsolePrivateKeyJwtClient/Program.cs, identity-server/clients/src/MvcJarJwt/AssertionService.cs, identity-server/clients/src/MvcJarUriJwt/AssertionService.cs, identity-server/src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs, identity-server/src/IdentityServer/Validation/Default/IntrospectionRequestValidator.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Discovery/DiscoveryEndpointTests.cs
Adds the PAR endpoint to the discovery doc's mTLS aliases.
=> Include PAR in mtls aliases

aspnetcore-authentication-jwtbearer/src/AspNetCore.Authentication.JwtBearer/DPoP/DPoPJwtBearerEvents.cs, aspnetcore-authentication-jwtbearer/test/AspNetCore.Authentication.JwtBearer.Tests/DPoPIntegrationTests.cs
As per https://www.rfc-editor.org/rfc/rfc9110#name-authentication-scheme the authentication scheme name must be treated as case insensitive.
=> Make DPoP authorization scheme case-insensitive

nuget.config, src/IdentityServer/Configuration/DependencyInjection/Options/LoggingOptions.cs, test/IdentityServer.IntegrationTests/Common/IdentityServerPipeline.cs, test/IdentityServer.IntegrationTests/Common/MockLogger.cs, test/IdentityServer.IntegrationTests/Endpoints/Authorize/PushedAuthorizationTests.cs
PAR requests sometimes are handled by the same code path as authorize requests, so both endpoint's default
sensitive values filter should be the same.
=> Harden default logging filters for PAR and Authorize endpoints (7.0)

nuget.config, src/IdentityServer/Configuration/DependencyInjection/Options/LoggingOptions.cs, test/IdentityServer.IntegrationTests/Common/IdentityServerPipeline.cs, test/IdentityServer.IntegrationTests/Common/MockLogger.cs, test/IdentityServer.IntegrationTests/Endpoints/Authorize/PushedAuthorizationTests.cs
PAR requests sometimes are handled by the same code path as authorize requests, so both endpoint's default
sensitive values filter should be the same.
=> Harden default logging filters for PAR and Authorize endpoints (7.1)

identity-server/src/IdentityServer/Configuration/DependencyInjection/Options/LoggingOptions.cs, identity-server/test/IdentityServer.IntegrationTests/Common/IdentityServerPipeline.cs, identity-server/test/IdentityServer.IntegrationTests/Common/MockLogger.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Authorize/PushedAuthorizationTests.cs
PAR requests sometimes are handled by the same code path as authorize requests, so both endpoint's default
sensitive values filter should be the same.
=> Harden default logging filters for PAR and Authorize endpoints (7.2)

identity-server/src/IdentityServer/Endpoints/PushedAuthorizationEndpoint.cs, identity-server/src/IdentityServer/Endpoints/Results/PushedAuthorizationErrorResult.cs, identity-server/src/IdentityServer/Endpoints/TokenEndpoint.cs, identity-server/src/IdentityServer/ResponseHandling/Models/PushedAuthorizationResponse.cs, identity-server/src/IdentityServer/Validation/Contexts/PushedAuthorizationRequestValidationContext.cs, identity-server/src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs, identity-server/src/IdentityServer/Validation/Default/DefaultDPoPProofValidator.cs, identity-server/src/IdentityServer/Validation/Default/PushedAuthorizationRequestValidator.cs, identity-server/src/IdentityServer/Validation/Models/PushedAuthorizationValidationResult.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Authorize/PushedAuthorizationTests.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Token/DPoPEndpointTestBase.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Token/DPoPPushedAuthorizationEndpointTests.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Token/DPoPTokenEndpointTests.cs, identity-server/test/IdentityServer.UnitTests/Validation/DPoPProofValidatorTests.cs
This PR adds support for the DPoP header at the PAR endpoint.
The DPoP header at the PAR endpoint is used to bind authorization codes to the client's dpop key. This can also be done by (and we already support) passing the dpop_jkt parameter.
This change improves our support for RFC 9449, as accepting the DPoP header is a requirement for compliance now that we implement PAR (section 10.1). We also now enforce the rule that if both the header and the dpop_jkt parameter are passed, they must be consistent. 
This PR also significantly refactors the existing DPOP integration tests to make them easier to read and reuse. Most behaviors are the same whether authorize parameters are pushed or not, and either or both of the dpop binding mechanisms can be used with PAR, so we want to run through …
=> Support binding of authorization codes to dpop proof key via dpop header

aspnetcore-authentication-jwtbearer/src/AspNetCore.Authentication.JwtBearer/DPoP/ConfigureJwtBearerOptions.cs, aspnetcore-authentication-jwtbearer/src/AspNetCore.Authentication.JwtBearer/DPoP/DPoPJwtBearerEvents.cs, aspnetcore-authentication-jwtbearer/src/AspNetCore.Authentication.JwtBearer/DPoP/DPoPOptions.cs, aspnetcore-authentication-jwtbearer/src/AspNetCore.Authentication.JwtBearer/DPoP/DPoPProofValidatonContext.cs, aspnetcore-authentication-jwtbearer/src/AspNetCore.Authentication.JwtBearer/DPoP/DPoPProofValidatonResult.cs, aspnetcore-authentication-jwtbearer/src/AspNetCore.Authentication.JwtBearer/DPoP/DPoPProofValidator.cs, aspnetcore-authentication-jwtbearer/src/AspNetCore.Authentication.JwtBearer/DPoP/DPoPServiceCollectionExtensions.cs, aspnetcore-authentication-jwtbearer/src/AspNetCore.Authentication.JwtBearer/DPoP/ReplayCache.cs, aspnetcore-authentication-jwtbearer/test/AspNetCore.Authentication.JwtBearer.Tests/AspNetCore.Authentication.JwtBearer.Tests.csproj, aspnetcore-authentication-jwtbearer/test/AspNetCore.Authentication.JwtBearer.Tests/DPoP/AccessTokenCnfTests.cs, aspnetcore-authentication-jwtbearer/test/AspNetCore.Authentication.JwtBearer.Tests/DPoP/DPoPProofValidatorTestBase.cs, aspnetcore-authentication-jwtbearer/test/AspNetCore.Authentication.JwtBearer.Tests/DPoP/FreshnessTests.cs, aspnetcore-authentication-jwtbearer/test/AspNetCore.Authentication.JwtBearer.Tests/DPoP/PayloadTests.cs, aspnetcore-authentication-jwtbearer/test/AspNetCore.Authentication.JwtBearer.Tests/DPoP/ReplayTests.cs, aspnetcore-authentication-jwtbearer/test/AspNetCore.Authentication.JwtBearer.Tests/DPoP/TestDPoPProofValidator.cs, aspnetcore-authentication-jwtbearer/test/AspNetCore.Authentication.JwtBearer.Tests/DPoP/TokenValidationTests.cs, aspnetcore-authentication-jwtbearer/test/AspNetCore.Authentication.JwtBearer.Tests/TestFramework/ApiHost.cs
This is a fairly significant refactor of the DPoP jwt bearer extension's extensibility model that makes most of the types internal. The intention is to make the intended extensibility points explicit, rather than just making everything public.
=> DPoP Jwt Bearer extensibility reworked

Directory.Build.props
- Autoincrement patch instead of minor. Major and minor version numbers are explicitly controlled by our release process.
- Add missing is- tag prefix config
(Intention is to merge this forward through all release branches, which should correct the version numbers of internal builds of bug fixes on release branches).
=> Update minver config

identity-server/Directory.Build.props
Merge 7.1 forward to 7.2, bringing forward minver config fixes.
=> 7.2 minver fix

.gitignore, identity-server/Directory.Build.targets, identity-server/src/IdentityServer/Endpoints/Results/ProtectedResourceErrorResult.cs, identity-server/test/Configuration.IntegrationTests/Configuration.IntegrationTests.csproj, identity-server/test/EntityFramework.IntegrationTests/EntityFramework.IntegrationTests.csproj, identity-server/test/EntityFramework.Storage.IntegrationTests/EntityFramework.Storage.IntegrationTests.csproj, identity-server/test/EntityFramework.Storage.UnitTests/EntityFramework.Storage.UnitTests.csproj, identity-server/test/IdentityServer.IntegrationTests/IdentityServer.IntegrationTests.csproj, identity-server/test/IdentityServer.UnitTests/Endpoints/Results/ProtectedResourceErrorResultTests.cs, identity-server/test/IdentityServer.UnitTests/IdentityServer.UnitTests.csproj
Introduce tests for ProtectedResourceErrorResult to ensure WWW-Authenticate header formatting is correct. Refactor header construction values into a single string.
=> Ensure WWW-Authenticate uses a single HTTP header 

identity-server/src/IdentityServer/Endpoints/TokenEndpoint.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Token/DPoPTokenEndpointTests.cs
Adjust the error returned when multiple DPoP headers are sent to conform to the FAPI 2.0 Profile
=> Adjust Multiple DPoP Token Error

identity-server/src/IdentityServer/Configuration/DependencyInjection/Options/LoggingOptions.cs
Adds the request object to sensitive value filters to avoid logging its value by default.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary …
=> Filter Request Object

aspnetcore-authentication-jwtbearer/src/AspNetCore.Authentication.JwtBearer/DPoP/DPoPJwtBearerEvents.cs, aspnetcore-authentication-jwtbearer/src/AspNetCore.Authentication.JwtBearer/DPoP/DPoPProofValidator.cs, aspnetcore-authentication-jwtbearer/test/AspNetCore.Authentication.JwtBearer.Tests/DPoP/PayloadTests.cs, aspnetcore-authentication-jwtbearer/test/AspNetCore.Authentication.JwtBearer.Tests/DPoPIntegrationTests.cs
=>  DPoP Error Handling in JwtBearerExtensions

identity-server/src/Telemetry/Telemetry.cs, identity-server/test/IdentityServer.UnitTests/Telemetry/TelemetryTests.cs
As documented at https://docs.duendesoftware.com/identityserver/diagnostics/otel/, the detailed metrics moved from the "Duende.IdentityServer.Experimental" service name to the stable "Duende.IdentityServer". These metrics are instrumented by the IdentityServer middleware and services, and track usage of specific flows and features.
If you have subscribed to the associated meters, for example in an OpenTelemetry dashboard, you'll need to update the service name going forward.
Associated docs PR: https://github.com/DuendeSoftware/docs.duendesoftware.com/pull/713
=> Remove "Duende.IdentityServer.Experimental" service name from telemetry

identity-server/src/IdentityServer/Configuration/DependencyInjection/Options/DPoPOptions.cs, identity-server/src/IdentityServer/Configuration/DependencyInjection/Options/IdentityServerOptions.cs, identity-server/src/IdentityServer/IdentityServerConstants.cs, identity-server/src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs, identity-server/src/IdentityServer/Validation/Default/DefaultDPoPProofValidator.cs, identity-server/src/IdentityServer/Validation/Default/JwtRequestValidator.cs, identity-server/src/IdentityServer/Validation/Default/PrivateKeyJwtSecretValidator.cs, identity-server/src/IdentityServer/Validation/Default/TokenValidator.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Authorize/JwtRequestAuthorizeTests.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Discovery/DiscoveryEndpointTests.cs, identity-server/test/IdentityServer.UnitTests/Validation/AccessTokenValidation.cs, identity-server/test/IdentityServer.UnitTests/Validation/DPoPProofValidatorTests.cs, identity-server/test/IdentityServer.UnitTests/Validation/Secrets/PrivateKeyJwtSecretValidation.cs
Adds new options for allowed signing algorithms for JWTs and DPoP proof tokens for scenarios when the supported algorithms need to be restricted such as the FAPI 2.0 Profile.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, …
=> Options of Allowed Signing Algorithms JWTs and DPoP Proof Tokens

identity-server/src/IdentityServer/Configuration/DependencyInjection/Options/DPoPOptions.cs, identity-server/src/IdentityServer/Configuration/DependencyInjection/Options/IdentityServerOptions.cs
Per some internal discussion it will be better to keep the default value of our `JwtValidationClockSkew` in line with the Wilson default and let users adjust as needed. Because we're keeping that as a higher default, there's not a reason to keep it aligned wit the same setting in the DPoP configuration so that setting is being adjusted back to its original value as well.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor …
=> Adjust Default Values for Clock Skew Config Options

identity-server/src/IdentityServer/Validation/Default/TokenRequestValidator.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Token/DPoPTokenEndpointTests.cs
As per the FAPI 2.0 conformance test suite, if we are missing a DPoP proof when it is required, we should return an invalid_request error (previously was invalid_dpop_proof).
=> Change error when required DPoP proof is missing

identity-server/src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/AuthSchemeInfoDiagnosticEntry.cs, identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticEntries/AssemblyInfoDiagnosticEntryTests.cs, identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticEntries/AuthSchemeInfoDiagnosticEntryTests.cs, identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticEntries/DiagnosticEntryTestHelper.cs
Stacks on #2021 to add a diagnostic entry for auth schemes
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate and use your …
=> Auth Scheme Diagnostic Entry

Directory.Packages.props, identity-server/src/IdentityServer/Configuration/DependencyInjection/Options/DPoPOptions.cs, identity-server/src/IdentityServer/Configuration/DependencyInjection/Options/IdentityServerOptions.cs, identity-server/src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs, identity-server/src/IdentityServer/Validation/Default/JwtRequestValidator.cs, identity-server/src/IdentityServer/Validation/Default/PrivateKeyJwtSecretValidator.cs, identity-server/src/IdentityServer/Validation/Default/TokenValidator.cs, identity-server/src/IdentityServer/Validation/Models/ValidatedRequest.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Authorize/JwtRequestAuthorizeTests.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Discovery/DiscoveryEndpointTests.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Discovery/DiscoveryEndpointTests_dpop_signing_algs_supported.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Discovery/DiscoveryEndpointTests_token_endpoint_auth_signing_algs_supported.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Discovery/DiscoveryEndpoint_request_object_auth_signing_algs_supported.cs, identity-server/test/IdentityServer.UnitTests/Validation/AccessTokenValidation.cs, identity-server/test/IdentityServer.UnitTests/Validation/Secrets/PrivateKeyJwtSecretValidation.cs
- Removed AllowedJwtAlgorithms
- Added SupportedClientAssertionSigningAlgorithms, which controls allowed algs for private_key_jwt
- Added SupportedRequestObjectSigningAlgorithms, which controls allowed algs for JAR
- No alg validation is now done in TokenValidator, instead we rely on the fact that we are validating tokens signed by IdentityServer, and that its signing keys (and their algorithms) are configurable.
=> Reworked supported algorithm options

identity-server/src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/RegisteredImplementationsDiagnosticEntry.cs, identity-server/src/IdentityServer/Licensing/V2/ServiceCollectionAccessor.cs, identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticEntries/RegisteredImplementationsDiagnosticEntryTests.cs
Stacks on #2022 to add a diagnostic entry for implementations registered for our interfaces
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary …
=> Registered Implementations Diagnostic Entry

identity-server/src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/DataProtectionDiagnosticEntry.cs, identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticEntries/DataProtectionDiagnosticEntryTests.cs
Stacks on #2024 to add a diagnostic entry for data protection configuration.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate …
=> Data Protection Diagnostic Entry

identity-server/src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/LicenseUsageDiagnosticEntry.cs, identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticEntries/LicenseUsageDiagnosticEntryTests.cs
Stacks on #2029 to add a diagnostic entry for license usage summary. …
=> License Usage Summary Diagnostic Entry

identity-server/src/IdentityServer/Services/Default/DefaultSessionCoordinationService.cs, identity-server/test/IdentityServer.UnitTests/Services/Default/DefaultSessionCoordinationServiceTests.cs
Make sure to do a null check on `client` in `ProcessExpirationAsync` to stop possible null reference exceptions when the client is not found.
=> Add null-check for client before coordinating session lifecycle

bff/src/Bff/BffBuilder.cs, bff/src/Bff/DynamicFrontends/IFrontendCollection.cs, bff/src/Bff/DynamicFrontends/Internal/ConfigureBffStartupFilter.cs, bff/src/Bff/DynamicFrontends/Internal/FrontendCollection.cs, bff/src/Bff/DynamicFrontends/Internal/FrontendSelector.cs, bff/src/Bff/DynamicFrontends/Internal/IndexHtmlHttpClient.cs, bff/test/Bff.Tests/Configuration/BffBuilderTests.cs, bff/test/Bff.Tests/MultiFrontend/FrontendSelectorTests.cs, bff/test/Bff.Tests/MultiFrontend/LocalFrontEndStoreTests.cs, bff/test/Bff.Tests/PublicApiVerificationTests.VerifyPublicApi_Bff.verified.txt, bff/test/Bff.Tests/TestInfra/BffTestHost.cs
This PR (re) exposes the capability for implementors of this library to add / remove frontends at runtime. Also, it felt better to call this FrontendCollection, which I think more clearly indicates that it doesn't persist any changes made to it. 
I had several options to perform this change:
1. Make the LocalFrontendStore sealed and public with an internal constructor. You only get an add / remove method publicly. 
2. Re-introduce an interface, but don't allow you to override it in the container. Might be easier for testing. 
3. Allow you to register something that's observable. For example an ObservableCollection<Frontend>. 
I decided to go for option 2. 
Initially, the simplest option would be to go for option 1. However, after consideration, if our …
=> Re-introduce interface for Frontendstore. 

identity-server/src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs, identity-server/src/IdentityServer/Infrastructure/RemovePropertyModifier.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/ClientLoadedTracker.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/ClientInfoDiagnosticEntry.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/IdentityServerOptionsDiagnosticEntry.cs, identity-server/src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs, identity-server/src/IdentityServer/Validation/Default/TokenRequestValidator.cs, identity-server/test/IdentityServer.UnitTests/Infrastructure/RemovePropertyModifierTests.cs, identity-server/test/IdentityServer.UnitTests/Licensing/v2/ClientLoadedTrackerTests.cs, identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticEntries/ClientInfoDiagnosticEntryTests.cs, identity-server/test/IdentityServer.UnitTests/Validation/AuthorizeRequest Validation/Authorize_ProtocolValidation_Resources.cs, identity-server/test/IdentityServer.UnitTests/Validation/Setup/Factory.cs
Adds mechanism for tracking loaded clients by non-default values and client info diagnostic entry for including the client data in the diagnostic dump.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, …
=> Client Info Diagnostic Entry

identity-server/hosts/EntityFramework-dotnet9/IdentityServerExtensions.cs, identity-server/hosts/EntityFramework/IdentityServerExtensions.cs
There is no need to run the session and grant cleanup jobs every few seconds unless you are working on those features specifically. The jobs generate noise in the logs when they are run too frequently.
=> Slow down cleanup job frequency in development

bff/src/Bff/BffBuilder.cs, bff/src/Bff/DynamicFrontends/BffConfigureCookieOptions.cs, bff/src/Bff/DynamicFrontends/BffConfigureOpenIdConnectOptions.cs, bff/src/Bff/SessionManagement/Configuration/PostConfigureApplicationCookieTicketStore.cs, bff/src/Bff/SessionManagement/Configuration/PostConfigureSlidingExpirationCheck.cs, bff/test/Bff.Tests/SessionManagement/CookieSlidingTests.cs, bff/test/Bff.Tests/TestInfra/BffTestBase.cs, bff/test/Bff.Tests/TestInfra/TestData.cs, bff/test/Bff.Tests/TestInfra/TestDataBuilder.cs, bff/test/Bff.Tests/TestInfra/TestHost.cs
The sliding cookie tests were still in the 'old' testing style.
Turns out that the new frontend style of wiring things wasn't working for sliding cookies. So now the tests explicitly run the 'old' and the 'new' style of wiring things up. This will likely be the pattern I'll use for future tests also, because I want to make sure you can still use V3 style (explicit auth wireup) and v4 style (automatic wireup)
Also, it turns out that, if you do AddScheme, aspnet core also adds a specific post configuration middleware:
https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Core/src/AuthenticationBuilder.cs#L52
We have to do the same in our dynamic scheme wireup. (basically, it only adds the timeprovider, but still, quite important) …
=> Fix the sliding cookie configuration when using frontend tests

identity-server/src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/ResourceInfoDiagnosticEntry.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/ResourceLoadedTracker.cs, identity-server/src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs, identity-server/src/IdentityServer/Validation/Default/TokenRequestValidator.cs, identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticEntries/ResourceInfoDiagnosticEntryTests.cs, identity-server/test/IdentityServer.UnitTests/Licensing/v2/ResourceLoadedTrackerTests.cs, identity-server/test/IdentityServer.UnitTests/Validation/AuthorizeRequest Validation/Authorize_ProtocolValidation_Resources.cs, identity-server/test/IdentityServer.UnitTests/Validation/Setup/Factory.cs
Adds mechanism to keep track of info on resources which have been used and a diagnostic entry to include that info in the diagnostic dump
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, …
=> Resource Info Diagnostic Entry

identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/AssemblyInfoDiagnosticEntry.cs, identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticEntries/AssemblyInfoDiagnosticEntryTests.cs
* Adds filtering to the assembly info diagnostic entry to restrict the list included to the most relevant assemblies for support
* Adds dotnet version to the assembly info diagnostic entry
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a …
=> Assembly Info Diagnostic Entry Tweaks

identity-server/hosts/Configuration/Host.Configuration.csproj, identity-server/hosts/EntityFramework-dotnet9/IdentityServerExtensions.cs, identity-server/hosts/EntityFramework/IdentityServerExtensions.cs, identity-server/hosts/Shared/Customization/ParameterizedScopeParser.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/RegisteredImplementationDetails.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/RegisteredImplementationsDiagnosticEntry.cs, identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticEntries/RegisteredImplementationsDiagnosticEntryTests.cs
Updates the registered implementations diagnostic entry to be aware of default implementations and only report on interfaces which do not have the default implementation(s) registered.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a …
=> Registered Implementation Diagnostic Entry Tweaks

identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/AssemblyInfoDiagnosticEntry.cs, identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticEntries/AssemblyInfoDiagnosticEntryTests.cs
We're now filtering the loaded assemblies, so the number doesn't match the list in the diagnostics. Doesn't seem to be much diagnostic value in either number, so I'm just removing it.
=> Remove assemblyCount from diagnostics

identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/TokenIssueCountDiagnosticEntry.cs, identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticEntries/TokenIssueCountDiagnosticEntryTests.cs
Minor rename but I thought "PoPDPoP" was kinda silly...
=> Remove pop from the names of token counts in diagnostics

Directory.Packages.props, bff/hosts/Hosts.IdentityServer/Config.cs, bff/src/Bff/Constants.cs, bff/src/Bff/DynamicFrontends/BffConfigureOpenIdConnectOptions.cs, bff/test/Bff.Tests/PublicApiVerificationTests.VerifyPublicApi_Bff.verified.txt, bff/test/Bff.Tests/TestInfra/IdentityServerTestHost.cs
Initially, the BFF used a custom signin url to distinguish between the v3 and v4 style authentication. 
The Microsoft openid connect library automatically initializes this to /signin-oidc. 
Turns out, this causes issues for people who want to stick to the default url. Also, it turns out that with the latest v4 bits, this custom url is no longer needed because frontend selection already has taken place at this point. 
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in …
=> remove custom signin-bff url

identity-server/src/IdentityServer/Events/Infrastructure/EventIds.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticSummary.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/Log.cs, identity-server/src/Telemetry/Tracing.cs, identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticSummaryTests.cs
* Adds EventId to diagnostic summary logs
* Puts diagnostic summary logs in an activity for easier correlation
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under …
=> Diagnostic Summary Log Tweaks

identity-server/aspire/AppHost/Properties/launchSettings.json, identity-server/aspire/ServiceDefaults/Extensions.cs, identity-server/aspire/ServiceDefaults/FallbackIsHostConfigurationSource.cs
Added custom configuration source with default values for when clients, APIs, and hosts are running outside the context of Aspire.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, …
=> IS Non-Aspire Default Config

bff/performance/Bff.Benchmarks/BenchmarkBase.cs, bff/performance/Bff.Benchmarks/Program.cs
Previously, the benchmark output contained units (in ms). This caused issues when sending the data to influxdb.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under …
=> Make sure benchmark setup doesn't include units

identity-server/clients/src/ConsolePrivateKeyJwtClient/Program.cs, identity-server/hosts/Shared/Configuration/ClientsConsole.cs, identity-server/src/Configuration/Validation/DynamicClientRegistration/DynamicClientRegistrationValidator.cs, identity-server/src/IdentityServer/Configuration/DependencyInjection/Options/IdentityServerOptions.cs, identity-server/src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Authorize/JwtRequestAuthorizeTests.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Discovery/DiscoveryEndpointTests_token_endpoint_auth_signing_algs_supported.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Discovery/DiscoveryEndpoint_request_object_auth_signing_algs_supported.cs
Reverts DuendeSoftware/products#2062, and sets default jwt algorithms to not include HMAC, as HMAC requires that the secret be insecurely stored in plain text.
=> Revert "Support client_secret_jwt client auth"

identity-server/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs, identity-server/test/IdentityServer.UnitTests/Hosting/MutualTlsEndpointMiddlewareTests.cs
When the mtls middleware fails to validate the incoming client
certificate, or if no certificate is presented, it now returns an HTTP
400 response, and includes the standardized json error:
```
{
"error": "invalid_client",
"error_description": "mTLS authentication failed"
}
```
This conforms to RFC 8705:
> If no certificate is presented, or that which is presented doesn't
> match that which is expected for the given client_id, the
> authorization server returns a normal OAuth 2.0 error response per
> Section 5.2 of [RFC6749] with the invalid_client error code to
> indicate failed client authentication.
=> Use standard error response for failed mTLS auth

identity-server/CHANGELOG.md, identity-server/src/Storage/Models/Client.cs
The XML docs on the property `Client.CoordinateLifetimeWithUserSession` pointed to a global configuration setting called `CoordinateTokensWithUserSession`. That setting's name is `CoordinateClientLifetimesWithUserSession`.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the …
=> Fixed typo in XML doc for Client.CoordinateLifetimeWithUserSession

identity-server/CHANGELOG.md, identity-server/src/IdentityServer/Validation/Default/RequestObjectValidator.cs, identity-server/test/IdentityServer.IntegrationTests/Common/IdentityServerPipeline.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/Authorize/PushedAuthorizationTests.cs
When posting a PAR containing the "request" request parameter, then none of the typical authorization request parameters can be present in the posted form body. The only parameters allowed in this scenario are the ones needed for client authentication and the request parameter itself.
This PR fixes [the issue](https://github.com/orgs/DuendeSoftware/discussions/235) described in our community discussions.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any …
=> Reject Pushed Authorization Requests with parameters duplicated in a JAR

bff/migrations/Directory.Build.props, bff/src/Bff.Blazor/BffBuilderExtensions.cs, bff/src/Bff.Blazor/BffServerAuthenticationStateProvider.cs, bff/src/Bff.Blazor/ServerSideTokenStore.cs, bff/src/Bff.EntityFramework/Internal/UserSessionStore.cs, bff/src/Bff.EntityFramework/ModelBuilderExtensions.cs, bff/src/Bff.EntityFramework/UserSessionEntity.cs, bff/src/Bff/AuthenticationTicketExtensions.cs, bff/src/Bff/BffBuilder.cs, bff/src/Bff/Endpoints/Internal/DefaultBackchannelLogoutEndpoint.cs, bff/src/Bff/Otel/LogMessages.cs, bff/src/Bff/SessionManagement/Revocation/SessionRevocationService.cs, bff/src/Bff/SessionManagement/SessionStore/BuildUserSessionPartitionKey.cs, bff/src/Bff/SessionManagement/SessionStore/IUserSessionStore.cs, bff/src/Bff/SessionManagement/SessionStore/InMemoryUserSessionStore.cs, bff/src/Bff/SessionManagement/SessionStore/PartitionKey.cs, bff/src/Bff/SessionManagement/SessionStore/UserKey.cs, bff/src/Bff/SessionManagement/SessionStore/UserSession.cs, bff/src/Bff/SessionManagement/SessionStore/UserSessionKey.cs, bff/src/Bff/SessionManagement/SessionStore/UserSessionsFilter.cs, bff/src/Bff/SessionManagement/TicketStore/ServerSideTicketStore.cs, bff/test/Bff.Tests/Endpoints/Management/BackchannelLogoutEndpointTests.cs, bff/test/Bff.Tests/EntityFramework/UserSessionStoreTests.cs, bff/test/Bff.Tests/PublicApiVerificationTests.VerifyPublicApi_Bff.verified.txt, bff/test/Bff.Tests/PublicApiVerificationTests.VerifyPublicApi_Bff_EntityFramework.verified.txt, bff/test/Bff.Tests/SessionManagement/CookieSlidingTests.cs, bff/test/Bff.Tests/SessionManagement/ServerSideTicketStoreTests.cs, bff/test/Bff.Tests/SessionManagement/ServerSideTokenStoreTests.cs, bff/test/Bff.Tests/TestInfra/TestData.cs, bff/test/Bff.Tests/TestInfra/TestDataBuilder.cs
When implementing an ApplicationBuilder, I ran into the issue that the session storage should not depend on the partition key, but instead should have this injected. 
* For testing purposes, I introduced a delegate for the partition key generation. Note, this delegate is public, because people need to be able to use it, but not an extensibility point (cannot be overwritten)
* Introduced strongly typed values for PartitionKey and UserSessionkey. In the DB, this is converted back to a string. 
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a …
=> moved partition key building out of session store

identity-server/CHANGELOG.md, identity-server/src/IdentityServer/Extensions/HttpContextExtensions.cs, identity-server/test/IdentityServer.UnitTests/Extensions/HttpContextExtensionsTests.cs, identity-server/test/IdentityServer.UnitTests/Services/Default/DefaultIdentityServerInteractionServiceTests.cs
If no clients for the current users session have `FrontChannelLogoutUri` configured, do not generate the iFrame url for the end session callback as it is not necessary. …
=> Skip front-channel logout iframe when unnecessary

identity-server/src/Directory.Build.props
Stacks on #2114 to document that we will keep [CA1034](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1034) on the NoWarn list. …
=> Address CA1034 Violations

bff/src/Bff.Blazor/BffBuilderExtensions.cs, bff/src/Bff.Yarp/Internal/AccessTokenRequestTransform.cs, bff/src/Bff.Yarp/Internal/ProxyBffPluginLoader.cs, bff/src/Bff.Yarp/Internal/RemoteApiConfiguration.cs, bff/src/Bff.Yarp/Internal/RemoteRouteHandler.cs, bff/src/Bff.Yarp/RemoteApi.cs, bff/src/Bff.Yarp/ReverseProxyEndpointConventionBuilderExtensions.cs, bff/src/Bff/BffBuilderExtensions.cs, bff/src/Bff/DynamicFrontends/Internal/BffCacheClearingHostedService.cs, bff/src/Bff/DynamicFrontends/Internal/BffIndex.cs, bff/src/Bff/DynamicFrontends/Internal/FrontendCollection.cs, bff/src/Bff/DynamicFrontends/Internal/IndexHtmlHttpClient.cs, bff/src/Bff/DynamicFrontends/Origin.cs, bff/src/Bff/Otel/LogMessages.cs, bff/src/Bff/SessionManagement/Configuration/PostConfigureApplicationCookieRevokeRefreshToken.cs, bff/test/Bff.Tests/BffFrontendIndexTests.cs, bff/test/Bff.Tests/BffFrontendSigninTests.cs, bff/test/Bff.Tests/BffRemoteApiTests.cs, bff/test/Bff.Tests/Blazor/BffBlazorTests.cs, bff/test/Bff.Tests/Configuration/BffBuilderTests.cs, bff/test/Bff.Tests/PublicApiVerificationTests.VerifyPublicApi_Bff.verified.txt, bff/test/Bff.Tests/PublicApiVerificationTests.VerifyPublicApi_Bff_Yarp.verified.txt, bff/test/Bff.Tests/TestInfra/BffTestHost.cs, bff/test/Bff.Tests/TestInfra/TestHybridCache.cs, bff/test/Bff.Tests/TestInfra/TestLoggerProvider.cs, bff/test/Bff.Tests/TestInfra/TestTokenRetriever.cs, bff/test/Hosts.Tests/TestInfra/BffClient.cs
- **throw clear exception when no server side sessions registered**
- **make activity timeout configurable**
- **adding BffUserAccessTokenParameters and AccessTokenRetrieverType for frontend mapped routes**
- **Move applying backchannelhandler to an extension method**
- **added warning log message when duplicate frontends added**
- **volatile is ok**
- **introduce a parseordefault on origin**
- **logging when retrieving indexhtml and moved cache busting to background service**
- **don't implement an ITokenRevocationService yet**
- **Implement caching for transformers**
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed …
=> Address several todo's in the bff codebase

identity-server/src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticContext.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/AssemblyInfoDiagnosticEntry.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/AuthSchemeInfoDiagnosticEntry.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/BasicServerInfoDiagnosticEntry.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/ClientInfoDiagnosticEntry.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/DataProtectionDiagnosticEntry.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/EndpointUsageDiagnosticEntry.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/IdentityServerOptionsDiagnosticEntry.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/LicenseUsageDiagnosticEntry.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/RegisteredImplementationsDiagnosticEntry.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/ResourceInfoDiagnosticEntry.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/TokenIssueCountDiagnosticEntry.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticSummary.cs, identity-server/src/Storage/Models/GrantType.cs, identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticEntries/BasicServerInfoDiagnosticEntryTests.cs, identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticEntries/DiagnosticEntryTestHelper.cs, identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticEntries/TokenIssueCountDiagnosticEntryTests.cs, identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticSummaryTests.cs
* Adds serve startup and current time to basic server info to provide more context to the rest of the data in the diagnostic dump
* Reworks structure of the token count diagnostic entry based on feedback
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant …
=> Token Diagnostic Entry Updates

bff/src/Bff/BffApplicationBuilderExtensions.cs, bff/src/Bff/DynamicFrontends/Internal/ConfigureBffStartupFilter.cs, bff/test/Bff.Tests/BffFrontendMatchingTests.cs, bff/test/Bff.Tests/PublicApiVerificationTests.VerifyPublicApi_Bff.verified.txt, bff/test/Bff.Tests/TestInfra/BffTestHost.cs
A user reported that, if there is a proxy BEFORE the BFF, then there is a problem with handling the xforwarded headers correctly. 
https://github.com/orgs/DuendeSoftware/discussions/281
Basically, if you automatically register the BFF middleware, then it's harder to also add the XForward header checks in the pipeline. Technically, a user could also add a startup filter to add this, but I think it's a legitimate usecase. 
With this PR, the BFF now automatically adds the XForward middleware at the beginning of the pipeline. It's still up to the user to configure it. Without any configuration, this middleware should be a noop. 
Also, I've made it easier for users with two extension methods to manually add the BFF to the aspnet pipeline, if automatic …
=> add xforwarded header support

bff/src/Bff/Extensions/HttpContextExtensions.cs
There are openid connect providers that return non standard casings for Bearer or DPoP token names.
fixes https://github.com/DuendeSoftware/products/issues/2131 …
=> make sure access token type is case insensitive

identity-server/templates/src/IdentityServer/Pages/Account/Login/Index.cshtml, identity-server/templates/src/IdentityServer/Pages/Account/Logout/Index.cshtml, identity-server/templates/src/IdentityServer/Pages/Admin/ApiScopes/ApiScopeRepository.cs, identity-server/templates/src/IdentityServer/Pages/Admin/ApiScopes/Edit.cshtml, identity-server/templates/src/IdentityServer/Pages/Admin/ApiScopes/New.cshtml, identity-server/templates/src/IdentityServer/Pages/Admin/ApiScopes/New.cshtml.cs, identity-server/templates/src/IdentityServer/Pages/Admin/Clients/ClientRepository.cs, identity-server/templates/src/IdentityServer/Pages/Admin/Clients/Edit.cshtml, identity-server/templates/src/IdentityServer/Pages/Admin/Clients/EditSecret.cshtml, identity-server/templates/src/IdentityServer/Pages/Admin/Clients/New.cshtml, identity-server/templates/src/IdentityServer/Pages/Admin/Clients/New.cshtml.cs, identity-server/templates/src/IdentityServer/Pages/Admin/IdentityScopes/Edit.cshtml, identity-server/templates/src/IdentityServer/Pages/Admin/IdentityScopes/IdentityScopeRepository.cs, identity-server/templates/src/IdentityServer/Pages/Admin/IdentityScopes/New.cshtml, identity-server/templates/src/IdentityServer/Pages/Admin/IdentityScopes/New.cshtml.cs
Stacks on #2162 to improve the organization of the client creation form.
- Don't generate client_id
- Move client_id and secret to be top of form
- Change label of name from client name to display name
- Move uncommonly used uris lower in the form
=> Reorganize client creation in template

identity-server/CHANGELOG.md, identity-server/src/Directory.Build.props, identity-server/src/Shared/Telemetry/Telemetry.cs
Removes [CA2211](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2211) from the NoWarn list and addresses the resulting violations. This is technically a breaking change as the affected properties are public, but I could not think of a reason anyone would need to modify our Otel counters.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its …
=> Address CA2211 Violations

identity-server/src/IdentityServer/Licensing/V2/Diagnostics/ClientLoadedTracker.cs, identity-server/test/IdentityServer.UnitTests/IdentityServer.UnitTests.csproj
This sets a non-null value into a default client that is serialized, allowing RespectNullableAnnotationsDefault to be enabled.
=> Support RespectNullableAnnotationsDefault 

identity-server/hosts/AspNetIdentity/IdentityServerExtensions.cs, identity-server/hosts/EntityFramework-dotnet9/IdentityServerExtensions.cs, identity-server/hosts/EntityFramework/IdentityServerExtensions.cs, identity-server/hosts/main/IdentityServerExtensions.cs
In all hosts, set the InitializationSynchronizationDelay to 0. This
makes it faster for the hosts to reach a healthy state, and is safe to
do as they are never run in a load balanced environment.
=> Set synchronization delay to 0

identity-server/src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs, identity-server/src/IdentityServer/Configuration/DependencyInjection/Options/EndpointOptions.cs, identity-server/src/IdentityServer/Endpoints/BaseDiscoveryEndpoint.cs, identity-server/src/IdentityServer/Endpoints/DiscoveryEndpoint.cs, identity-server/src/IdentityServer/Endpoints/OAuthMetadataEndpoint.cs, identity-server/src/IdentityServer/Hosting/Endpoint.cs, identity-server/src/IdentityServer/Hosting/EndpointHelpers.cs, identity-server/src/IdentityServer/Hosting/EndpointRouter.cs, identity-server/src/IdentityServer/IdentityServerConstants.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/EndpointUsageDiagnosticEntry.cs, identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/RegisteredImplementationsDiagnosticEntry.cs, identity-server/src/IdentityServer/Logging/ILoggerExtensions.cs, identity-server/src/IdentityServer/Validation/Default/DefaultIssuerPathValidator.cs, identity-server/src/IdentityServer/Validation/IIssuerPathValidator.cs, identity-server/test/IdentityServer.IntegrationTests/Common/IdentityServerPipeline.cs, identity-server/test/IdentityServer.IntegrationTests/Endpoints/OAuthMetadata/OAuthMetadataTests.cs, identity-server/test/IdentityServer.UnitTests/Hosting/EndpointHelpersTests.cs, identity-server/test/IdentityServer.UnitTests/Hosting/EndpointRouterTests.cs, identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticEntries/EndpointUsageDiagnosticEntryTests.cs, identity-server/test/IdentityServer.UnitTests/Validation/DefaultIssuerPathValidatorTests.cs
Adds support for [RFC 8414: OAuth 2.0 Authorization Server Metadata](https://datatracker.ietf.org/doc/html/rfc8414). 
This also required adjustments to the endpoint routing to accommodate a path that isn't an exact match to support issue identifiers with path components.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the …
=> RFC 8414 support

bff/src/Bff/BffEndpointRouteBuilderExtensions.cs, bff/test/Bff.Tests/Endpoints/WireupTests.cs, bff/test/Bff.Tests/TestInfra/BffTestHost.cs
Fixes a bug that required you to disable the automatic mapping of endpoints if you use a template in the ManagementBasePath. 
Fixes the issue reported here:
https://github.com/orgs/DuendeSoftware/discussions/301
fixes:https://github.com/DuendeSoftware/issues/issues/531
Automatic mapping of mangement endpoints is checking if the management endpoints are already registered. If so, this should have been a no-op. However, if you use templates (IE /{someid}/bff as the bff base path, then this check failed. This was caused because a RoutePrefix.ToString() returns an url encoded version. The RoutePrefix.Value doesn't. 
If You provide us with any comments, bug reports, …
=> allow support for management basepath with templates

identity-server/CHANGELOG.md, identity-server/src/IdentityServer/Hosting/IdentityServerMiddleware.cs, identity-server/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs, identity-server/test/IdentityServer.IntegrationTests/Common/MockHttpActivityFeature.cs, identity-server/test/IdentityServer.IntegrationTests/Common/MockTestActivityMiddleware.cs, identity-server/test/IdentityServer.IntegrationTests/Hosting/IdentityServerMiddlewareTests..cs
Set the http activity's display name when IdentityServer routes to it. This makes OTel traces easier to read because the incoming HTTP request will display where it is headed.
=> Set HTTP activity name on routing

identity-server/CHANGELOG.md, identity-server/src/IdentityServer/Extensions/AuthorizeResponseExtensions.cs, identity-server/src/IdentityServer/ResponseHandling/Models/AuthorizeResponse.cs, identity-server/test/IdentityServer.IntegrationTests/Extensibility/CustomAuthorizeResponseGeneratorTests.cs
Adds extensibility point for custom parameters in an authorize response.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate and …
=> Support for custom parameters in authorize response

identity-server/hosts/UI/AspNetIdentity/Pages/ExternalLogin/Callback.cshtml.cs, identity-server/hosts/UI/Main/Pages/ExternalLogin/Callback.cshtml.cs, identity-server/templates/src/IdentityServer/Pages/ExternalLogin/Callback.cshtml.cs, identity-server/templates/src/IdentityServerAspNetIdentity/Pages/ExternalLogin/Callback.cshtml.cs, identity-server/templates/src/IdentityServerEntityFramework/Pages/ExternalLogin/Callback.cshtml.cs, identity-server/templates/src/IdentityServerInMem/Pages/ExternalLogin/Callback.cshtml.cs
Ensures both subject and name identifier claims are removed in external callbacks before potentially provisioning a user.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive …
=> Ensure Subject and Name Identifier Removed in External Callback

identity-server/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs
We are currently always requesting a new issuer when creating a new key. We do not need to do this if we're not using X509s.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive …
=> Key Creation Optimization

.github/workflow-gen/Program.cs, .github/workflow-gen/StepExtensions.cs, .github/workflows/bff-ci.yml
Improve Playwright Installation / Setup that can take upwards of 12 minutes in certain cases by caching the artifacts for future runs.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, …
=> Improve Playwright setup by caching artifacts

identity-server/CHANGELOG.md, identity-server/src/AspNetIdentity/ConfigureSecurityStampValidatorOptions.cs, identity-server/src/AspNetIdentity/DefaultSessionClaimsFilter.cs, identity-server/src/AspNetIdentity/ISessionClaimsFilter.cs, identity-server/src/AspNetIdentity/IdentityServerBuilderExtensions.cs, identity-server/src/AspNetIdentity/SecurityStampValidatorCallback.cs, identity-server/test/IdentityServer.UnitTests/AspNetIdentity/DefaultSessionClaimsFilterTests.cs, identity-server/test/IdentityServer.UnitTests/IdentityServer.UnitTests.csproj, identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticEntries/RegisteredImplementationsDiagnosticEntryTests.cs
This replaces are current approach to persisting session based claims in ASP.NET Identity which are not stored in the data store but need to be kept around during the user's session. Our new approach limits the default claims included in the filter and provides an extension point via the `ISessionClaimsFilter` interface for those who need something different.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have …
=> Use Customizable Filter to Persist Session Claims in ASP.NET Identity
