- src/IdentityServer/Extensions/TokenExtensions.cs
- test/IdentityServer.UnitTests/Extensions/TokenExtensionsTests.cs
> Parsing claim object by claim valueType

- src/IdentityServer/Configuration/DependencyInjection/Options/KeyManagementOptions.cs
- src/IdentityServer/Services/Default/KeyManagement/KeySerializer.cs
* remove use of json.net #59
* add check to prevent mis-configuration of EC keys with X509 containers
> key management updates (try 2)

- src/IdentityServer/Constants.cs
- src/IdentityServer/Extensions/ValidatedAuthorizeRequestExtensions.cs
- src/IdentityServer/Models/Messages/AuthorizationRequest.cs
- src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs
- src/IdentityServer/Validation/Models/ValidatedAuthorizeRequest.cs
- test/IdentityServer.IntegrationTests/Common/IdentityServerPipeline.cs
- test/IdentityServer.IntegrationTests/Endpoints/Authorize/AuthorizeTests.cs
- test/IdentityServer.IntegrationTests/Endpoints/Authorize/JwtRequestAuthorizeTests.cs
- test/IdentityServer.UnitTests/ResponseHandling/AuthorizeInteractionResponseGenerator/AuthorizeInteractionResponseGeneratorTests_Login.cs
- test/IdentityServer.UnitTests/Validation/AuthorizeRequest Validation/Authorize_ProtocolValidation_Valid.cs
> Allow for prompt handling to maintain original values when sent to login page

- src/EntityFramework/Services/CorsPolicyService.cs
- test/EntityFramework.Tests/Services/CorsPolicyServiceTests.cs
> Remove usage of HttpContextAccessor in CorsPolicyService

- clients/Duende.IdentityServer.Clients.sln
- clients/src/ConsoleCode/SystemBrowser.cs
- clients/src/ConsoleResourceIndicators/ConsoleResourceIndicators.csproj
- clients/src/ConsoleResourceIndicators/LoopbackHttpListener.cs
- clients/src/ConsoleResourceIndicators/Program.cs
- clients/src/ConsoleResourceIndicators/SystemBrowser.cs
- hosts/Configuration/ClientsConsole.cs
to exercise scope/resource combinations
> Add interactive resource indicator sample

- src/IdentityServer/Hosting/IdentityServerMiddleware.cs
- src/IdentityServer/Validation/Default/LicenseValidator.cs
- test/IdentityServer.UnitTests/Validation/LicenseValidatorTests.cs
> License validator updates

- .config/dotnet-tools.json
- .github/workflows/ci.yml
- build.cmd
- build.ps1
- build.sh
- build/Program.cs
Signs all NuGet packages with the Duende Code Signing certificate
> Add NuGet package signing

- src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs
- test/IdentityServer.UnitTests/Validation/AuthorizeRequest Validation/Authorize_ProtocolValidation_Valid.cs
> Remove nonce requirement when no id_token requested from authorize endpoint

- Directory.Build.targets
- src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs
This is a minor improvement to improve OIDC interoperability. Result of conformance testing
> Emit supported signing algorithms for request objects

- src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs
- src/IdentityServer/Stores/Default/DistributedCacheAuthorizationParametersMessageStore.cs
- src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs
- src/IdentityServer/Validation/Default/JwtRequestValidator.cs
- src/IdentityServer/Validation/IJwtRequestValidator.cs
Preserve request objects based on request objects URI to make this works transparently with authorization parameter stores
> Preserve request objects based on request objects URI

- src/IdentityServer/Validation/Default/LicenseValidator.cs
- test/IdentityServer.UnitTests/Validation/LicenseValidatorTests.cs
Added a flag to the license key for ISV licenses, and adjusted community limits.
Fixes #120
> Add ISV flag and update license key validation

- src/IdentityServer/Services/Default/DefaultKeyMaterialService.cs
This PR changes the behavior for which signing key is chosen. With this change if an explicit signing key is registered, then it should be preferred over the keys from the automatic key management feature.
Fixes: #177
> Prefer explicitly registered signing keys over automatic key management keys

- src/IdentityServer/Endpoints/AuthorizeCallbackEndpoint.cs
- src/IdentityServer/Endpoints/AuthorizeEndpoint.cs
- src/IdentityServer/Endpoints/AuthorizeEndpointBase.cs
- src/IdentityServer/Models/Messages/ConsentRequest.cs
- test/IdentityServer.IntegrationTests/Common/BrowserHandler.cs
- test/IdentityServer.IntegrationTests/Endpoints/Authorize/JwtRequestAuthorizeTests.cs
- test/IdentityServer.UnitTests/Endpoints/Authorize/AuthorizeEndpointBaseTests.cs
- test/IdentityServer.UnitTests/Endpoints/Authorize/AuthorizeEndpointTests.cs
- test/IdentityServer.UnitTests/Endpoints/Authorize/StubAuthorizeRequestValidator.cs
5.1.0 patch fix of this: https://github.com/DuendeSoftware/IdentityServer/pull/200
> move consent message store loading to after request validation

- hosts/AspNetIdentity/Quickstart/Account/AccountController.cs
- hosts/EntityFramework/Quickstart/Account/AccountController.cs
- hosts/main/Quickstart/Account/AccountController.cs
- src/EntityFramework.Storage/Stores/IdentityProviderStore.cs
- src/IdentityServer/Hosting/DynamicProviders/Store/CachingIdentityProviderStore.cs
- src/IdentityServer/Hosting/DynamicProviders/Store/InMemoryOidcProviderStore.cs
- src/IdentityServer/Hosting/DynamicProviders/Store/NopIdentityProviderStore.cs
- src/Storage/Models/IdentityProvider.cs
- src/Storage/Stores/IIdentityProviderStore.cs
Add missing GetAllSchemeNames API to the IIdentityProviderStore.
> Add missing GetAllSchemeNames to the IIdentityProviderStore

- src/IdentityServer/Validation/Default/PrivateKeyJwtSecretValidator.cs
- test/IdentityServer.UnitTests/Validation/Secrets/PrivateKeyJwtSecretValidation.cs
Original request/PR: https://github.com/DuendeSoftware/IdentityServer/pull/310
> Add physical token endpoint to audience list for private key JWTs

- Directory.Build.targets
- build/Program.cs
supersedes https://github.com/DuendeSoftware/IdentityServer/pull/308
> Bump SimpleExec from 7.0.0 to 8.0.0

- src/IdentityServer/Duende.IdentityServer.csproj
- src/IdentityServer/Infrastructure/ObjectSerializer.cs
- src/IdentityServer/Logging/LogSerializer.cs
- src/IdentityServer/Services/Default/NumericUserCodeGenerator.cs
- src/Storage/Stores/Serialization/PersistentGrantSerializer.cs
> Fix obsolete warnings

- .github/workflows/ci.yml
- Directory.Build.targets
- global.json
> Update to .NET 6 Preview 6

- src/IdentityServer/Validation/Default/LicenseValidator.cs
> For ISV license, reduce startup license log level to trace

- src/EntityFramework.Storage/Entities/ApiScope.cs
- src/EntityFramework.Storage/Entities/Client.cs
- src/EntityFramework.Storage/Entities/IdentityProvider.cs
> Add missing columns for created, updated, etc to EF entities

- .github/workflows/ci.yml
- Directory.Build.targets
- global.json
- src/IdentityServer/Duende.IdentityServer.csproj
> Updates for .NET 6 Preview 7

- src/EntityFramework.Storage/Configuration/ServiceCollectionExtensions.cs
- src/EntityFramework.Storage/DbContexts/ConfigurationDbContext.cs
- src/EntityFramework.Storage/DbContexts/PersistedGrantDbContext.cs
- src/EntityFramework.Storage/Options/ConfigurationStoreOptions.cs
- src/EntityFramework.Storage/Options/OperationalStoreOptions.cs
- test/EntityFramework.Storage.IntegrationTests/DatabaseProviderBuilder.cs
- test/EntityFramework.Storage.IntegrationTests/DatabaseProviderFixture.cs
- test/EntityFramework.Storage.IntegrationTests/DbContexts/ClientDbContextTests.cs
- test/EntityFramework.Storage.IntegrationTests/IntegrationTest.cs
- test/EntityFramework.Storage.IntegrationTests/Stores/ClientStoreTests.cs
- test/EntityFramework.Storage.IntegrationTests/Stores/DeviceFlowStoreTests.cs
- test/EntityFramework.Storage.IntegrationTests/Stores/IdentityProviderStoreTests.cs
- test/EntityFramework.Storage.IntegrationTests/Stores/PersistedGrantStoreTests.cs
- test/EntityFramework.Storage.IntegrationTests/Stores/ResourceStoreTests.cs
- test/EntityFramework.Storage.IntegrationTests/TokenCleanup/TokenCleanupTests.cs
- test/EntityFramework.Tests/DatabaseProviderBuilder.cs
- test/EntityFramework.Tests/DatabaseProviderFixture.cs
- test/EntityFramework.Tests/IntegrationTest.cs
- test/EntityFramework.Tests/Services/CorsPolicyServiceTests.cs
Reverts DuendeSoftware/IdentityServer#260
> Revert "add DBContext Pooling"

- src/EntityFramework.Storage/Configuration/ServiceCollectionExtensions.cs
- src/EntityFramework.Storage/DbContexts/ConfigurationDbContext.cs
- src/EntityFramework.Storage/DbContexts/PersistedGrantDbContext.cs
- src/EntityFramework.Storage/Options/ConfigurationStoreOptions.cs
- src/EntityFramework.Storage/Options/OperationalStoreOptions.cs
- test/EntityFramework.Storage.IntegrationTests/DatabaseProviderBuilder.cs
- test/EntityFramework.Storage.IntegrationTests/DatabaseProviderFixture.cs
- test/EntityFramework.Storage.IntegrationTests/DbContexts/ClientDbContextTests.cs
- test/EntityFramework.Storage.IntegrationTests/IntegrationTest.cs
- test/EntityFramework.Storage.IntegrationTests/Stores/ClientStoreTests.cs
- test/EntityFramework.Storage.IntegrationTests/Stores/DeviceFlowStoreTests.cs
- test/EntityFramework.Storage.IntegrationTests/Stores/IdentityProviderStoreTests.cs
- test/EntityFramework.Storage.IntegrationTests/Stores/PersistedGrantStoreTests.cs
- test/EntityFramework.Storage.IntegrationTests/Stores/ResourceStoreTests.cs
- test/EntityFramework.Storage.IntegrationTests/TokenCleanup/TokenCleanupTests.cs
- test/EntityFramework.Tests/DatabaseProviderBuilder.cs
- test/EntityFramework.Tests/DatabaseProviderFixture.cs
- test/EntityFramework.Tests/IntegrationTest.cs
- test/EntityFramework.Tests/Services/CorsPolicyServiceTests.cs
Addresses: #253
New PR to address merge issues with prior with the [first PR](https://github.com/DuendeSoftware/IdentityServer/pull/260).
> [EF] Change DbContext constructors to support pooling

- .github/workflows/ci.yml
- Directory.Build.targets
- global.json
> Updates for .NET 6 RC1

- src/IdentityServer/Hosting/DynamicProviders/Store/CachingIdentityProviderStore.cs
- src/IdentityServer/Services/Default/DefaultCache.cs
- src/IdentityServer/Services/Default/DefaultReplayCache.cs
Feature request from here: https://github.com/DuendeSoftware/IdentityServer/discussions/393
> Change the cache key separator to use more redis friendly value

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
> Update checkout action

- src/IdentityServer/Events/BackchannelAuthenticationSuccessEvent.cs
Removed XML comment for missing param.
> update XML comments

- src/IdentityServer/ResponseHandling/Default/AuthorizeInteractionResponseGenerator.cs
- src/IdentityServer/Services/Default/DistributedBackchannelAuthenticationThrottlingService.cs
- src/IdentityServer/Services/Default/DistributedDeviceFlowThrottlingService.cs
- src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs
- src/IdentityServer/Validation/Default/BackchannelAuthenticationRequestIdValidator.cs
- src/IdentityServer/Validation/Default/DeviceCodeValidator.cs
- test/IdentityServer.UnitTests/Services/Default/DistributedDeviceFlowThrottlingServiceTests.cs
Thus remove implicit conversions.
> Be very explicit when comparing DateTime and DateTimeOffset

- Directory.Build.targets
- src/IdentityServer/Constants.cs
- src/IdentityServer/Endpoints/BackchannelAuthenticationEndpoint.cs
- src/IdentityServer/Endpoints/Results/BackchannelAuthenticationResult.cs
- src/IdentityServer/Validation/Default/BackchannelAuthenticationRequestValidator.cs
- src/IdentityServer/Validation/Default/TokenRequestValidator.cs
* updated to latest IdentityModel preview
* updated last remaining places we had hard coded ciba constants
> Update the remaining ciba constants

- src/IdentityServer/Stores/Caching/CachingResourceStore.cs
Bug fix for a preview version of a 6.0 feature.
Fixes: #523
> Add prefix when using the call cache to prevent cache entries eclipsing other requests

- hosts/AspNetIdentity/Pages/Account/Login/Index.cshtml.cs
- hosts/AspNetIdentity/Pages/Account/Logout/Index.cshtml.cs
- hosts/AspNetIdentity/Pages/Consent/InputModel.cs
- hosts/AspNetIdentity/Pages/Device/InputModel.cs
- hosts/AspNetIdentity/Pages/Extensions.cs
- hosts/AspNetIdentity/Pages/ExternalLogin/Callback.cshtml.cs
- hosts/AspNetIdentity/Pages/SecurityHeadersAttribute.cs
- hosts/EntityFramework/Pages/Consent/InputModel.cs
- hosts/EntityFramework/Pages/Device/InputModel.cs
- hosts/EntityFramework/Pages/Extensions.cs
- hosts/EntityFramework/Pages/ExternalLogin/Callback.cshtml.cs
- hosts/EntityFramework/Pages/SecurityHeadersAttribute.cs
- hosts/main/Pages/ExternalLogin/Callback.cshtml.cs
* minor namespace and white space cleanup
* sync all 3 QS UIs
* removed the FindUserFromExternalProviderAsync helper, as it was often confusing
> Cleanup on the external callback quickstart UI

- hosts/AspNetIdentity/Pages/Account/Logout/Index.cshtml.cs
- hosts/AspNetIdentity/Pages/Ciba/Consent.cshtml.cs
- hosts/AspNetIdentity/Pages/Ciba/Index.cshtml.cs
- hosts/AspNetIdentity/Pages/ExternalLogin/Callback.cshtml.cs
- hosts/AspNetIdentity/Pages/ExternalLogin/Challenge.cshtml.cs
- hosts/AspNetIdentity/Pages/Home/Error/Index.cshtml.cs
- hosts/AspNetIdentity/Pages/Redirect/Index.cshtml.cs
- hosts/AspNetIdentity/Startup.cs
- hosts/EntityFramework/Pages/Account/Logout/Index.cshtml.cs
- hosts/EntityFramework/Pages/Account/Logout/LoggedOut.cshtml.cs
- hosts/EntityFramework/Pages/Ciba/Consent.cshtml.cs
- hosts/EntityFramework/Pages/Ciba/Index.cshtml.cs
- hosts/EntityFramework/Pages/ExternalLogin/Callback.cshtml.cs
- hosts/EntityFramework/Pages/ExternalLogin/Challenge.cshtml.cs
- hosts/EntityFramework/Pages/Home/Error/Index.cshtml.cs
- hosts/EntityFramework/Pages/Redirect/Index.cshtml.cs
- hosts/EntityFramework/Startup.cs
- hosts/main/Pages/Account/Logout/Index.cshtml.cs
- hosts/main/Pages/Account/Logout/LoggedOut.cshtml.cs
- hosts/main/Pages/Ciba/Index.cshtml.cs
- hosts/main/Pages/ExternalLogin/Callback.cshtml.cs
- hosts/main/Pages/ExternalLogin/Challenge.cshtml.cs
- hosts/main/Pages/Home/Error/Index.cshtml.cs
- hosts/main/Pages/Redirect/Index.cshtml.cs
- hosts/main/Startup.cs
> Add global authorization filter to pages

- src/IdentityServer/Validation/Default/License.cs
- test/IdentityServer.UnitTests/Validation/LicenseValidatorTests.cs
> Update community edition license validation rules for v6.0

- src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs
Moved most log entries from Debug to Trace, and Info to Debug.
> Reduce noise from key manager logging

- src/IdentityServer/Validation/Default/TokenValidator.cs
Fixes: https://github.com/DuendeSoftware/Support/issues/7
> Make invalid client behavior consistent in token validator

- Directory.Build.targets
> Update OTel libraries

- hosts/AspNetIdentity/Pages/Ciba/Consent.cshtml.cs
- hosts/EntityFramework/Pages/Ciba/Consent.cshtml.cs
- hosts/main/Pages/Ciba/Consent.cshtml.cs
Quickstart UI only bug.
Fixes: #927
> fix logger type for CIBA consent page

- src/IdentityServer/Validation/Default/TokenRequestValidator.cs
- test/IdentityServer.IntegrationTests/Endpoints/Token/RefreshTokenTests.cs
Fixes: https://github.com/DuendeSoftware/Support/issues/99
> capture session id value on token request when refresh token is being used

- src/IdentityServer/Extensions/IReadableStringCollectionExtensions.cs
- src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs
- src/IdentityServer/Validation/Default/BackchannelAuthenticationRequestValidator.cs
- src/IdentityServer/Validation/Default/TokenRequestValidator.cs
- test/IdentityServer.IntegrationTests/Endpoints/Authorize/ResourceTests.cs
- test/IdentityServer.IntegrationTests/Endpoints/Token/ResourceTests.cs
Fixes: https://github.com/DuendeSoftware/Support/issues/48
> Ignore empty query/form input values 

- src/IdentityServer/Extensions/ResourceExtensions.cs
- src/IdentityServer/Extensions/StringsExtensions.cs
- src/IdentityServer/Services/Default/OidcReturnUrlParser.cs
- src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs
- src/IdentityServer/Validation/Default/DefaultClientConfigurationValidator.cs
- test/IdentityServer.UnitTests/Extensions/StringExtensionsTests.cs
Fixes: https://github.com/DuendeSoftware/Support/issues/148
Resubmitting for correct base branch.
> fix URI validation to allow query params with encoded values

- .github/workflows/codeql-analysis.yml
- Directory.Build.targets
- build/build.csproj
> Minor updates to build

- src/IdentityServer/Test/TestBackchannelLoginUserValidator.cs
- src/IdentityServer/Validation/Default/NopBackchannelAuthenticationUserValidator.cs
- src/IdentityServer/Validation/IBackchannelAuthenticationUserValidator.cs
- src/IdentityServer/Validation/Models/BackchannelAuthenticationUserValidationResult.cs
- test/IdentityServer.IntegrationTests/Common/MockCibaUserValidator.cs
Fixes: https://github.com/DuendeSoftware/IdentityServer/issues/1042
> typo in CIBA BackchannelAuthenticationUserValidatonResult

- Duende.IdentityServer.sln
- clients/src/MvcJarJwt/Controllers/HomeController.cs
- clients/src/MvcJarJwt/Views/Home/CallApi.cshtml
- clients/src/MvcJarUriJwt/Controllers/HomeController.cs
- clients/src/MvcJarUriJwt/Views/Home/CallApi.cshtml
- hosts/main/Extensions/ExtensionGrantValidator.cs
- hosts/main7/Extensions/ExtensionGrantValidator.cs
Small tweaks for samples. Also, I added the net7 project into the main solution, as I'm sure we'll need to use it in the future.
> updates for the samples after testing .net7

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- Directory.Build.targets
- global.json
> Update to .NET 7 RTM

- Directory.Build.props
- test/EntityFramework.Storage.IntegrationTests/Stores/DeviceFlowStoreTests.cs
- test/IdentityServer.UnitTests/Storage/PersistedGrantFilterTests.cs
> Enable TreatWarningsAsErrors

- src/IdentityServer/Services/Default/BackChannelLogoutHttpClient.cs
- test/IdentityServer.IntegrationTests/Endpoints/EndSession/EndSessionTests.cs
Closes: https://github.com/DuendeSoftware/IdentityServer/issues/1026
> handle formatted back-channel logout error messages

- src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs
- src/IdentityServer/Constants.cs
- src/IdentityServer/Endpoints/AuthorizeCallbackEndpoint.cs
- src/IdentityServer/Endpoints/AuthorizeEndpoint.cs
- src/IdentityServer/Endpoints/BackchannelAuthenticationEndpoint.cs
- src/IdentityServer/Endpoints/CheckSessionEndpoint.cs
- src/IdentityServer/Endpoints/DeviceAuthorizationEndpoint.cs
- src/IdentityServer/Endpoints/DiscoveryEndpoint.cs
- src/IdentityServer/Endpoints/DiscoveryKeyEndpoint.cs
- src/IdentityServer/Endpoints/EndSessionCallbackEndpoint.cs
- src/IdentityServer/Endpoints/EndSessionEndpoint.cs
- src/IdentityServer/Endpoints/IntrospectionEndpoint.cs
- src/IdentityServer/Endpoints/TokenEndpoint.cs
- src/IdentityServer/Endpoints/TokenRevocationEndpoint.cs
- src/IdentityServer/Endpoints/UserInfoEndpoint.cs
- src/IdentityServer/Events/BackchannelAuthenticationFailureEvent.cs
- src/IdentityServer/Events/BackchannelAuthenticationSuccessEvent.cs
- src/IdentityServer/Events/DeviceAuthorizationFailureEvent.cs
- src/IdentityServer/Events/DeviceAuthorizationSuccessEvent.cs
- src/IdentityServer/Events/TokenIssuedFailureEvent.cs
- src/IdentityServer/Events/TokenIssuedSuccessEvent.cs
- src/IdentityServer/Events/UserLoginFailureEvent.cs
- src/IdentityServer/Events/UserLoginSuccessEvent.cs
- src/IdentityServer/Extensions/EndpointOptionsExtensions.cs
- src/IdentityServer/IdentityServerConstants.cs
- test/IdentityServer.UnitTests/Extensions/EndpointOptionsExtensionsTests.cs
- test/IdentityServer.UnitTests/Hosting/EndpointRouterTests.cs
Closes: https://github.com/DuendeSoftware/IdentityServer/issues/731
> Make constants for EndpointNames public

- src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs
- src/IdentityServer/Validation/IRedirectUriValidator.cs
Closes: https://github.com/DuendeSoftware/IdentityServer/issues/44
Docs needed: context params docs
> add new API to IRedirectUriValidator with more request context

- src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs
- src/IdentityServer/Validation/Default/LicenseValidator.cs
Several error log changes: 
* better license validation log entry to disable key management.
Closes https://github.com/DuendeSoftware/IdentityServer/issues/1017
* improve issuer license validation error message
Closes https://github.com/DuendeSoftware/IdentityServer/issues/918
* improve error on unprotecting signing keys
Closes https://github.com/DuendeSoftware/IdentityServer/issues/973
Closes https://github.com/DuendeSoftware/IdentityServer/issues/851
> improved error logs

- .gitignore
- .vscode/launch.json
- .vscode/tasks.json
This adds config to build and run the hosts and clients from vscode.
> Launch and tasks files for vscode

- src/IdentityServer/Configuration/DependencyInjection/Options/LoggingOptions.cs
- src/IdentityServer/Validation/Default/BackchannelAuthenticationRequestValidator.cs
Use the BackchannelAuthenticationRequestSensitiveValuesFilter in the BackchannelAuthenticationRequestValidator.
> Use correct sensitive values filter during CIBA

- src/IdentityServer/Endpoints/Results/AuthorizeResult.cs
- src/IdentityServer/Endpoints/Results/CheckSessionResult.cs
- src/IdentityServer/Endpoints/Results/EndSessionCallbackResult.cs
- src/IdentityServer/IdentityServerConstants.cs
- test/IdentityServer.UnitTests/Endpoints/Results/AuthorizeResultTests.cs
- test/IdentityServer.UnitTests/Endpoints/Results/CheckSessionResultTests.cs
> Expose CSP hashes as constants

- src/IdentityServer/Configuration/DependencyInjection/Options/CorsOptions.cs
- src/IdentityServer/Constants.cs
- src/IdentityServer/Endpoints/Results/AuthorizeInteractionPageResult.cs
- src/IdentityServer/Extensions/HttpContextExtensions.cs
- src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs
- src/IdentityServer/IdentityServerConstants.cs
- src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs
- src/IdentityServer/Services/Default/OidcReturnUrlParser.cs
- src/IdentityServer/Validation/Default/DefaultDPoPProofValidator.cs
- src/IdentityServer/Validation/Default/PrivateKeyJwtSecretValidator.cs
> Make ProtocolRoutePaths constants public

- src/IdentityServer/IdentityServerConstants.cs
- src/IdentityServer/Models/Contexts/LogoutNotificationContext.cs
- src/IdentityServer/Models/Contexts/LogoutNotificationReason.cs
- src/IdentityServer/Services/Default/DefaultBackChannelLogoutService.cs
- src/IdentityServer/Services/Default/DefaultSessionCoordinationService.cs
- src/IdentityServer/Services/Default/DefaultSessionManagementService.cs
- src/IdentityServer/Services/Default/LogoutNotificationService.cs
- src/IdentityServer/Services/ILogoutNotificationService.cs
- test/IdentityServer.IntegrationTests/Endpoints/EndSession/EndSessionTests.cs
Closes: https://github.com/DuendeSoftware/IdentityServer/issues/1198
> Send custom logout reason value in back channel logout notification token

- clients/src/APIs/DPoPApi/DPoPJwtBearerEvents.cs
- src/IdentityServer/Validation/Default/DefaultDPoPProofValidator.cs
- test/IdentityServer.IntegrationTests/Endpoints/Token/DPoPTokenEndpointTests.cs
- test/IdentityServer.UnitTests/Validation/DPoPProofValidatorTests.cs
DPoP jwt typ header value should be "dpop+jwt"
> Fix dpop jwt type

- src/IdentityServer/Validation/Default/License.cs
- test/IdentityServer.UnitTests/Validation/LicenseValidatorTests.cs
To better reflect the general configuration API feature (which is more than just DCR).
> change dcr license key flag to config_api

- src/IdentityServer/Services/Default/DefaultEventService.cs
Fixes: https://github.com/DuendeSoftware/Support/issues/614
> guard against NRE on HttpContext in DefaultEventService

- src/IdentityServer/Services/IIdentityServerInteractionService.cs
@josephdecock I think these will help on the templates work being done here: https://github.com/DuendeSoftware/IdentityServer.Templates/pull/37
> add missing nullable semantics on IIdentityServerInteractionService

- src/IdentityServer/Validation/Default/LicenseValidator.cs
- src/IdentityServer/Validation/Default/TokenRequestValidator.cs
Closes: https://github.com/DuendeSoftware/IdentityServer/issues/1266
> don't accept dpop request is license does not allow

- src/IdentityServer/Logging/Models/TokenRequestValidationLog.cs
> filter username in TokenRequestValidationLog when configured as a filter

- src/Storage/Models/Client.cs
Fixes: https://github.com/DuendeSoftware/IdentityServer/issues/1296
> Add nullability annotation to ClientClaimsPrefix

- hosts/EntityFramework/Pages/Admin/Clients/ClientRepository.cs
- hosts/EntityFramework/Pages/Admin/Clients/Edit.cshtml
For this issue: https://github.com/DuendeSoftware/IdentityServer.Templates/issues/41
We can sync the templates code base before the next release of the templates nuget.
> add InitiateLoginUri to EF admin UI code

- src/IdentityServer/Services/Default/DefaultUserSession.cs
- test/IdentityServer.UnitTests/Services/Default/DefaultUserSessionTests.cs
Merge this PR forward: https://github.com/DuendeSoftware/IdentityServer/pull/1353
> Merge 6.2.x patch into 6.3.x

- src/IdentityServer/Services/Default/OidcReturnUrlParser.cs
- src/IdentityServer/Services/IReturnUrlParser.cs
> Fixes nullability annotation on IReturnUrlParser.ParseAsync

- src/EntityFramework.Storage/Stores/DeviceFlowStore.cs
- src/IdentityServer/Hosting/IdentityServerMiddleware.cs
Closes: https://github.com/DuendeSoftware/IdentityServer/issues/735
> remove unnecessary call to ToModel in device flow

- src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs
- test/IdentityServer.IntegrationTests/Endpoints/Authorize/AuthorizeTests.cs
Fixes: https://github.com/DuendeSoftware/IdentityServer/issues/845#issuecomment-1405377531
> return error for unknown prompt values on authorize endpoint

- src/Configuration/Models/DynamicClientRegistration/DynamicClientRegistrationRequest.cs
- src/Configuration/Validation/DynamicClientRegistration/DynamicClientRegistrationValidator.cs
- src/IdentityServer/Configuration/DependencyInjection/Options/KeyManagementOptions.cs
- src/IdentityServer/Configuration/DependencyInjection/Options/ValidationOptions.cs
- src/IdentityServer/ResponseHandling/Default/TokenResponseGenerator.cs
- src/IdentityServer/ResponseHandling/Models/TokenResponse.cs
- src/IdentityServer/Services/Default/DefaultUserSession.cs
- src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs
Just some minor edits to xmldocs
> Minor DCR xmldoc fixes

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- Directory.Build.targets
- global.json
> Update to .NET8 Preview 6

- src/IdentityServer/Services/InMemory/InMemoryCorsPolicyService.cs
Related to https://github.com/DuendeSoftware/Support/issues/834
> Update xmldoc for InMemoryCorsPolicyService.cs

- hosts/main/Pages/Index.cshtml.cs
Minor fix for an optional dependency
> Fix optional license dependency

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- Directory.Build.targets
- global.json
> Update to .NET8 RC.1

- src/EntityFramework.Storage/Stores/ServerSideSessionStore.cs
> Make ServerSideSessionStore.GetAndRemoveExpiredSessionsAsync virtual

- src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs
The typos in key manager activity tracing. …
> Fixed typos in logging

- hosts/AspNetIdentity/Pages/Account/Login/Index.cshtml.cs
Just a smaller spelling fix.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate and use your Feedback for any purpose, …
> Small spelling fix in Index.cshtml.cs

- src/IdentityServer/Endpoints/AuthorizeEndpointBase.cs
- src/IdentityServer/Endpoints/PushedAuthorizationEndpoint.cs
- src/IdentityServer/Endpoints/TokenEndpoint.cs
- src/IdentityServer/Validation/Models/ValidatedAuthorizeRequest.cs
- src/Telemetry/Telemetry.cs
> Otel metrics for PAR

- global.json
> Don't allow pre-release SDKs

- build/Program.cs
> Cleanup build script

- src/IdentityServer/Services/Default/ServerSideSessionRefreshTokenService.cs
> Make ValidateRefreshTokenAsync virtual

- Directory.Build.targets
Removes source link as discussed here: https://github.com/DuendeSoftware/IdentityServer/pull/1473
> Remove redundant SourceLink dependency

- src/IdentityServer/Endpoints/Results/AuthorizeResult.cs
- src/IdentityServer/Events/Infrastructure/Event.cs
- src/IdentityServer/Models/Messages/ErrorMessage.cs
> Include Activity Id in ErrorMessage

- src/Storage/Models/Client.cs
It applies to Device Code flow too!
> Expanded xmldoc for Client.PollingInterval

- src/IdentityServer/Services/Default/DefaultPersistedGrantService.cs
- test/IdentityServer.UnitTests/Services/Default/DefaultPersistedGrantServiceTests.cs
> Return successfully deserialized grants even if some fail

- hosts/AspNetIdentity/Pages/ExternalLogin/Challenge.cshtml.cs
- hosts/Configuration/Pages/ExternalLogin/Challenge.cshtml.cs
- hosts/EntityFramework/Pages/ExternalLogin/Challenge.cshtml.cs
- hosts/main/Pages/ExternalLogin/Challenge.cshtml.cs
See https://github.com/DuendeSoftware/Support/issues/1061
> Update misleading comment

- Directory.Build.targets
Fixes [Support/#1266](https://github.com/DuendeSoftware/Support/issues/1266)
> Update dependencies for 6.3.x

- src/AspNetIdentity/Duende.IdentityServer.AspNetIdentity.csproj
- src/AspNetIdentity/README.md
- src/Configuration.EntityFramework/Duende.IdentityServer.Configuration.EntityFramework.csproj
- src/Configuration.EntityFramework/README.md
- src/Configuration/Duende.IdentityServer.Configuration.csproj
- src/Configuration/README.md
- src/EntityFramework.Storage/Duende.IdentityServer.EntityFramework.Storage.csproj
- src/EntityFramework.Storage/README.md
- src/EntityFramework/Duende.IdentityServer.EntityFramework.csproj
- src/EntityFramework/README.md
- src/IdentityServer/Duende.IdentityServer.csproj
- src/IdentityServer/README.md
- src/Storage/Duende.IdentityServer.Storage.csproj
- src/Storage/README.md
> Update GitHub readme, add NuGet readmes

- README.md
missing f
typo fix
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate and use your Feedback for any purpose, including to make …
> Typo fix in Update README.md

- src/IdentityServer/ResponseHandling/Default/AuthorizeInteractionResponseGenerator.cs
I just stumbled across this small typo. …
> fix typo in comment

- src/IdentityServer/Endpoints/DeviceAuthorizationEndpoint.cs
> Fix error log when device authorization endpoint fails

- src/IdentityServer/Configuration/DependencyInjection/PostConfigureApplicationCookieTicketStore.cs
since one of the constructors does not set logger
> fix null reference in PostConfigureApplicationCookieTicketStore PostConfigure

- src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs
- src/IdentityServer/Validation/Default/BackchannelAuthenticationRequestValidator.cs
- src/IdentityServer/Validation/Default/TokenRequestValidator.cs
* reduced list alloc
* remove redundant checks on empty enumerable
> better perf in request validation

- .github/workflows/bff-ci.yml
- .github/workflows/identity-server-ci.yml
- .github/workflows/templates-ci.yml
Improves the names on the workflows so easily discernible in github actions UI …
> Improve names on workflows

- src/IdentityServer/Licensing/LicenseUsageSummary.cs
Updated XML documentation to provide detailed descriptions for parameter usage in the LicenseUsageSummary record. This improves clarity, especially for auditing purposes, and ensures better understanding of the fields.
This is related to #1711
> Clarify documentation for LicenseUsageSummary parameters.

- .github/workflows/identity-server-ci.yml
Attempt to align the build configs across main and releases/is/7.1.x
> ci(is): align workflows across branches

- bff/build/Program.cs
- identity-server/build/Program.cs
- templates/build/Program.cs
Updates build programs to use update code signing certificate for nuget package signing. …
> Using new nuget code signing certificate

- bff/samples/IdentityServer/Pages/Index.cshtml
- bff/test/Duende.Bff.Tests/TestFramework/TestLoggerProvider.cs
Replaced static href attributes with ASP.NET tag helpers for links to accurately generate links.
> Update links and add alt attribute in Index page

- bff/.editorconfig
- bff/samples/Bff/Extensions.cs
- bff/samples/Blazor/PerComponent/PerComponent.Client/PerComponent.Client.csproj
- bff/samples/Blazor/WebAssembly/WebAssembly.Client/Program.cs
- bff/samples/Hosts.AppHost/Hosts.AppHost.csproj
- bff/samples/Hosts.AppHost/Program.cs
- bff/samples/Hosts.ServiceDefaults/AppHostServices.cs
- bff/samples/Hosts.Tests/TestInfra/AppHostFixture.cs
- bff/samples/IdentityServer/ServiceDiscoveringClientStore.cs
One of the blazor samples wasn't configured correctly, so the api call never completed.  …
> fix blazor samples

- .github/workflows/practices-check-pr.yml
Will fail a PR if it doesn't...
We can update this with additional checks (e.g. Milestone) in a follow up PR.
> Add a workflow that checks that a PR is following our practices for labels, assignee etc.

- bff/test/Duende.Bff.Tests/Endpoints/DpopRemoteEndpointTests.cs
- bff/test/Duende.Bff.Tests/Endpoints/RemoteEndpointTests.cs
Fix test stabilization issues with this test …
> BFF - fix occasionally failing dpop test

- .github/CODEOWNERS 
This will automatically assign reviewers to PRs
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate and use your Feedback for …
> Add CODEOWERS definition

- .github/ISSUE_TEMPLATE/config.yml
- bff/README.md
- bff/src/Duende.Bff.EntityFramework/README.md
- bff/src/Duende.Bff.Yarp/README.md
- bff/src/Duende.Bff/README.md
- identity-server/README.md
- identity-server/src/AspNetIdentity/README.md
- identity-server/src/Configuration.EntityFramework/README.md
- identity-server/src/Configuration/README.md
- identity-server/src/EntityFramework.Storage/README.md
- identity-server/src/EntityFramework/README.md
- identity-server/src/IdentityServer/README.md
- identity-server/src/Storage/README.md
Ready to go once Community repo is public.
> Update support links to developer community

- identity-server/test/IdentityServer.IntegrationTests/Hosting/ServerSideSessionTests.cs
When these tests were added they were not added with the `Trait` attribute like the rest of the files. Adding that attribute now to keep things consistent. …
> Adding Missing Test Attributes

- .github/workflow-gen/Program.cs
- .github/workflows/bff-ci.yml
- .github/workflows/identity-server-ci.yml
- Directory.Packages.props
- bff/bff.v3.ncrunchsolution
- bff/hosts/Blazor/PerComponent/Hosts.Bff.Blazor.PerComponent.Client/Components/LoginDisplay.razor
- bff/hosts/Hosts.Bff.EF/.gitignore
- bff/test/Bff.Tests/Bff.Tests.net8.0.v3.ncrunchproject
- bff/test/Bff.Tests/Bff.Tests.net9.0.v3.ncrunchproject
- bff/test/Bff.Tests/Properties/launchSettings.json
- bff/test/Hosts.Tests/BffBlazorWebAssemblyTests.cs
- bff/test/Hosts.Tests/BlazorPerComponentTests.cs
- bff/test/Hosts.Tests/Hosts.Tests.csproj
- bff/test/Hosts.Tests/PageModels/BlazorModel.cs
- bff/test/Hosts.Tests/PageModels/LogOutPageModel.cs
- bff/test/Hosts.Tests/PageModels/LoginPageModel.cs
- bff/test/Hosts.Tests/PageModels/PageModel.cs
- bff/test/Hosts.Tests/PageModels/PerComponentPageModel.cs
- bff/test/Hosts.Tests/PageModels/WeatherPageModel.cs
- bff/test/Hosts.Tests/PageModels/WebAssemblyPageModel.cs
- bff/test/Hosts.Tests/PlaywrightTestBase.cs
- bff/test/Hosts.Tests/TestInfra/AppHostFixture.cs
Introduces playwright tests (front-end) for the blazor samples.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate and use your …
> introducing playwright test for blazor

- identity-server/hosts/AspNetIdentity/Pages/ServerSideSessions/Index.cshtml
- identity-server/hosts/Configuration/Pages/ServerSideSessions/Index.cshtml
- identity-server/hosts/EntityFramework/Pages/ServerSideSessions/Index.cshtml
- identity-server/hosts/main/Pages/ServerSideSessions/Index.cshtml
- templates/src/IdentityServerAspNetIdentity/HostingExtensions.cs
- templates/src/IdentityServerAspNetIdentity/Pages/ServerSideSessions/Index.cshtml
- templates/src/IdentityServerEmpty/HostingExtensions.cs
- templates/src/IdentityServerEntityFramework/Pages/ServerSideSessions/Index.cshtml
- templates/src/IdentityServerInMem/HostingExtensions.cs
- templates/src/IdentityServerInMem/Pages/ServerSideSessions/Index.cshtml
Update all in code links to docs to v7.
> Update in code links to v7

- .github/workflow-gen/Program.cs
- .github/workflows/bff-ci.yml
- .github/workflows/bff-release.yml
- .github/workflows/identity-server-ci.yml
- .github/workflows/identity-server-release.yml
- .gitignore
- Allow you to specify a target branch to release from (for patching previous releases)
- Allow you to override a specific git tag
- No longer pushing to myget
- Always sign / push on a release build
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant …
> Adjust release process to align with foss

- bff/src/Bff.Blazor.Client/Bff.Blazor.Client.csproj
- bff/src/Bff.Blazor/Bff.Blazor.csproj
- bff/src/Bff.EntityFramework/Bff.EntityFramework.csproj
the packages for BFF.Blazor and EF had a different casing than the other packages
This pr fixes that. 
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all …
> fix casing of bff.blazor packages

- bff/src/Bff.Blazor/Bff.Blazor.csproj
- bff/src/Bff.Blazor/BffServerAuthenticationStateProvider.cs
> check license in blazor

- nuget.config
Removes an unnecessary file from the source to avoid causing hassle. …
> The `nuget.config` file has been completely removed.

- .github/workflow-gen/Program.cs
- .github/workflows/bff-ci.yml
- .github/workflows/identity-server-ci.yml
Adds `|| (github.event_name == 'workflow_dispatch')` to the job `if`.
> Run job if event is workflow dispatch

- identity-server/src/IdentityServer/Services/Default/DefaultUserSession.cs
Merge fixes from the 7.1.1 release forward to main
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate and use your Feedback for …
> Merge 7.1.1 Fixes Forward to Main

- .github/workflow-gen/Program.cs
- .github/workflows/identity-server-ci.yml
- .github/workflows/identity-server-release.yml
> Change where to expect artifacts during upload

- .editorconfig
- .github/workflow-gen/.editorconfig
- bff/templates/.editorconfig
- identity-server/templates/.editorconfig
> reformat .editorconfig

- bff/.config/dotnet-tools.json
Somehow the tools config was missing. This PR restores it. 
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate and use your …
> restore the tools config

- Directory.Packages.props
- identity-server/test/EntityFramework.IntegrationTests/Services/CorsPolicyServiceTests.cs
- identity-server/test/EntityFramework.IntegrationTests/Storage/DbContexts/ClientDbContextTests.cs
- identity-server/test/EntityFramework.IntegrationTests/Storage/Stores/DeviceFlowStoreTests.cs
- identity-server/test/EntityFramework.IntegrationTests/Storage/Stores/PersistedGrantStoreTests.cs
- identity-server/test/EntityFramework.IntegrationTests/Storage/Stores/ResourceStoreTests.cs
- identity-server/test/EntityFramework.Storage.UnitTests/Mappers/ApiResourceMappersTests.cs
- identity-server/test/EntityFramework.Storage.UnitTests/Mappers/ClientMappersTests.cs
- identity-server/test/EntityFramework.Storage.UnitTests/Mappers/IdentityProviderMappersTests.cs
- identity-server/test/EntityFramework.Storage.UnitTests/Mappers/IdentityResourcesMappersTests.cs
- identity-server/test/EntityFramework.Storage.UnitTests/Mappers/PersistedGrantMappersTests.cs
- identity-server/test/EntityFramework.Storage.UnitTests/Mappers/PushedAuthorizationRequestMappersTests.cs
- identity-server/test/EntityFramework.Storage.UnitTests/Mappers/ScopeMappersTests.cs
- identity-server/test/IdentityServer.UnitTests/Extensions/EndpointOptionsExtensionsTests.cs
- identity-server/test/IdentityServer.UnitTests/Extensions/IdentityServerBuilderExtensionsCryptoTests.cs
- identity-server/test/IdentityServer.UnitTests/Extensions/StringExtensionsTests.cs
- identity-server/test/IdentityServer.UnitTests/Extensions/TokenExtensionsTests.cs
- identity-server/test/IdentityServer.UnitTests/Extensions/ValidatedAuthorizeRequestExtensionsTests.cs
- identity-server/test/IdentityServer.UnitTests/ResponseHandling/DeviceAuthorizationResponseGeneratorTests.cs
- identity-server/test/IdentityServer.UnitTests/Storage/PersistedGrantFilterTests.cs
- test.props
Aligned with rest of code base in the repository.
> Convert a bunch of test assertions from xunit assert to Shoudly

- Directory.Packages.props
Fixes a transitive dependendency constraint issue. 1.50.0 is references the correct transitive nuget package xunit.extensibility.core >= 2.8.0.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, …
> Update Microsoft.Playwright.Xunit package

- identity-server/aspire/aspire.orchestrator/aspire.orchestrator.AppHost/Properties/launchSettings.json
I always want https, and removing it from launchSettings makes it not show up as an option in some tooling, so I always like to remove it. Just a small nit, but I like doing this :)
> Remove http launchSettings from aspire

- identity-server/clients/src/ConsoleDcrClient/Program.cs
- identity-server/clients/src/ConsolePrivateKeyJwtClient/Program.cs
- Updated private key jwt authentication to use strict audience validation
- Dynamically generate a client id and secret during Dynamic Client Registration (otherwise DCR tests succeed even when DCR is not available).
> Test Client Improvements

- identity-server/templates/src/IdentityServerAspNetIdentity/IdentityServerAspNetIdentity.csproj
- identity-server/templates/src/IdentityServerEmpty/IdentityServerEmpty.csproj
- identity-server/templates/src/IdentityServerEntityFramework/IdentityServerEntityFramework.csproj
- identity-server/templates/src/IdentityServerInMem/IdentityServerInMem.csproj
Updates the Duende package references in the templates to use the new 7.2.0 packages …
> Update templates to use 7.2.0 packages

- identity-server/src/IdentityServer/Validation/Default/UserInfoRequestValidator.cs
Originally submitted by @SimonCropp. I got git into a weird state and had to recreate his PR.
> fix null ref in UserInfoRequestValidator

- identity-server/templates/src/IdentityServerEntityFramework/Pages/Admin/Clients/ClientRepository.cs
- identity-server/templates/src/IdentityServerEntityFramework/Pages/Admin/Clients/Edit.cshtml.cs
- identity-server/templates/src/UI/Pages/ServerSideSessions/Index.cshtml.cs
Updates class name to avoid potential namespace collisions with System.ClientModel …
> Avoid Namespace Collisions with System.ClientModel in EF Template

- bff/templates/src/BffBlazor/BffBlazor/BffBlazor.csproj
- bff/templates/src/BffLocalApi/BffLocalApi.csproj
- bff/templates/src/BffRemoteApi/BffRemoteApi.csproj
Forgot to bump some package versions in templates
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate and use your Feedback for …
> Bump package versions in templates

- .github/workflow-gen/Program.cs
- .github/workflow-gen/workflow-gen.csproj
- .github/workflows/aspnetcore-authentication-jwtbearer-ci.yml
- .github/workflows/bff-ci.yml
- .github/workflows/identity-server-ci.yml
Will speed up the CodeQL job significantly
(upgrades `Logicality.GitHub.Actions.Workflow` packages)
Before:
After:
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license …
> Run CodeQL on a larger hosted runner.

- identity-server/src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs
- identity-server/src/IdentityServer/Configuration/IdentityServerApplicationBuilderExtensions.cs
- identity-server/src/IdentityServer/Hosting/EndpointRouter.cs
- identity-server/src/IdentityServer/Licensing/V2/LicenseExpirationChecker.cs
- identity-server/test/IdentityServer.UnitTests/Hosting/EndpointRouterTests.cs
- identity-server/test/IdentityServer.UnitTests/Licensing/v2/LicenseExpirationCheckerTests.cs
Adds a warning to logs about expired license …
> License Expiration Warning

- .gitignore
- Directory.Packages.props
- bff/test/Bff.Tests/Bff.Tests.csproj
- bff/test/Bff.Tests/PublicApiVerificationTests.VerifyPublicApi_Bff.verified.txt
- bff/test/Bff.Tests/PublicApiVerificationTests.VerifyPublicApi_Bff_Blazor.verified.txt
- bff/test/Bff.Tests/PublicApiVerificationTests.VerifyPublicApi_Bff_Blazor_Client.verified.txt
- bff/test/Bff.Tests/PublicApiVerificationTests.VerifyPublicApi_Bff_EntityFramework.verified.txt
- bff/test/Bff.Tests/PublicApiVerificationTests.VerifyPublicApi_Bff_Yarp.verified.txt
- bff/test/Bff.Tests/PublicApiVerificationTests.cs
Makes sure public api tests are in place, so we can track public api changes over time.  …
> Add public api tests

- bff/migrations/Directory.Build.props
- bff/src/Bff.Blazor.Client/Bff.Blazor.Client.csproj
- bff/src/Directory.Build.props
- bff/test/Bff.Tests/Blazor/BffBlazorHost.cs
- bff/test/Bff.Tests/Blazor/Components/Routes.razor
- bff/test/Directory.Build.props
Applied root namespaces to BFF projects.  …
> setup root namespace for BFF

- .github/workflow-gen/Program.cs
- .github/workflows/aspnetcore-authentication-jwtbearer-ci.yml
- .github/workflows/bff-ci.yml
- .github/workflows/identity-server-ci.yml
Update the build pathspec to include .editorconfig
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate and use your Feedback for …
> Update the build pathspec to include .editorconfig

- .gitattributes
https://github.com/github-linguist/linguist/blob/main/docs/overrides.md
This is incorrect.
> Tell linquistic that the primary repository language is C#

- bff/hosts/Hosts.ServiceDefaults/Extensions.cs
- bff/hosts/Hosts.ServiceDefaults/Hosts.ServiceDefaults.csproj
- bff/src/Bff.EntityFramework/Store/UserSessionStore.cs
- bff/src/Bff/Configuration/BffServiceCollectionExtensions.cs
- bff/src/Bff/Internal/BffMetrics.cs
- bff/src/Bff/SessionManagement/SessionStore/IUserSessionStoreCleanup.cs
- bff/src/Bff/SessionManagement/SessionStore/SessionCleanupHost.cs
- bff/src/Bff/SessionManagement/TicketStore/ServerSideTicketStore.cs
- bff/test/Bff.Tests/Blazor/ServerSideTokenStoreTests.cs
- bff/test/Bff.Tests/PublicApiVerificationTests.VerifyPublicApi_Bff.verified.txt
- bff/test/Bff.Tests/PublicApiVerificationTests.VerifyPublicApi_Bff_EntityFramework.verified.txt
Adds OTEL metrics to the BFF for:
- create session
- remove session
fixes #1942 …
> Add metrics to BFF

- identity-server/src/IdentityServer/Licensing/V2/LicenseAccessor.cs
- identity-server/src/IdentityServer/Licensing/V2/LicenseExpirationChecker.cs
- identity-server/src/IdentityServer/Licensing/V2/Log.cs
- identity-server/src/IdentityServer/Licensing/V2/ProtocolRequestCounter.cs
Updated log statements in V2 licensing code to use source generators …
> Source Generator Based Logging for V2 License Code

- identity-server/src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs
This is a minor cleanup of an old todo.
> Use PAR IdentityModel constants

- identity-server/src/IdentityServer/Licensing/IdentityServerLicenseValidator.cs
- identity-server/src/IdentityServer/Licensing/V2/LicenseUsageTracker.cs
- identity-server/src/IdentityServer/Licensing/V2/Log.cs
- identity-server/test/IdentityServer.UnitTests/Configuration/DependencyInjection/PostConfigureApplicationCookieTicketStoreTests.cs
- identity-server/test/IdentityServer.UnitTests/Licensing/IdentityServerLicenseValidatorTests.cs
- identity-server/test/IdentityServer.UnitTests/Licensing/v2/LicenseUsageTests.cs
- identity-server/test/IdentityServer.UnitTests/Validation/AuthorizeRequest Validation/Authorize_ProtocolValidation_Resources.cs
- identity-server/test/IdentityServer.UnitTests/Validation/Setup/Factory.cs
Adds warnings around client usage to the V2 licensing checks
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate and use your …
> V2 License Client Warnings

- identity-server/hosts/Shared/Customization/CustomClientRegistrationProcessor.cs
Update the custom client registration processor to ensure compatibility with the Entity Framework client configuration.
> Fix DCR customizations for EF client configuration

- .github/workflow-gen/StepExtensions.cs
- .github/workflows/aspnetcore-authentication-jwtbearer-ci.yml
- .github/workflows/bff-ci.yml
- .github/workflows/identity-server-ci.yml
> Can disable codeql analysis through an environment variable.

- identity-server/src/IdentityServer/Validation/Default/PrivateKeyJwtSecretValidator.cs
- identity-server/test/IdentityServer.UnitTests/Validation/Secrets/PrivateKeyJwtSecretValidation.cs
Merge the bugfix from 7.2.1 forward to main.
> Merge 7.2.1's fix forward to main

- templates.props
This should fix the template deployment pipeline
> Fix minver in templates

- Directory.Build.props
Merges 7.0 forward to 7.1, bringing forward our minver config
> 7.1 minver fix

- identity-server/hosts/EntityFramework-dotnet9/Host.EntityFramework.dotnet9.csproj
- identity-server/hosts/EntityFramework/Host.EntityFramework.csproj
- identity-server/migrations/IdentityServerDb/IdentityServerDb.csproj
- identity-server/test/IdentityServer.IntegrationTests/Hosting/LicenseTests.cs
> Trivial Typos

- bff/templates/src/BffBlazorAutoRenderMode/.template.config/dotnetcli.host.json
- bff/templates/src/BffBlazorAutoRenderMode/.template.config/template.json
- bff/templates/src/BffBlazorAutoRenderMode/BffBlazorAutoRenderMode.Client/BffBlazorAutoRenderMode.Client.csproj
- bff/templates/src/BffBlazorAutoRenderMode/BffBlazorAutoRenderMode.sln
- bff/templates/src/BffBlazorAutoRenderMode/BffBlazorAutoRenderMode/BffBlazorAutoRenderMode.csproj
- bff/templates/src/BffBlazorAutoRenderMode/BffBlazorAutoRenderMode/Components/App.razor
- bff/templates/src/BffBlazorAutoRenderMode/BffBlazorAutoRenderMode/Program.cs
Stacks on #1995 to add a solution file to the BFF Blazor template …
> Add Solution File to BFF Blazor Template

- identity-server/templates/src/IdentityServerAspNetIdentity/HostingExtensions.cs
- identity-server/templates/src/IdentityServerAspNetIdentity/IdentityServerAspNetIdentity.csproj
- identity-server/templates/src/IdentityServerEntityFramework/HostingExtensions.cs
- identity-server/templates/src/IdentityServerEntityFramework/IdentityServerEntityFramework.csproj
- identity-server/templates/src/IdentityServerInMem/HostingExtensions.cs
- identity-server/templates/src/IdentityServerInMem/IdentityServerInMem.csproj
https://github.com/dotnet/aspnetcore/issues/61817
> Microsoft.AspnetCore.Authentication.Google -> Use demo.duendesoftware.com

- identity-server/clients/src/ConsoleDcrClient/ConsoleDcrClient.csproj
- identity-server/hosts/AspNetIdentity/Host.AspNetIdentity.csproj
- identity-server/hosts/Configuration/Host.Configuration.csproj
- identity-server/hosts/EntityFramework-dotnet9/Host.EntityFramework.dotnet9.csproj
- identity-server/hosts/EntityFramework/Host.EntityFramework.csproj
- identity-server/hosts/main/Host.Main.csproj
- identity-server/src/EntityFramework.Storage/Duende.IdentityServer.EntityFramework.Storage.csproj
> Fix tabs -> spaces in several csproj's

- identity-server/src/IdentityServer/Licensing/V2/Log.cs
- identity-server/test/IdentityServer.IntegrationTests/Hosting/LicenseTests.cs
- identity-server/test/IdentityServer.UnitTests/Licensing/v2/ProtocolRequestCounterTests.cs
> Use duende.link for trial mode docs

- identity-server/src/IdentityServer/ResponseHandling/Default/AuthorizeInteractionResponseGenerator.cs
- identity-server/src/IdentityServer/Services/Default/DefaultConsentService.cs
- identity-server/src/IdentityServer/Services/IDeviceFlowInteractionService.cs
- identity-server/src/IdentityServer/Services/IUserSession.cs
- identity-server/src/IdentityServer/Stores/Default/DefaultAuthorizationCodeStore.cs
- identity-server/src/IdentityServer/Stores/Default/DefaultUserConsentStore.cs
> Nit: Fix some typos

- identity-server/src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs
- identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/IdentityServerOptionsDiagnosticEntry.cs
- identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticEntries/IdentityServerOptionsDiagnosticEntryTests.cs
Stacks on #2023 to add a diagnostic entry for IdentityServerOptions …
> IdentityServerOptions Diagnostic Entry

- identity-server/src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs
- identity-server/src/IdentityServer/Licensing/V2/Diagnostics/DiagnosticEntries/EndpointUsageDiagnosticEntry.cs
- identity-server/test/IdentityServer.UnitTests/Licensing/v2/DiagnosticEntries/EndpointUsageDiagnosticEntryTests.cs
Adds diagnostic entry for tracking how many requests each endpoint receives
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate …
> Endpoint Usage Diagnostic Entry

- bff/hosts/Blazor/PerComponent/Hosts.Bff.Blazor.PerComponent/Program.cs
- bff/hosts/Blazor/WebAssembly/Hosts.Bff.Blazor.WebAssembly/Program.cs
- bff/hosts/Hosts.Bff.EF/Extensions.cs
- bff/hosts/Hosts.Bff.InMemory/Program.cs
- bff/hosts/Hosts.Bff.MultiFrontend/Program.cs
- bff/performance/Bff.Benchmarks/Hosts/BffHost.cs
- bff/src/Bff/BffEndpointRouteBuilderExtensions.cs
- bff/src/Bff/DynamicFrontends/Internal/ConfigureBffStartupFilter.cs
- bff/test/Bff.Tests/Headers/GeneralTests.cs
- bff/test/Bff.Tests/TestInfra/BffTestHost.cs
- bff/test/Bff.Tests/TestInfra/TestHostContext.cs
The management endpoints can be automatically wired up. But, we do need to check if this is already done to prevent errors. 
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive …
> automatically map the management endpoints

- bff/src/Bff.Yarp/RouteBuilderExtensions.cs
- bff/test/Bff.Tests/BffFrontendIndexTests.cs
- bff/test/Bff.Tests/BffRemoteApiTests.cs
- bff/test/Bff.Tests/Endpoints/DPoPTestsWithManualAuthentication.cs
- bff/test/Bff.Tests/Endpoints/DpopRemoteEndpointTests.cs
- bff/test/Bff.Tests/Endpoints/RemoteEndpointTests.cs
- bff/test/Bff.Tests/Endpoints/YarpTests.cs
- bff/test/Bff.Tests/Headers/ApiAndBffUseForwardedHeaders.cs
- bff/test/Bff.Tests/Headers/ApiUseForwardedHeaders.cs
- bff/test/Bff.Tests/PublicApiVerificationTests.VerifyPublicApi_Bff_Yarp.verified.txt
- bff/test/Bff.Tests/TestInfra/TestData.cs
- **integration test for yarp transform**
- **introduce tests for timeouts**
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate …
> Adds tests for yarp transformers and makes the request config configurable. 

- Directory.Packages.props
- identity-server/src/IdentityServer/Validation/Default/PrivateKeyJwtSecretValidator.cs
Updated IdentityModel to 7.1.0 and replaced strings with new constants from IdenityModel …
> Updated to version 7.1.0 of IdentityModel

- identity-server/src/Directory.Build.props
A combination of enable All on AnalysisMode while suppressing existing violations. This sets us up to not introduce new violations while giving us runway to work on addressing the existing violations over time.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You …
> Enable AnalysisMode All

- bff/hosts/Hosts.Bff.Performance/Program.cs
- bff/hosts/Hosts.Bff.Performance/Properties/launchSettings.json
- bff/hosts/Hosts.Bff.Performance/Services/BffService.cs
- bff/hosts/Hosts.Bff.Performance/Services/IdentityServerService.cs
- bff/hosts/Hosts.Bff.Performance/Services/MultiFrontendBffService.cs
- bff/hosts/Hosts.Bff.Performance/Services/SingleFrontendBffService.cs
- Allows the enabling of specific services
- Adds the ability XForwarded Headers
- Uppercases Environment Variable Key names
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive …
> Refine configuration and honor XForwarded Headers

- bff/src/Bff/BffBuilderExtensions.cs
- bff/src/Bff/DynamicFrontends/Internal/BffCacheClearingHostedService.cs
- bff/src/Bff/DynamicFrontends/Internal/ConfigureBffStartupFilter.cs
- bff/src/Bff/Otel/LogMessages.cs
- bff/test/Bff.Tests/BffFrontendSigninTests.cs
- bff/test/Bff.Tests/ConventionTests.cs
Clear ATM caches on frontend changes.  …
> clear ATM cache on frontend change

- .github/workflow-gen/Program.cs
- .github/workflows/aspnetcore-authentication-jwtbearer-release.yml
- .github/workflows/bff-release.yml
- .github/workflows/identity-server-release.yml
This should fix an issue where the validation fails to start bash
> Validate version input after checkout

- Directory.Packages.props
* Bumping to ATM to RC2
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate and use your Feedback for any purpose, including to …
> bump to atm 4.0.0-rc.2

- identity-server/src/Directory.Build.props
- identity-server/src/EntityFramework/TokenCleanupHost.cs
- identity-server/src/IdentityServer/Hosting/ServerSideSessionCleanupHost.cs
- identity-server/src/IdentityServer/Infrastructure/MessageCookie.cs
- identity-server/src/IdentityServer/ResponseHandling/Default/AuthorizeInteractionResponseGenerator.cs
- identity-server/src/IdentityServer/Services/Default/DefaultRefreshTokenService.cs
- identity-server/src/IdentityServer/Validation/Default/BackchannelAuthenticationRequestIdValidator.cs
- identity-server/src/IdentityServer/Validation/Default/DeviceCodeValidator.cs
Stacks on #2171 to remove [CA2253](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2253) from the NoWarn list and address the resulting violations.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a …
> Address CA2253 Violations

- identity-server/templates/src/IdentityServer/IdentityServerTemplate.csproj
- identity-server/templates/src/IdentityServerAspNetIdentity/IdentityServerAspNetIdentity.csproj
- identity-server/templates/src/IdentityServerEmpty/IdentityServerEmpty.csproj
- identity-server/templates/src/IdentityServerEntityFramework/IdentityServerEntityFramework.csproj
- identity-server/templates/src/IdentityServerInMem/IdentityServerInMem.csproj
Update from rc.2 to GA release!
> Update to 7.3.0 in templates

- identity-server/src/Configuration/Licensing/LicenseValidator.cs
- identity-server/src/Directory.Build.props
- identity-server/src/EntityFramework/TokenCleanupHost.cs
- identity-server/src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Additional.cs
- identity-server/src/IdentityServer/Configuration/IdentityServerApplicationBuilderExtensions.cs
- identity-server/src/IdentityServer/Endpoints/AuthorizeEndpointBase.cs
- identity-server/src/IdentityServer/Endpoints/PushedAuthorizationEndpoint.cs
- identity-server/src/IdentityServer/Endpoints/UserInfoEndpoint.cs
- identity-server/src/IdentityServer/Hosting/ServerSideSessionCleanupHost.cs
- identity-server/src/IdentityServer/Licensing/LicenseValidator.cs
- identity-server/src/IdentityServer/Licensing/V2/LicenseAccessor.cs
- identity-server/src/IdentityServer/Logging/ILoggerExtensions.cs
- identity-server/src/IdentityServer/Logging/SanitizedLogger.cs
- identity-server/src/IdentityServer/ResponseHandling/Default/AuthorizeResponseGenerator.cs
- identity-server/src/IdentityServer/Services/Default/DefaultDeviceFlowInteractionService.cs
- identity-server/src/IdentityServer/Services/Default/KeyManagement/FileSystemKeyStore.cs
- identity-server/src/IdentityServer/Validation/Default/BackchannelAuthenticationRequestValidator.cs
- identity-server/src/IdentityServer/Validation/Default/DefaultDPoPProofValidator.cs
- identity-server/src/IdentityServer/Validation/Default/DeviceAuthorizationRequestValidator.cs
- identity-server/src/IdentityServer/Validation/Default/EndSessionRequestValidator.cs
- identity-server/src/IdentityServer/Validation/Default/RequestObjectValidator.cs
- identity-server/src/IdentityServer/Validation/Default/TokenRequestValidator.cs
- identity-server/src/IdentityServer/Validation/Default/TokenValidator.cs
Stacks on #2175 to remove [CA5394](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca5394) from the NoWarn list and address the resulting violations.
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a …
> Address CA5394 Violations

- templates/README.md
Fix the README by adding our new template description.
> Add duende-is to templates README.md

- identity-server/src/Configuration/Licensing/LicenseValidator.cs
- identity-server/src/IdentityServer/Licensing/LicenseValidator.cs
Updated log messages not using short links to do so
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights necessary to incorporate and use your Feedback …
> More Log Messages to Short Links

- Directory.Packages.props
- bff/src/Bff/Configuration/BffUserAccessTokenParameters.cs
- identity-server/clients/src/MvcAutomaticTokenManagement/Controllers/HomeController.cs
- identity-server/clients/src/MvcDPoP/Controllers/HomeController.cs
- identity-server/clients/src/Web/Pages/Secure.cshtml.cs
Update to Access Token Management 4.0.0. 
Note that this won't succeed until we release!
> Update to ATM-4.0.0

- Directory.Packages.props
- aspnetcore-authentication-jwtbearer/test/AspNetCore.Authentication.JwtBearer.Tests/DPoPIntegrationTests.cs
- aspnetcore-authentication-jwtbearer/test/AspNetCore.Authentication.JwtBearer.Tests/TestDPoPNonceStore.cs
- aspnetcore-authentication-jwtbearer/test/AspNetCore.Authentication.JwtBearer.Tests/TestFramework/AppHost.cs
Updated the tests for JwtBearer extensions to use the latest version of Access Token Management
If You provide us with any comments, bug reports, feedback, enhancements, or modifications proposed or suggested by You for the Software, such Feedback is provided on a non-confidential basis (notwithstanding any notice to the contrary You may include in any accompanying communication), and Licensor shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Software. You hereby grant Licensor a perpetual, irrevocable, transferable, sublicensable, nonexclusive license under all rights …
> Update JwtBearer Extensions Test to Latest ATM
